// Cấu hình tập trung cho toàn bộ module AI tư vấn ẩm thực và xếp hạng món ăn.
export const AI_PARAMETERS = {
  THRESHOLDS: {
    minSimilarity: 0.7,
    directMatch: 0.6,
    rerankingMinDistanceScore: 0.5,
  },
  DECAY: {
    distanceFactor: -0.07,
  },
  WEIGHTS: {
    intent: 0.4,
    embedding: 0.2,
    distance: 0.15,
    price: 0.1,
    rating: 0.05,
    context: 0.1,
  },
  MOBILITY_LIMITS: {
    lazyNearKm: 1.5,
    lazyFarKm: 3.0,
    exploreMinKm: 3.0,
  },
  PRICE_LIMITS: {
    rewardThreshold: 80000,
  },
  EMOTION_LIMITS: {
    tiredStressedNearKm: 2.0,
  },
  DEFAULT_VALUES: {
    conversationTitle: 'Đoạn chat mới',
    rerankingDefaultRating: 0.8,
  },
  SYNONYMS: {
    companion: {
      SINGLE: [
        '1 mình',
        'cô đơn',
        'một mình',
        'lẻ loi',
        'tự kỷ',
        'đơn thân',
        'mình tôi',
      ],
      FAMILY: [
        'gia đình',
        'bố mẹ',
        'vợ con',
        'nhà mình',
        'phụ huynh',
        'con cái',
        'nhà tôi',
      ],
      DATE: [
        'người yêu',
        'hẹn hò',
        'ghẹ',
        'bồ',
        'crush',
        'bạn gái',
        'bạn trai',
        'gấu',
      ],
      FRIENDS: [
        'bạn bè',
        'đồng nghiệp',
        'tụ tập',
        'nhóm',
        'team',
        'công ty',
        'hội nhóm',
        'cơ quan',
      ],
    } as Record<string, string[]>,
    mobility: {
      LAZY: [
        'lười',
        'ngại đi',
        'ngại đi xa',
        'ship',
        'mang về',
        'giao hàng',
        'tận nhà',
        'mang đi',
      ],
      EXPLORE: [
        'đi chơi',
        'cuối tuần',
        'trải nghiệm',
        'quán mới',
        'khám phá',
        'du hí',
        'phượt',
        'đi xa',
      ],
    } as Record<string, string[]>,
    emotion: {
      TIRED: ['mệt', 'oải', 'đuối', 'kiệt sức', 'mệt mỏi', 'uể oải', 'hết hơi'],
      REWARD: [
        'tự thưởng',
        'sang chảnh',
        'ăn mừng',
        'lương về',
        'xõa',
        'linh đình',
        'thịnh soạn',
      ],
      STRESSED: [
        'stress',
        'căng thẳng',
        'buồn',
        'thất tình',
        'áp lực',
        'bực mình',
        'stress nặng',
      ],
    } as Record<string, string[]>,
    category: {
      DRINK: [
        'uống',
        'nước ngọt',
        'trà sữa',
        'cà phê',
        'sinh tố',
        'nước ép',
        'trà chanh',
        'cafe',
        'cocktail',
      ],
      FOOD: [
        'ăn',
        'món ăn',
        'cơm',
        'bún',
        'phở',
        'mì',
        'lẩu',
        'bánh',
        'cháo',
        'hải sản',
      ],
    } as Record<string, string[]>,
  },
  NOISE_WORDS: [
    'gần',
    'ở',
    'tại',
    'dưới',
    'tầm',
    'khoảng',
    'rẻ',
    'ngon',
    'nóng',
    'cay',
    '1 mình',
    'gia đình',
    'bạn bè',
    'nào',
    'gì',
    'đây',
    'cho',
    'tôi',
    'em',
  ],
};
