/**
 * Mục đích: Định nghĩa các hằng số cấu hình quy tắc phân tích ý định và trích xuất thực thể của AI.
 * File quan hệ: Được sử dụng bởi IntentDetectorService và BusinessRuleEngineService.
 */

export const AI_RULES = {
  SYNONYMS: {
    companion: {
      SINGLE: [
        '1 mình',
        'cô đơn',
        'một mình',
        'lẻ loi',
        'tự kỷ',
        'đơn thân',
        'mình tôi',
      ],
      FAMILY: [
        'gia đình',
        'bố mẹ',
        'vợ con',
        'nhà mình',
        'phụ huynh',
        'con cái',
        'nhà tôi',
      ],
      DATE: [
        'người yêu',
        'hẹn hò',
        'ghẹ',
        'bồ',
        'crush',
        'bạn gái',
        'bạn trai',
        'gấu',
      ],
      FRIENDS: [
        'bạn bè',
        'đồng nghiệp',
        'tụ tập',
        'nhóm',
        'team',
        'công ty',
        'hội nhóm',
        'cơ quan',
      ],
    },
    mobility: {
      LAZY: [
        'lười',
        'ngại đi',
        'ngại đi xa',
        'ship',
        'mang về',
        'giao hàng',
        'tận nhà',
        'mang đi',
      ],
      EXPLORE: [
        'đi chơi',
        'cuối tuần',
        'trải nghiệm',
        'quán mới',
        'khám phá',
        'du hí',
        'phượt',
        'đi xa',
      ],
    },
    emotion: {
      TIRED: ['mệt', 'oải', 'đuối', 'kiệt sức', 'mệt mỏi', 'uể oải', 'hết hơi'],
      REWARD: [
        'tự thưởng',
        'sang chảnh',
        'ăn mừng',
        'lương về',
        'xõa',
        'linh đình',
        'thịnh soạn',
      ],
      STRESSED: [
        'stress',
        'căng thẳng',
        'buồn',
        'thất tình',
        'áp lực',
        'bực mình',
        'stress nặng',
      ],
    },
    category: {
      DRINK: [
        'uống',
        'nước ngọt',
        'trà sữa',
        'cà phê',
        'sinh tố',
        'nước ép',
        'trà chanh',
        'cafe',
        'cocktail',
      ],
      FOOD: [
        'ăn',
        'món ăn',
        'cơm',
        'bún',
        'phở',
        'mì',
        'lẩu',
        'bánh',
        'cháo',
        'hải sản',
      ],
    },
  },
  NOISE_WORDS: [
    'gần',
    'ở',
    'tại',
    'dưới',
    'tầm',
    'khoảng',
    'rẻ',
    'ngon',
    'nóng',
    'cay',
    '1 mình',
    'gia đình',
    'bạn bè',
    'nào',
    'gì',
    'đây',
    'cho',
    'tôi',
    'em',
  ],
  TIME_BOOSTS: {
    MORNING: {
      hours: [6, 7, 8, 9],
      keywords: ['bánh mì', 'phở', 'bún', 'cháo', 'xôi', 'cà phê', 'cafe'],
      boost: 0.25,
    },
    LUNCH: {
      hours: [11, 12, 13],
      keywords: ['cơm', 'bún chả', 'bún đậu', 'phở', 'mì', 'com'],
      boost: 0.25,
    },
    DINNER: {
      hours: [18, 19, 20, 21],
      keywords: ['lẩu', 'nướng', 'cơm gia đình', 'hải sản', 'ốc', 'nhậu'],
      boost: 0.25,
    },
    LATE_NIGHT: {
      hours: [22, 23, 0, 1, 2, 3, 4],
      keywords: ['lẩu', 'nướng', 'mì đêm', 'cháo đêm', 'ốc', 'ăn đêm'],
      boost: 0.25,
    },
  },
  WEATHER_BOOSTS: {
    HOT_TEMP_THRESHOLD: 33,
    COLD_TEMP_THRESHOLD: 20,
    HOT: {
      boostKeywords: [
        'kem',
        'nước ép',
        'sinh tố',
        'trà sữa',
        'chè',
        'đá',
        'mát',
      ],
      penalizeKeywords: ['lẩu', 'cay', 'nóng', 'súp', 'cháo'],
      value: 0.25,
    },
    COLD_OR_RAIN: {
      boostKeywords: [
        'lẩu',
        'nướng',
        'cay',
        'nóng',
        'súp',
        'cháo',
        'bún bò',
        'mì cay',
      ],
      value: 0.25,
    },
  },
  WELLNESS_ADVICE: {
    STRESSED: {
      advice:
        'Khi bị stress, các món ăn ấm nóng, nhẹ bụng và bổ dưỡng sẽ giúp cơ thể xoa dịu hệ thần kinh rất tốt đó nè. Bạn có muốn thử dùng một bát cháo nóng hoặc thưởng thức một tách trà hoa cúc thư giãn không?',
      targetCuisines: ['cháo', 'trà', 'súp', 'canh'],
    },
    TIRED: {
      advice:
        'Cơ thể đang mệt mỏi rất cần bổ sung năng lượng nhanh và các chất điện giải tự nhiên. Một bát bún bò nóng hổi hoặc một cốc nước dừa mát lành sẽ giúp bạn mau hồi sức nhé.',
      targetCuisines: ['bún bò', 'nước dừa', 'nước ép', 'cháo', 'súp'],
    },
    DIET: {
      advice:
        'Để hỗ trợ quá trình giảm cân và giữ dáng, bạn nên chọn các món ăn giàu chất xơ, ít calo và giàu đạm lành mạnh. Mình gợi ý các món salad tươi mát hoặc ức gà phi lê áp chảo giàu dinh dưỡng nhé!',
      targetCuisines: ['salad', 'ức gà', 'chay', 'gỏi', 'healthy'],
    },
    COLD_WEATHER: {
      advice:
        'Trời lạnh lạnh thế này thì các món nước nóng hổi hoặc lẩu riêu cua, súp cay sẽ giúp giữ ấm cơ thể cực tốt. Mời bạn tham khảo một vài món ngon nghi ngút khói dưới đây nha.',
      targetCuisines: ['lẩu', 'súp', 'cay', 'bún bò', 'phở'],
    },
  },
  WELLNESS_KEYWORDS: {
    STRESSED: ['stress', 'căng thẳng', 'áp lực'],
    TIRED: ['mệt', 'oải', 'đuối', 'kiệt sức'],
    DIET: ['giảm cân', 'diet', 'healthy', 'giảm mỡ', 'ít calo'],
    COLD_WEATHER: ['lạnh', 'rét', 'gió mùa', 'đông về'],
  },
  CUISINE_TRIGGERS: [
    'thèm',
    'muốn ăn',
    'ăn',
    'uống',
    'tìm món',
    'tìm quán',
    'thích',
    'thử món',
    'món',
  ],
};
