export const LIMITS = {
  DEFAULT_RECENT_VIEWS: 5,
  FOOD_LIST_PAGINATION: 100,
  DEFAULT_NEARBY_RADIUS: 10,
  DEFAULT_NEARBY_PAGINATION: 12,
  AI_SUGGESTION_COUNT_SMALL: 3,
  AI_SUGGESTION_COUNT_MEDIUM: 6,
  AI_CHAT_HISTORY_PAGINATION: 10,
  RESTAURANT_INITIAL_FOODS: 5,
};
