// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const isInventory = process.argv.some(arg => arg.includes("inventory.prisma"));

export default defineConfig({
  schema: isInventory ? "prisma/inventory.prisma" : "prisma/schema.prisma",
  migrations: {
    path: isInventory ? "prisma/inventory-migrations" : "prisma/migrations",
    seed: isInventory ? undefined : "node prisma/seed.js",
  },
  datasource: {
    url: isInventory ? process.env["INVENTORY_DATABASE_URL"] : process.env["DATABASE_URL"],
  },
});
