import { LABELS } from './labels';

export const EXCEL_SAMPLE_DATA = [
  {
    [LABELS.RESTAURANT.UPLOAD_EXCEL.COLS.NAME]: '',
    [LABELS.RESTAURANT.UPLOAD_EXCEL.COLS.PRICE]: '',
    [LABELS.RESTAURANT.UPLOAD_EXCEL.COLS.DESC]: '',
    [LABELS.RESTAURANT.UPLOAD_EXCEL.COLS.IMAGE]: '',
    [LABELS.RESTAURANT.UPLOAD_EXCEL.COLS.TAGS]: ''
  }
];

export const EXCEL_INGREDIENT_SAMPLE_DATA = [
  {
    [LABELS.RESTAURANT.UPLOAD_INGREDIENT_EXCEL.COLS.NAME]: '',
    [LABELS.RESTAURANT.UPLOAD_INGREDIENT_EXCEL.COLS.SKU]: '',
    [LABELS.RESTAURANT.UPLOAD_INGREDIENT_EXCEL.COLS.QTY]: '',
    [LABELS.RESTAURANT.UPLOAD_INGREDIENT_EXCEL.COLS.UNIT]: '',
    [LABELS.RESTAURANT.UPLOAD_INGREDIENT_EXCEL.COLS.MIN_STOCK]: ''
  }
];
