import { LABELS } from './labels';

export const EXCEL_SAMPLE_DATA = [
  {
    [LABELS.RESTAURANT.UPLOAD_EXCEL.COLS.NAME]: '',
    [LABELS.RESTAURANT.UPLOAD_EXCEL.COLS.PRICE]: '',
    [LABELS.RESTAURANT.UPLOAD_EXCEL.COLS.DESC]: '',
    [LABELS.RESTAURANT.UPLOAD_EXCEL.COLS.IMAGE]: '',
    [LABELS.RESTAURANT.UPLOAD_EXCEL.COLS.TAGS]: ''
  }
];
