// Mục đích: Khai báo đối tượng hằng số LABELS chứa toàn bộ văn bản hiển thị (UI text) tiếng Việt của ứng dụng.
// Các file khác hay file này có ý nghĩa như nào: Đóng vai trò là nguồn văn bản hiển thị tập trung (Localization/i18n), tránh việc hardcode trực tiếp vào UI.
// Các chức năng đặc biệt: Tổ chức văn bản theo từng phân hệ (Auth, Restaurant, Admin, Customer, Settings, Nav, Footer, Hero, Home, Form, Explore, Food, AI Chat).
// Kiến thức, Design Pattern, nguyên tắc (SOLID, OOP...) đang được áp dụng trong file: Constant pattern, Namespace grouping, Localization/i18n.
// Các biến, hàm đặc biệt trong file: LABELS.

import { LABELS_EN } from './labels.en';

const LABELS_VI = {
  COMMON: {
    SAVE: 'Lưu thay đổi',
    CANCEL: 'Hủy',
    DELETE: 'Xóa',
    EDIT: 'Chỉnh sửa',
    APPROVE: 'Phê duyệt',
    REJECT: 'Từ chối',
    LOGOUT: 'Đăng xuất',
    BACK_HOME: 'Quay lại trang chủ',
    LOADING: 'Đang tải...',
    SUCCESS: 'Thành công',
    ERROR: 'Lỗi',
    NEXT: 'Tiếp theo',
    BACK: 'Quay lại',
    SEARCH: 'Tìm kiếm...',
    OTHER: 'Khác...',
    APP_TITLE: 'FOOD AI - Món ngon mỗi ngày',
    PROCESSING: 'Đang xử lý...',
    DEVELOPING: 'Tính năng đang phát triển',
    DEVELOPING_DESC: 'Chúng tôi đang phát triển tính năng này. Quay lại sau nhé! ✨',
    SEE_MORE: 'Xem thêm',
    UNNAMED: 'Chưa đặt tên',
    SCROLL_LEFT: 'Cuộn sang trái',
    SCROLL_RIGHT: 'Cuộn sang phải',
    TOGGLE_THEME: 'Chuyển đổi giao diện sáng/tối',
    CLOSE: 'Đóng',
    AI_BUSY: 'Rất tiếc, AI đang bận. Bạn thử lại sau nhé!',
    ACTION: 'Thao tác',

    UNKNOWN: 'Chưa xác định',
    BRAND_NAME: 'Food AI',
    BRAND_LOGO_ALT: 'Food AI Logo',
    AI_ASSISTANT_NAME: 'Food AI Assistant',
    USER: 'Người dùng',
    STORE: 'Cửa hàng',
    PAGINATION: {
      PREVIOUS: 'Trang trước',
      NEXT: 'Trang sau',
      JUMP_TO_PAGE: 'Nhảy nhanh đến trang',
    },
  },
  AUTH: {
    LOGIN: 'Đăng nhập',
    REGISTER: 'Đăng ký',
    ADMIN: 'Quản trị viên',
    RESTAURANT_ROLE: 'Chủ nhà hàng',
    PROFILE: 'Hồ sơ cá nhân',
    LOGIN_TITLE: 'Đăng nhập',
    LOGIN_SUBTITLE: 'Chào mừng bạn quay trở lại với FoodAI',
    PASSWORD: 'Mật khẩu',
    OR_LOGIN_WITH: 'Hoặc đăng nhập bằng',
    SOCIAL_GOOGLE: 'Google',
    SOCIAL_FACEBOOK: 'Facebook',
    FORGOT_PASSWORD: 'Quên mật khẩu?',
    NO_ACCOUNT: 'Chưa có tài khoản?',
    REGISTER_NOW: 'Đăng ký ngay',
    REGISTER_TITLE: 'Tạo tài khoản',
    REGISTER_SUBTITLE: 'Bắt đầu hành trình khám phá ẩm thực thông minh',
    WHO_ARE_YOU: 'Bạn là ai?',
    CUSTOMER: 'Khách hàng',
    RESTAURANT: 'Nhà hàng',
    CONFIRM_PASSWORD: 'Xác nhận mật khẩu',
    LEGAL_DOCS: 'Giấy tờ pháp lý / Thông tin xác thực',
    LEGAL_DOCS_PLACEHOLDER: 'Số giấy phép kinh doanh hoặc link ảnh giấy tờ...',
    AGREE_TERMS: 'Tôi đồng ý với các điều khoản bảo mật và chính sách sử dụng.',
    ALREADY_HAVE_ACCOUNT: 'Đã có tài khoản?',
    VERIFY_ACCOUNT: 'Xác minh tài khoản',
    LOGIN_GO: 'Đi tới Đăng nhập',
    REGISTER_SUCCESS_PENDING: 'Đăng ký thành công! Đang chờ Admin phê duyệt.',
    REGISTER_SUCCESS_VERIFY: 'Đăng ký thành công! Vui lòng xác minh tài khoản.',
    LOGIN_REQUIRED: 'Vui lòng đăng nhập để thực hiện chức năng này!',
  },
  RESTAURANT: {
    DASHBOARD_TITLE: 'Chào mừng quay trở lại!',
    MENU_MANAGEMENT: 'Quản lý thực đơn',
    AI_HISTORY: 'Lịch sử đề xuất AI',
    SUBTITLE: 'Cửa hàng của bạn đang hoạt động rất tốt ✨',
    MERCHANT_HUB: 'Merchant Hub',
    STATUS: 'Trạng thái',
    ADD_FOOD: 'Đăng món mới',
    RECENT_ACTIVITY: 'Hoạt động gần đây',
    DELETE_BRANCH: 'Xóa cơ sở',
    BRANCH_NUMBER: (num: number) => `📍 Cơ sở ${num}`,
    VIEW_INSIGHT: 'Xem Insight chi tiết',
    VIEW_AS_GUEST: 'Xem với tư cách khách',
    NO_FOOD: 'Chưa có món ăn nào.',
    SAVE_SUCCESS_EDIT: 'Đã lưu! Chờ Admin duyệt.',
    SAVE_SUCCESS_ADD: 'Đã đăng! Chờ Admin duyệt.',
    AI_SUGGESTION_TITLE: 'Gợi ý AI cho quán',
    AI_SUGGESTION_DESC: 'Món "Phở cuốn" đang là xu hướng. Bạn có muốn thêm vào thực đơn?',
    STATUS_OPEN: 'Đang mở cửa',
    STATUS_CLOSED: 'Tạm nghỉ',
    STATUS_TOOLTIP: 'Khi chủ động đóng cửa (Tạm nghỉ), toàn bộ món ăn của bạn sẽ bị ẩn khỏi kết quả tìm kiếm và danh sách đề xuất của hệ thống.',
    SETTINGS_TITLE: 'Cài đặt Cửa hàng',
    OPERATING_HOURS: 'Giờ hoạt động định kỳ',
    CONTACT_PHONE: 'Số điện thoại liên hệ',
    SAVE: 'Lưu',
    STATUS_OPEN_SUCCESS: 'Cửa hàng đã mở cửa đón khách.',
    STATUS_CLOSE_SUCCESS: 'Cửa hàng đã tạm đóng cửa đột xuất.',
    STATUS_UPDATE_ERROR: 'Không thể cập nhật trạng thái cửa hàng.',
    DELETE_FOOD_CONFIRM: 'Bạn có chắc chắn muốn xóa món ăn này khỏi thực đơn không? Món ăn sẽ bị ẩn và không hiển thị đối với thực khách nữa.',
    DELETE_FOOD_CONFIRM_TITLE: 'Xác nhận xóa món ăn',
    HOURS_UPDATE_SUCCESS: 'Cập nhật giờ mở cửa thành công.',
    HOURS_UPDATE_ERROR: 'Không thể cập nhật giờ mở cửa.',
    CLOSED_WARNING_TITLE: 'Cửa hàng hiện đang tạm đóng cửa',
    CLOSED_BY_MERCHANT: 'Nhà hàng đã chủ động đóng cửa tạm thời.',
    CLOSED_OUTSIDE_HOURS: (hours: string) => `Ngoài khung giờ hoạt động của cửa hàng (${hours}).`,
    NOT_SET: 'chưa thiết lập',
    OPERATING_HOURS_LABEL: 'Giờ hoạt động',
    HOURS_PLACEHOLDER: 'Ví dụ: 08:00 - 22:00',
    HOURS_FORMAT_ERROR: 'Giờ hoạt động không đúng định dạng (Ví dụ đúng: 08:00 - 22:00).',
    EDIT_STORE: 'cửa hàng',
    TABS: {
      OVERVIEW: 'Tổng quan',
      CATEGORIES: 'Danh mục',
      MENU: 'Thực đơn của tôi',
      HISTORY: 'Lịch sử đề xuất',
    },
    EDIT_MODAL: {
      LIVE_PREVIEW: 'Live Card Preview',
      VERIFIED: 'Verified',
      BIO_PLACEHOLDER: 'Giới thiệu ngắn về nhà hàng...',
      NOT_OPENED: 'Chưa mở cửa',
      TIP: 'Thay đổi ảnh Logo và Ảnh bìa của quán sẽ cập nhật lập tức trên lưới Khám phá và trang hồ sơ công khai của nhà hàng.',
      SUBTITLE: 'Tùy chỉnh thương hiệu và thông tin liên hệ của quán ăn',
      TAB_INFO: 'Thông tin cơ bản',
      TAB_IMAGES: 'Hình ảnh thương hiệu',
      TAB_CONTACT: 'Liên hệ & Vận hành',
      NAME_LABEL: 'Tên nhà hàng',
      NAME_PLACEHOLDER: 'Ví dụ: FOOD AI - Chi nhánh Đống Đa',
      NAME_REQUIRED: 'Vui lòng nhập tên nhà hàng',
      BIO_LABEL: 'Giới thiệu ngắn (Bio)',
      BIO_INPUT_PLACEHOLDER: 'Món ăn sạch, thuần khiết tự nhiên...',
      DESC_LABEL: 'Mô tả chi tiết',
      DESC_PLACEHOLDER: 'Mô tả chi tiết về thực đơn, phong cách quán ăn của bạn...',
      LOGO_LABEL: 'URL Logo nhà hàng',
      LOGO_PLACEHOLDER: 'https://example.com/logo.png',
      SYNC_AVATAR: 'Đồng bộ ảnh Logo này làm ảnh đại diện cá nhân của bạn',
      COVER_LABEL: 'URL Ảnh bìa (Cover Image)',
      COVER_PLACEHOLDER: 'https://example.com/cover.png',
      SYNC_COVER: 'Đồng bộ ảnh bìa này làm ảnh bìa cá nhân của bạn',
      CITY_LABEL: 'Tỉnh / Thành phố',
      DISTRICT_LABEL: 'Quận / Huyện',
      ADDRESS_LABEL: 'Địa chỉ thực tế chi tiết',
      ADDRESS_PLACEHOLDER: 'Ví dụ: 123 Đường Láng, Láng Thượng',
      HOURS_LABEL: 'Giờ mở cửa (HH:MM - HH:MM)',
      PHONE_LABEL: 'Số điện thoại liên hệ',
      PHONE_PLACEHOLDER: '0987654321',
      EMAIL_LABEL: 'Email liên hệ',
      EMAIL_PLACEHOLDER: 'contact@quanphobac.com',
      MAPS_LABEL: 'Bản đồ chỉ đường (Google Maps Link)',
      MAPS_PLACEHOLDER: 'https://maps.app.goo.gl/...',
      CANCEL: 'Hủy bỏ',
      SUBMIT: 'Lưu cài đặt',
      SAVING: 'Đang lưu...',
      SAVE_ERROR: 'Lỗi khi cập nhật thông tin cửa hàng',
      CONFIRM_TITLE: 'Xác nhận lưu cài đặt',
      CONFIRM_DESC: 'Bạn có chắc chắn muốn lưu các thay đổi này cho cửa hàng không?',
      CLOSE_SETTINGS: 'Đóng cài đặt cửa hàng',
    },
    CARD_LABELS: {
      DEFAULT_BIO: 'Hân hạnh được phục vụ quý khách thực đơn món ngon cao cấp.',
      FOLLOWERS_SUFFIX: 'người theo dõi',
      FOODS_SUFFIX: 'món ăn',
      DEFAULT_LOCATION: 'Việt Nam',
      DEFAULT_CATEGORY: 'Quán ăn',
    },
    TABLE: {
      FOOD: 'Món ăn',
      STATUS: 'Trạng thái',
      ACTION: 'Thao tác',
      FEATURE: 'Nổi bật',
      RECOMMEND: 'Đề xuất',
    },
    MODAL: {
      ADD_TITLE: 'Đăng món mới',
      EDIT_TITLE: 'Chỉnh sửa món ăn',
      SUBMIT_ADD: 'Đăng món ngay',
      SUBMIT_EDIT: 'Lưu thay đổi',
      BRANCH_LABEL: 'Cơ sở kinh doanh',
      BRANCH_PLACEHOLDER: '-- Chọn cơ sở --',
      CATEGORY_LABEL: 'Danh mục món ăn (Tùy chọn)',
      CATEGORY_PLACEHOLDER: '-- Không thuộc danh mục nào --',
      AUTO_FILL_BRANCH: '(Tự động điền theo cơ sở)',
      AUTO_FILL_LAT_LNG: '(Tự động điền)',
    },
    PUBLIC_PROFILE: {
      NOT_FOUND: 'Không tìm thấy quán ăn',
      NOT_FOUND_DESC: 'Đường dẫn không hợp lý hoặc cơ sở kinh doanh đã ngừng hoạt động.',
      MENU_TAB: 'Thực đơn món ăn',
      INFO_TAB: 'Thông tin quán ăn',
      EMPTY_MENU: 'Thực đơn trống',
      EMPTY_MENU_DESC: 'Quán ăn hiện chưa đăng tải món ăn nào đã được phê duyệt.',
      DETAIL_INFO: 'Thông tin Chi tiết',
      NO_HOURS: 'Chưa thiết lập giờ hoạt động',
      NO_PHONE: 'Chưa thiết lập số điện thoại',
      CONTACT_EMAIL: 'Email liên hệ',
      MAP_TITLE: 'Bản đồ chỉ đường',
      MAP_OPEN: 'Mở vị trí trên Google Maps',
      BIO_TITLE: 'Giới thiệu quán',
      BIO_EMPTY: 'Quán ăn chưa cập nhật thông tin giới thiệu chi tiết.',
      FOLLOWERS_TITLE: 'Người đang theo dõi',
      FOLLOWERS_EMPTY: 'Chưa có người theo dõi nào.',
      FOLLOWING_TITLE: 'Đang theo dõi quán',
      FOLLOWING_EMPTY: 'Chưa theo dõi quán ăn nào.',
      LOGIN_REQUIRED: 'Vui lòng đăng nhập để thực hiện tính năng này',
      FOLLOWERS_PRIVATE: 'Danh sách người theo dõi đã được ẩn bởi chủ quán',
      FOLLOWING_PRIVATE: 'Danh sách đang theo dõi đã được ẩn bởi chủ quán',
      LOAD_ERROR: 'Không thể tải danh sách',
      VIEWING_AS_GUEST: 'Bạn đang xem cửa hàng của mình dưới tư cách khách.',
      PRIVACY_TITLE: '🔒 Cài đặt quyền riêng tư',
      PRIVACY_LABEL: 'Hiển thị danh sách theo dõi',
      PRIVACY_DESC: 'Bật/tắt chế độ hiển thị danh sách người theo dõi và đang theo dõi trên trang của bạn.',
      PRIVACY_SUCCESS: 'Cập nhật quyền riêng tư thành công!',
      PRIVACY_ERROR: 'Lỗi cập nhật cài đặt.',
      MENU_CATEGORIES: 'Danh mục món ăn',
      COLLAPSE_CATEGORY: 'Thu gọn danh mục',
      EXPAND_CATEGORY: 'Mở rộng danh mục',
      ALL_FOODS: 'Tất cả món ăn',
      LOADING_FOODS: 'Đang tải món ăn...',
      LOADING_MORE: 'Đang tải...',
      LOAD_MORE: 'Xem thêm món',
      GO_TO_ADMIN: '[Vào trang quản trị]',
      MANAGE_RESTAURANT: 'Quản lý quán ăn',
      CATEGORY_MANAGER: {
        TITLE: 'Quản lý Nhóm & Danh mục',
        LOADING: 'Đang tải danh mục...',
        HELP_TOOLTIP: 'Nhóm (Group) là thư mục gốc ngoài cùng. Sau khi tạo Nhóm, bạn có thể ấn nút dấu [+] trên nhóm đó để tạo ra các Phân loại con (Category) bên trong.',
        ADD_GROUP: 'Thêm Nhóm Mới',
        GUIDE_TITLE: '💡 Hướng dẫn phân loại món ăn:',
        GUIDE_GROUP: 'Nhóm danh mục (Ví dụ: Đồ uống): Bạn có thể gán món ăn trực tiếp vào Nhóm này.',
        GUIDE_CATEGORY: 'Phân loại con (Ví dụ: Trà sữa, Nước ép): Nếu muốn chi tiết hơn, hãy ấn nút [+] trên Nhóm để tạo Phân loại con, sau đó gán món vào Phân loại con tương ứng.',
        PRIORITY_PREFIX: 'Ưu tiên hiển thị thứ: #',
        PRIORITY_SHORT: 'Ưu tiên số: #',
        ADD_ROOT_CATEGORY: 'Thêm danh mục gốc',
        ADD_SUB_CATEGORY: 'Thêm phân loại con',
        EMPTY_GROUP_NOTE: '📌 Bạn có thể gán món trực tiếp vào nhóm này, hoặc ấn nút [+] để tạo thêm phân loại con.',
        EMPTY_GROUPS: 'Chưa có nhóm danh mục nào',
        EDIT_GROUP: 'Sửa Nhóm',
        GROUP_NAME: 'Tên nhóm',
        DISPLAY_ORDER: 'Thứ tự hiển thị',
        ORDER_DESC_GROUP: 'Dùng để sắp xếp vị trí hiển thị trên Menu. Số càng nhỏ, nhóm càng được ưu tiên xếp lên trên. Ví dụ: Nhập 0 sẽ xếp đầu tiên, 1 xếp thứ hai.',
        GROUP_PLACEHOLDER: 'VD: Cơm phần, Đồ uống...',
        EDIT_CATEGORY: 'Sửa Phân Loại',
        ADD_CATEGORY: 'Thêm Phân Loại',
        CATEGORY_NAME: 'Tên phân loại',
        CATEGORY_PLACEHOLDER: 'VD: Cơm sườn, Nước ép...',
        ORDER_DESC_CATEGORY: 'Dùng để sắp xếp vị trí hiển thị trên Menu. Số càng nhỏ, phân loại này càng được ưu tiên xếp lên trước. Ví dụ: 0 là xếp đầu tiên.',
        CONFIRM_DELETE_TITLE: 'Xác nhận xóa',
        CONFIRM_DELETE_MESSAGE: (type: string) => `Bạn có chắc chắn muốn xóa ${type} này? Toàn bộ các danh mục con (nếu có) cũng sẽ bị xóa theo!`
      }
    },
    UPLOAD_EXCEL: {
      MAIN_GROUP: '📁 Nhóm chính',
      COLS: {
        NAME: 'Tên món',
        PRICE: 'Giá',
        DESC: 'Mô tả',
        IMAGE: 'Ảnh',
        TAGS: 'Tags'
      },
      FILE_NAME: 'mau-nhap-mon-an.xlsx',
      SHEET_NAME: 'Danh sách món ăn',
      DOWNLOAD_SUCCESS: 'Đã tải xuống file mẫu!',
      READ_SUCCESS: (count: number) => `Đọc thành công ${count} món từ file!`,
      READ_ERROR: 'Lỗi khi đọc file Excel. Vui lòng kiểm tra định dạng.',
      INVALID_DATA: 'Không tìm thấy dữ liệu hợp lệ. Kiểm tra lại tên cột và dữ liệu.',
      BRANCH_REQUIRED: 'Vui lòng chọn cơ sở áp dụng',
      EMPTY_DATA: 'Dữ liệu trống hoặc không hợp lệ',
      UPLOAD_SUCCESS: (count: number) => `Đã thêm thành công ${count} món ăn!`,
      UPLOAD_ERROR: 'Có lỗi xảy ra khi tải dữ liệu lên hệ thống.',
      TITLE: 'Upload Excel',
      GUIDE_TITLE: 'Hướng dẫn Upload Excel:',
      DOWNLOAD_BTN: 'Tải file mẫu',
      STEP_1: 'Bước 1: Chọn cơ sở',
      STEP_2: 'Bước 2: Chọn danh mục',
      STEP_3: 'Bước 3: Chọn file Excel',
      SELECT_BRANCH: '-- Chọn cơ sở --',
      SELECT_CATEGORY: '-- Chưa phân loại (bỏ qua) --',
      NO_CATEGORY_WARN: '⚠ Cơ sở này chưa có danh mục. Vào tab "Danh mục" để tạo trước.',
      LOADING_CATEGORY: 'Đang tải danh mục...',
      PREVIEW_TITLE: (count: number) => `Xem trước dữ liệu (${count} món)`,
      SAVING: 'Đang xử lý...',
      SAVE_BTN: (count: number) => `Lưu ${count > 0 ? count + ' món' : ''} vào hệ thống`,
      OPTIONAL: '(Tuỳ chọn)',
      GUIDES: {
        COLS_INFO: 'File Excel phải có đúng các cột:',
        REQUIRED_INFO: (col1: string, col2: string) => `${col1} và ${col2} là 2 cột bắt buộc.`,
        TAGS_INFO: 'nhập nhiều giá trị cách nhau bởi dấu phẩy (vd: Ăn vặt, Đồ uống).',
        NO_FILE: 'Bạn chưa có file? Tải file mẫu về điền vào rồi upload lại.',
      }
    }
  },
  ADMIN: {
    PANEL_TITLE: 'Admin Panel',
    APPROVE_MERCHANTS: 'Duyệt Thương gia',
    MANAGE_MERCHANTS: 'Quản lý Thương gia',
    MANAGE_CUSTOMERS: 'Quản lý Thực khách',
    MANAGE_MENU: 'Quản lý Thực đơn',
    MANAGE_LEVEL_BADGES: 'Quản lý Cấp độ & Danh hiệu',
    SEND_NOTIFICATION: 'Gửi thông báo',
    BADGES_MANAGER: {
      TITLE: 'Cấu hình Cấp độ & Danh hiệu',
      DESC: 'Quản lý các cột điểm và danh hiệu tự động cho khách và thương gia.',
      ROLE: 'Vai trò',
      BADGE_TITLE: 'Tên danh hiệu',
      MIN_POINTS: 'Điểm tối thiểu',
      ADD_BADGE: 'Thêm danh hiệu mới',
      DELETE_CONFIRM: 'Bạn có chắc chắn muốn xóa danh hiệu này?',
      SAVE_SUCCESS: 'Lưu cấu hình danh hiệu thành công!',
      POINTS_REQUIRED: 'Vui lòng nhập điểm tối thiểu hợp lệ.',
      TITLE_REQUIRED: 'Vui lòng nhập tên danh hiệu.',
      TITLE_PLACEHOLDER: 'Ví dụ: Chuyên Gia Ẩm Thực',
      POINTS_PLACEHOLDER: 'Ví dụ: 1000',
    },
    NOTIFICATION_TAB: {
      TITLE: 'Gửi thông báo hệ thống',
      DESC: 'Tạo và gửi thông báo trực tiếp đến chuông thông báo của toàn bộ người dùng hoặc một cá nhân cụ thể.',
      SECTION_TITLE: 'Chi tiết nội dung thông báo',
      RECIPIENT_LABEL: 'Đối tượng nhận thông báo',
      RECIPIENT_ALL: (count: number) => `Tất cả thành viên (${count})`,
      RECIPIENT_SPECIFIC: 'Thành viên cụ thể',
      SELECT_USER_LABEL: 'Chọn thành viên',
      SELECT_USER_PLACEHOLDER: '-- Chọn thành viên nhận --',
      USER_OPTION: (name: string, role: string, email: string) => `${name} (${role === 'CUSTOMER' ? 'Khách hàng' : 'Nhà hàng'} - ${email})`,
      NOTIF_TYPE_LABEL: 'Loại thông báo',
      NOTIF_TYPE_OPTIONS: {
        SYSTEM: 'Hệ thống (SYSTEM)',
        WARNING: 'Cảnh báo (WARNING)',
        PROMOTION: 'Khuyến mại (PROMOTION)',
      },
      TITLE_LABEL: 'Tiêu đề thông báo',
      TITLE_PLACEHOLDER: 'Nhập tiêu đề ngắn gọn...',
      CONTENT_LABEL: 'Nội dung chi tiết',
      CONTENT_PLACEHOLDER: 'Nhập nội dung đầy đủ của thông báo gửi đến người dùng...',
      SEND_BTN: 'Gửi thông báo ngay',
      SENDING: 'Đang gửi...',
      PREVIEW_TITLE: 'Xem trước thông báo',
      PREVIEW_TITLE_DEFAULT: '(Tiêu đề mẫu)',
      PREVIEW_CONTENT_DEFAULT: 'Nội dung thông báo chi tiết của bạn sẽ được hiển thị tại đây khi soạn thảo...',
      PREVIEW_TIME: 'Vừa xong',
      TIP_TITLE: 'Mẹo nhỏ',
      TIP_DESC: 'Thông báo gửi đi sẽ hiển thị một chấm đỏ nhấp nháy trên thanh chuông của người nhận và lưu lại vĩnh viễn trên thiết bị của họ.',
      TOAST: {
        TITLE_REQUIRED: 'Vui lòng nhập tiêu đề thông báo!',
        CONTENT_REQUIRED: 'Vui lòng nhập nội dung thông báo!',
        USER_REQUIRED: 'Vui lòng chọn thành viên nhận thông báo!',
        NO_USERS: 'Không tìm thấy thành viên nào trên hệ thống để gửi thông báo.',
        SEND_ALL_SUCCESS: (count: number) => `Đã gửi thông báo hệ thống thành công đến ${count} thành viên!`,
        USER_NOT_FOUND: 'Thành viên được chọn không tồn tại.',
        SEND_SPECIFIC_SUCCESS: (name: string) => `Đã gửi thông báo thành công đến thành viên: ${name}!`,
        SEND_ERROR: 'Đã xảy ra lỗi khi gửi thông báo.',
      }
    },
    IMPORT_EXCEL: 'Import Excel',
    SYSTEM_FOOD: 'Món ăn hệ thống',
    MERCHANT_FOOD: 'Món ăn đối tác',
    BATCH_SAVE: 'Lưu',
    BATCH_CANCEL: 'Hủy',
    DESELECT_ALL: 'Bỏ chọn tất cả',
    BATCH_SAVE_ALL: 'Lưu thay đổi',
    BATCH_CANCEL_ALL: 'Hủy thay đổi',
    UNSAVED_CHANGES: (count: number) => `Bạn có ${count} thay đổi chưa lưu trên các thực đơn đối tác.`,
    EDIT_MODE_LABEL: 'Chỉnh sửa',
    VIEW_MODE_LABEL: 'Xem',
    FILTER_ALL: 'Tất cả',
    FILTER_RECOMMENDED: 'Đề xuất',
    FILTER_UNRECOMMENDED: 'Chưa đề xuất',
    DONE: 'Hoàn tất',
    SAVE_SUCCESS: 'Cập nhật thành công!',
    DELETE_SUCCESS: 'Xóa thành công!',
    FEATURE_TODAY_ON: 'Đã Bật Nổi bật Ngày',
    FEATURE_TODAY_OFF: 'Đã Tắt Nổi bật Ngày',
    FEATURE_WEEKLY_ON: 'Đã Bật Nổi bật Tuần',
    FEATURE_WEEKLY_OFF: 'Đã Tắt Nổi bật Tuần',
    RECOMMEND_ON: 'Đã Bật Gợi ý',
    RECOMMEND_OFF: 'Đã Tắt Gợi ý',
    UPDATE_FAILED: 'Cập nhật thất bại',
    DELETE_WARNING: 'Bạn có chắc chắn muốn xóa tài khoản này?',
    CONFIRM_DELETE_USER: 'Bạn có chắc chắn muốn xóa tài khoản này?',
    MODAL: {
      EDIT_TITLE: 'Chỉnh sửa món ăn',
      FOOD_NAME: 'Tên món',
      PRICE: 'Giá (VNĐ)',
      TAGS: 'Tags',
      IMAGE_URL: 'URL Hình ảnh',
      DESCRIPTION: 'Mô tả',
    },
    TABLE: {
      NAME: 'Tên tài khoản',
      FOOD_NAME: 'Món ăn',
      SOURCE: 'Nguồn',
      EMAIL: 'Email',
      PRICE: 'Giá',
      DATE: 'Ngày đăng ký',
      ACTION: 'Thao tác',
      EMPTY: 'Không tìm thấy dữ liệu nào.',
      FEATURE_TODAY: 'Món ngon hôm nay',
      FEATURE_WEEKLY: 'Món ngon tuần',
      ADMIN_RECOMMEND: 'Admin khuyên dùng',
      SHOWING_FOODS: (count: number) => `Có ${count} món ăn`,
      SHOWING_RESTAURANTS: (count: number) => `Có ${count} quán ăn`,
      SHOWING_REQUESTS: (count: number) => `Có ${count} yêu cầu`,
      SHOWING_ACCOUNTS: (count: number) => `Có ${count} tài khoản`,
      DRAFT: 'Nháp',
    },
    CONFIRM: {
      DELETE_USER: 'Bạn có chắc chắn muốn xóa tài khoản này?',
      DELETE_FOOD: 'Bạn có chắc chắn muốn xóa món ăn này?',
      DELETE_FOOD_DESC: 'Hành động này không thể hoàn tác. Món ăn này sẽ bị xóa khỏi hệ thống vĩnh viễn.',
      DELETE_USER_DESC: 'Hành động này không thể hoàn tác. Người dùng này sẽ bị xóa khỏi hệ thống vĩnh viễn.',
      BATCH_SAVE: 'Xác nhận lưu thay đổi?',
      BATCH_SAVE_DESC: 'Bạn có chắc chắn muốn áp dụng toàn bộ các thay đổi nháp này lên các thực đơn món ăn đối tác không?',
      BATCH_DISCARD: 'Xác nhận hủy thay đổi?',
      BATCH_DISCARD_DESC: 'Tất cả các thay đổi nháp hiện tại trên các thực đơn đối tác sẽ bị xóa sạch. Hành động này không thể hoàn tác. Bạn có chắc chắn muốn hủy không?',
      APPROVE_FOOD: 'Xác nhận phê duyệt món ăn',
      APPROVE_FOOD_DESC: (name: string) => `Bạn có chắc chắn muốn phê duyệt món ăn "${name}"? Món ăn sẽ lập tức hiển thị công khai trên thực đơn của khách hàng.`,
      REJECT_FOOD: 'Xác nhận từ chối món ăn',
      REJECT_FOOD_DESC: (name: string) => `Bạn có chắc chắn muốn từ chối món ăn "${name}"? Món ăn này sẽ bị ẩn và không hiển thị trên thực đơn công khai.`,
      SAVE_FOOD: 'Xác nhận lưu thay đổi món ăn',
      SAVE_FOOD_DESC: 'Bạn có chắc chắn muốn lưu các thay đổi này cho món ăn không?',
    },
    PENDING_APPROVAL: 'CẦN DUYỆT',
    VIEW_MODE: {
      TABLE: 'Bảng',
      ROW: 'Dòng (1x1)',
      TITLE_TABLE: 'Xem bảng',
      TITLE_ROW: 'Xem dòng trực quan',
      TITLE_GRID: 'Xem khối trực quan',
    },
    LEGAL_DOCS: (docs: string) => `Tài liệu pháp lý: ${docs}`,
    REGISTER_DATE: (date: string) => `Đăng ký: ${date}`,
    JOIN_DATE: (date: string) => `Tham gia: ${date}`,
  },
  CUSTOMER: {
    GREETING: (name: string) => `Chào bạn, ${name}! 👋`,
    SUBTITLE: 'Hôm nay bạn muốn AI gợi ý món gì cho bữa trưa không?',
    FAVORITES: 'Yêu thích',
    FAVORITE_UPDATE_ERROR: 'Không thể cập nhật danh sách yêu thích.',
    AI_SUGGESTION: 'Gợi ý AI dành riêng cho bạn',
    AI_SUGGESTION_DESC: (food: string) => `Dựa trên lịch sử ăn uống, chúng tôi đề xuất món ${food} cho hôm nay.`,
    RECENT_FOODS: 'Gần đây bạn đã xem',
    RECENT_FOODS_DESC: (limit: number) => `${limit} món ăn được xem gần đây nhất của bạn`,
    RECENT_FOOD_SUGGEST: (days: number) => `AI gợi ý ${days} ngày trước`,
    PLACEHOLDER_FOOD: 'Phở Bò Gia Truyền',
    OLDER_HISTORY: 'Lịch sử trước đó',
    OLDER_HISTORY_DESC: (limit: number) => `Các món ăn bạn đã xem trong ${limit} lượt gần đây`,
    OLDER_FOODS_TITLE: 'Các món đã xem trước đó',
    PLACEHOLDER_FOOD_2: 'Bún chả Hà Nội',
    INFO: 'Thông tin cá nhân',
    UPDATE_PREFERENCES: 'Cập nhật sở thích AI',
    UPDATE_PREFERENCES2: 'Dữ liệu này nhằm huấn luyện AI để gợi ý món ăn phù hợp với bạn hơn, bạn có thể tùy chỉnh lại trong Dashboard cá nhân',
    SUCCESS_UPDATE: 'Cập nhật thành công!',
    AI_HISTORY: 'Lịch sử đề xuất',
    AI_CONTEXT: 'Sở thích ăn uống (AI Context)',
    ONBOARDING_SUCCESS: 'Tuyệt vời!',
    ONBOARDING_PREPARING: 'Chờ mình một chút nhé ... !',
    STEP: (current: number, total: number) => `Bước ${current} / ${total}`,
    NO_HISTORY: 'Chưa có lịch sử món ăn đã xem',
    AI_LOGIN_REQUIRED: 'Vui lòng đăng nhập để sử dụng tính năng AI tư vấn món ngon bạn nhé! ✨',
    AI_CUSTOMER_ONLY: 'Tính năng AI tư vấn hiện chỉ dành cho khách hàng. Cảm ơn bạn!',
    QUESTION: 'Câu hỏi',
  },
  SETTINGS: {
    TITLE: 'Cài đặt tài khoản',
    SUBTITLE: 'Quản lý thông tin và bảo mật tài khoản của bạn',
    TABS: {
      PROFILE: 'Thông tin',
      SECURITY: 'Bảo mật',
      VERIFICATION: 'Xác minh',
      LANGUAGE: 'Ngôn ngữ',
      DANGER_ZONE: 'Vùng nguy hiểm',
    },
    LANG_DESC: 'Chọn ngôn ngữ hiển thị giao diện và các thông báo từ hệ thống',
    LANGUAGE_CONFIRM_TITLE: 'Xác nhận thay đổi ngôn ngữ',
    LANGUAGE_CONFIRM_DESC: 'Bạn có chắc chắn muốn thay đổi ngôn ngữ hiển thị của hệ thống không? Trang web sẽ được tải lại.',
    SECURITY_CONFIRM_TITLE: 'Xác nhận đổi mật khẩu',
    SECURITY_CONFIRM_DESC: 'Bạn có chắc chắn muốn thay đổi mật khẩu tài khoản không?',
    VERIFY_CONFIRM_TITLE: 'Xác nhận yêu cầu xác minh',
    VERIFY_CONFIRM_DESC: 'Hệ thống sẽ gửi một liên kết xác minh đến email của bạn. Bạn có muốn tiếp tục?',
    PRIVACY_CONFIRM_TITLE: 'Xác nhận thay đổi quyền riêng tư',
    PRIVACY_CONFIRM_DESC: 'Bạn có chắc chắn muốn thay đổi trạng thái hiển thị danh sách theo dõi trên trang của mình không?',
    PROFILE_CONFIRM_TITLE: 'Xác nhận lưu thay đổi',
    PROFILE_CONFIRM_DESC: 'Bạn có chắc chắn muốn lưu các thay đổi này cho hồ sơ cá nhân của mình không?',
    SECURITY: {
      CURRENT_PASSWORD: 'Mật khẩu hiện tại',
      NEW_PASSWORD: 'Mật khẩu mới',
      CONFIRM_PASSWORD: 'Xác nhận mật khẩu mới',
      CHANGE_PASSWORD: 'Đổi mật khẩu',
      CHANGE_SUCCESS: 'Đổi mật khẩu thành công!',
      CHANGE_PASSWORD_ERROR: 'Đổi mật khẩu thất bại. Vui lòng thử lại.',
      MISMATCH: 'Mật khẩu mới không trùng khớp.',
    },
    VERIFICATION: {
      TITLE: 'Xác minh tài khoản email của bạn',
      LABEL: 'Nhập email để xác minh',
      SUCCESS: 'Xác minh email thành công!',
      SEND_EMAIL_ERROR: 'Gửi email xác minh thất bại.',
      VERIFIED: 'Tài khoản đã được xác minh.',
      VERIFY_NOW: 'Xác minh ngay',
    },
    PROFILE: {
      TITLE: 'Hồ sơ của bạn',
      FULL_NAME: 'Họ và tên',
      NOT_UPDATED: 'Chưa cập nhật',
      EDIT_COVER: 'Chỉnh sửa ảnh bìa',
      FOLLOWERS: 'người theo dõi',
      FOLLOWING: 'đang theo dõi',
      DASHBOARD: 'Bảng điều khiển',
      FOLLOW: 'Theo dõi',
      UNFOLLOW: 'Bỏ theo dõi',
      SAVE_SUCCESS: 'Cập nhật thông tin thành công!',
      BIO_EMPTY: 'Người dùng này chưa có tiểu sử.',
      PRIVACY_TITLE: '🔒 Ẩn/hiện thông tin cá nhân',
      PRIVACY_DESC: 'Tùy chỉnh từng mục thông tin cá nhân mà bạn muốn hiển thị hoặc ẩn đi trên bài viết và trang cá nhân.',
      PRIVACY_TOAST_SUCCESS: (label: string, enabled: boolean) => `Đã ${enabled ? 'bật' : 'tắt'} hiển thị: ${label}`,
      FOLLOW_LIST_PRIVATE: 'Danh sách theo dõi đã được ẩn',
      PRIVACY_FIELDS: {
        showLevel: { label: 'Cấp bậc (Level)', desc: 'Hiển thị cấp bậc (Lv.) trên bài viết và trang cá nhân.' },
        showBadge: { label: 'Danh hiệu (Badge)', desc: 'Hiển thị danh hiệu đạt được trên bài viết và trang cá nhân.' },
        showPoints: { label: 'Điểm tích lũy', desc: 'Hiển thị số điểm tích lũy trên trang cá nhân.' },
        showXpBar: { label: 'Thanh tiến trình XP', desc: 'Hiển thị thanh tiến trình XP trên trang cá nhân.' },
        showFollowList: { label: 'Danh sách theo dõi', desc: 'Hiển thị danh sách người theo dõi và đang theo dõi trên trang cá nhân.' },
        showEmail: { label: 'Địa chỉ email', desc: 'Hiển thị email của bạn trên trang giới thiệu cá nhân.' },
        showPhone: { label: 'Số điện thoại', desc: 'Hiển thị số điện thoại trên trang thông tin cá nhân.' },
        showAddress: { label: 'Địa chỉ / Nơi sống', desc: 'Hiển thị địa chỉ hoặc nơi sống trên trang giới thiệu cá nhân.' },
      },
      TABS: {
        POSTS: 'Bài viết',
        ABOUT: 'Giới thiệu',
        FRIENDS: 'Bạn bè',
        PHOTOS: 'Ảnh',
      },
      INTRO: {
        TITLE: 'Giới thiệu',
        WORK: (work: string) => `Làm việc tại ${work}`,
        LIVES: (city: string) => `Sống tại ${city}`,
        JOINED: (year: number) => `Tham gia từ ${year}`,
        EDIT_DETAILS: 'Chỉnh sửa chi tiết',
      },
      POSTS: {
        EMPTY_TITLE: 'Chưa có bài viết nào',
        EMPTY_DESC: 'Bắt đầu chia sẻ những trải nghiệm ẩm thực của bạn ngay hôm nay!',
        THINKING: (name: string) => `${name} ơi, bạn đang nghĩ gì thế?`,
      },
      EDIT_MODAL: {
        TITLE: 'Chỉnh sửa hồ sơ',
        SUCCESS: 'Cập nhật hồ sơ thành công!',
        NAME: 'Tên hiển thị',
        PHONE: 'Số điện thoại',
        AVATAR: 'URL Ảnh đại diện',
        COVER: 'URL Ảnh bìa',
        BIO: 'Tiểu sử',
        ADDRESS: 'Địa chỉ / Nơi sống',
        WORK: 'Nơi làm việc',
        CITY: 'Tỉnh/Thành phố',
        DISTRICT: 'Quận/Huyện',
        DISTRICT_PLACEHOLDER: 'Chọn Quận/Huyện',
        STREET: 'Địa chỉ chi tiết (Số nhà, tên đường...)',
        STREET_PLACEHOLDER: 'Ví dụ: 123 Đường Láng',
        MERCHANT_SYNC: 'Đồng bộ sang Cửa hàng (Merchant Sync)',
        SYNC_AVATAR: 'Đồng bộ avatar làm Logo quán',
        SYNC_COVER: 'Đồng bộ ảnh bìa sang trang quán',
        CLOSE_SETTINGS: 'Đóng cài đặt cá nhân',
      },
      MODALS: {
        FOLLOWERS_TITLE: 'Người theo dõi',
        FOLLOWERS_EMPTY: 'Chưa có người theo dõi nào',
        FOLLOWING_TITLE: 'Đang theo dõi',
        FOLLOWING_EMPTY: 'Chưa theo dõi ai',
        PRIVATE_LIST_ERROR: 'Danh sách này là riêng tư hoặc đã bị ẩn.',
      }
    },
    DANGER_ZONE: {
      TITLE: '⚠️ Vùng nguy hiểm (Danger Zone)',
      WARNING: 'CẢNH BÁO: Hành động này là vĩnh viễn và không thể đảo ngược. Khi bạn xác nhận xóa tài khoản: Toàn bộ dữ liệu của bạn bao gồm hồ sơ cá nhân, các bài viết, lượt thích, đánh giá, lịch sử gợi ý AI, thông tin chi nhánh nhà hàng (nếu có) sẽ bị xóa hoàn toàn khỏi hệ thống và KHÔNG THỂ KHÔI PHỤC.',
      BUTTON: 'Xóa tài khoản của tôi',
      MODAL_TITLE: 'Xác nhận xóa tài khoản?',
      MODAL_WARNING: 'Hành động này sẽ xóa vĩnh viễn toàn bộ dữ liệu của bạn. Đây là thao tác tuyệt đối không thể khôi phục lại!',
      PASSWORD_LABEL: 'Nhập mật khẩu của bạn để xác nhận:',
      PASSWORD_PLACEHOLDER: 'Mật khẩu tài khoản của bạn',
      CONFIRM_BUTTON: 'Xác nhận xóa',
      CANCEL_BUTTON: 'Hủy bỏ',
      TOAST_PASSWORD_REQUIRED: 'Vui lòng nhập mật khẩu để xác nhận.',
      TOAST_SUCCESS: 'Tài khoản của bạn đã được xóa vĩnh viễn khỏi hệ thống.',
      TOAST_ERROR: 'Mật khẩu không chính xác hoặc có lỗi xảy ra.'
    }
  },
  NAV: {
    HOME: 'Trang chủ',
    EXPLORE: 'Khám phá',
    FORUM: 'Diễn đàn',
    OFFERS: 'Ưu đãi',
    ADMIN_PANEL: 'Panel Admin',
    RESTAURANT_PANEL: 'Quản lý quán',
    DASHBOARD: 'Dashboard cá nhân',
    SETTINGS: 'Cài đặt',
    FEATURES: 'Tính năng',
    SEARCH_PLACEHOLDER: 'Tính năng tìm kiếm chức năng đang phát triển!',
    USER_MENU: 'Menu người dùng',
  },
  FOOTER: {
    DESCRIPTION: 'Nền tảng gợi ý món ăn thông minh bằng AI, giúp bạn tìm thấy hương vị yêu thích mọi lúc mọi nơi.',
    QUICK_LINKS: 'Liên kết nhanh',
    FOLLOW_US: 'Theo dõi chúng tôi',
    RIGHTS: '© 2026 Food AI. Tất cả quyền được bảo lưu.',
    TERMS: 'Quy định',
    POLICY: 'Chính sách',
    CONTACT: 'Liên hệ',
  },
  HERO: {
    TITLE_START: 'Bạn muốn ăn gì',
    TITLE_HIGHLIGHT: 'hôm nay?',
    DESCRIPTION: 'Hãy kể cho AI nghe về tâm trạng, ngân sách hoặc sở thích của bạn. Chúng tôi sẽ gợi ý món ăn hoàn hảo nhất ngay gần bạn.',
    BG_ALT: 'Hình nền trang chủ',
    OPEN_AI_TOOLTIP: 'Bật trợ lý AI',
    SEARCH_PLACEHOLDER: 'Hôm nay bạn cảm thấy thế nào?',
    PLACEHOLDER_AUTH: 'Hãy kể cho AI nghe bạn muốn ăn gì...',
    PLACEHOLDER_GUEST: 'Đăng nhập để chat với AI tư vấn...',
    SEARCH_BUTTON: 'Tìm',
    AI_THINKING: 'Đang suyyyyyy...',
    SUGGESTED_TITLE: 'Các món ăn gợi ý cho bạn:',
    FEATURES: {
      MOOD: 'Gợi ý theo tâm trạng',
      BUDGET: 'Phù hợp túi tiền',
      LOCATION: 'Quán ăn gần bạn',
    }
  },
  HOME: {
    NEARBY_TITLE: "Quán ngon Quanh đây",
    NEARBY_SUBTITLE: "Khám phá các món ăn hấp dẫn ngay tại vị trí của bạn",
    TODAY_TITLE: "Món ngon Nổi bật hôm nay",
    TODAY_SUBTITLE: "Những lựa chọn tuyệt vời được tuyển chọn trong ngày",
    WEEKLY_TITLE: "Món ngon Nổi bật tuần qua",
    WEEKLY_SUBTITLE: "Danh sách các món ăn được cộng đồng yêu thích nhất tuần này",
    RECOMMENDED_TITLE: "Món ăn Được gợi ý",
    RECOMMENDED_SUBTITLE: "Các món ngon được chính Admin lựa chọn và đề xuất cho bạn",
  },
  FORM: {
    FOOD_NAME: 'Tên món ăn',
    PRICE: 'Giá (VNĐ)',
    DESCRIPTION: 'Mô tả',
    IMAGE_URL: 'Hình ảnh (URL)',
    TAGS: 'Tags',
    EMAIL: 'Email',
    ADDRESS: 'Địa chỉ',
    PHONE: 'Số điện thoại',
    MAP_URL: 'Link Google Maps',
    LAT: 'Vĩ độ (Latitude)',
    LNG: 'Kinh độ (Longitude)',
    NOT_SET: 'Chưa cập nhật',
    NO_PREFERENCES: 'Bạn chưa cập nhật sở thích.',
    OPINION_PLACEHOLDER: 'Hãy nhập ý kiến của bạn tại đây...',
    EMAIL_REQUIRED: 'Vui lòng nhập email',
    EMAIL_INVALID: 'Email không đúng định dạng',
    PASSWORD_REQUIRED: 'Vui lòng nhập mật khẩu',
    PASSWORD_INVALID: 'Mật khẩu phải từ 8 ký tự, gồm cả chữ và số',
    CONFIRM_PASSWORD_MISMATCH: 'Mật khẩu nhập lại không trùng khớp',
    NAME_REQUIRED: 'Tên phải có ít nhất 2 ký tự',
    LEGAL_DOCS_REQUIRED: 'Vui lòng cung cấp thông tin giấy tờ pháp lý rõ ràng',
    PLACEHOLDERS: {
      NAME: 'Nguyễn Văn User',
      EMAIL: 'user123@gmail.com',
      PASSWORD: '••••••••',
      ADDRESS: 'Hà Nội, Việt Nam...',
      WORK: 'Công ty ABC...',
    }
  },
  EXPLORE: {
    TITLE: 'Khám phá theo danh mục',
    TITLE_TAG: (tag: string) => tag ? `Khám phá "${tag}"` : 'Khám phá quán ăn',
    FOUND_COUNT: (count: number) => `Tìm thấy ${count} quán ăn phù hợp`,
    SEARCH_IN_TAG: (tag: string) => tag ? `Tìm kiếm quán ăn trong mục ${tag}...` : 'Tìm kiếm quán ăn...',
    EMPTY_TITLE: 'Rất tiếc, không tìm thấy quán ăn nào!',
    EMPTY_DESC: 'Bạn hãy thử tìm kiếm với từ khóa khác nhé.',
    LOADING: 'Đang tải trang khám phá...',
    SEARCHING: 'Đang tìm kiếm quán ăn cho bạn...',
    TAG_PLACEHOLDER: 'Nhập 1 hoặc nhiều tag cách nhau bởi dấu phẩy bạn nhé!',
    SUGGESTED_TAGS: 'Gợi ý:',
    ALL_DISTRICTS: 'Tất cả Quận/Huyện',
  },
  FOOD: {
    DETAIL_TITLE: 'Mô tả món ăn',
    RESTAURANT_TITLE: 'Địa chỉ quán',
    VIEW_MAP: 'Xem vị trí trên bản đồ',
    NO_ADDRESS: 'Chưa cập nhật địa chỉ',
    STORE_PAGE: 'Trang Quán ăn',
    REVIEWS: 'Xem các bài đánh giá',
    ADD_FAVORITE: 'Thêm vào yêu thích',
    VIEW_DETAIL: 'Xem chi tiết',
    NO_DESCRIPTION: 'Không có mô tả',
    NO_IMAGE: 'Không có ảnh',
    UNCATEGORIZED: 'Chưa phân loại',
    SYSTEM: 'Hệ thống',
  },
  UI_MESSAGES: {
    CATEGORY: {
      LOAD_ERROR: 'Lỗi khi tải danh mục',
      GROUP_NAME_REQUIRED: 'Vui lòng nhập tên nhóm',
      GROUP_UPDATE_SUCCESS: 'Đã cập nhật nhóm',
      GROUP_ADD_SUCCESS: 'Đã thêm nhóm mới',
      GROUP_DELETE_SUCCESS: 'Đã xóa nhóm',
      CATEGORY_NAME_REQUIRED: 'Vui lòng nhập tên phân loại',
      CATEGORY_UPDATE_SUCCESS: 'Đã cập nhật phân loại',
      CATEGORY_ADD_SUCCESS: 'Đã thêm phân loại mới',
      CATEGORY_DELETE_SUCCESS: 'Đã xóa phân loại',
      HAS_FOODS_ERROR: 'Có lỗi xảy ra (có thể danh mục đang có món ăn)',
      MAX_GROUPS_LIMIT_ERROR: (max: number) => `Bạn chỉ được phép tạo tối đa ${max} Nhóm danh mục để đảm bảo Menu không quá dài.`,
      GROUP_ORDER_DUPLICATE_ERROR: (order: number) => `Thứ tự hiển thị số ${order} đã bị trùng với nhóm khác. Vui lòng chọn số khác!`,
      CATEGORY_ORDER_DUPLICATE_ERROR: (order: number) => `Thứ tự số ${order} đã tồn tại trong danh sách này. Vui lòng chọn số khác!`,
    },
    RESTAURANT: {
      SELECT_REQUIRED: 'Vui lòng chọn cơ sở kinh doanh',
    },
    ADMIN: {
      UPDATE_FAILED: 'Cập nhật thất bại',
      UPDATE_SUCCESS: 'Cập nhật thành công',
      LOAD_ERROR: 'Lỗi lấy dữ liệu admin:',
    },
  },
  IMPORT_EXCEL: {
    MESSAGES: {
      INVALID_FILE_TYPE: 'Vui lòng chọn file Excel (.xlsx) hoặc CSV (.csv)',
      IMPORT_SUCCESS: (created: number, appended: number) => `Import thành công! Đã tạo ${created} nhà hàng, gộp ${appended} nhà hàng.`,
      IMPORT_ERROR_DEFAULT: 'Lỗi khi import file Excel',
      VALID_TYPES: [
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'application/vnd.ms-excel',
        'text/csv'
      ],
      TEMPLATE_HEADERS: 'Email,Password,Owner Name,Restaurant Name,Address,Latitude,Longitude,Restaurant Map URL,Food Name,Food Price,Food Desc,Food Image URL,Food Tags\n',
      TEMPLATE_SAMPLE: 'merchant@gmail.com,password123,Nguyen Van A,Pizza Ha Noi,Ha Noi,21.0285,105.8542,https://maps.app.goo.gl/example,Pizza Hai San,150000,Pizza ngon thuong hang,https://example.com/pizza.jpg,"ngon,hai san"\n',
      TEMPLATE_FILENAME: 'merchant_template.csv',
    },
    UI: {
      TITLE: 'Import dữ liệu hàng loạt',
      TEMPLATE_TITLE: 'Tải file mẫu (Template)',
      TEMPLATE_DESC: 'Sử dụng file CSV/Excel mẫu để nhập liệu chuẩn xác.',
      BTN_DOWNLOAD: 'Tải mẫu',
      DROPZONE_TITLE_FILE: 'Click hoặc kéo thả file vào đây',
      DROPZONE_SUBTITLE_FILE: 'Hỗ trợ định dạng .xlsx, .csv',
      BTN_REMOVE_FILE: 'Xóa file',
      BTN_CANCEL: 'Hủy',
      BTN_IMPORT: 'Import Ngay',
      BTN_LOADING: 'Đang xử lý...'
    }
  },
  ONBOARDING: {
    BRANCH_STEP_TITLE: 'Thiết lập vị trí & chi nhánh kinh doanh',
    BRANCH_STEP_DESC: 'Khai báo cơ sở (tên quán, địa chỉ chính xác, Google Maps) để AI tối ưu hóa hiển thị cho thực khách xung quanh.',
    ADD_BRANCH_BTN: 'Thêm Cơ Sở Khác (+ Chi Nhánh)',
    BACK_BTN: 'Quay Lại',
    COMPLETE_BTN: 'Hoàn Tất & Khởi Tạo',
    REQUIRED_BRANCH_FIELDS: (index: number) => `Vui lòng điền đầy đủ Tên và Địa chỉ của Cơ sở thứ ${index}.`,
    INVALID_COORDINATES: (index: number) => `Tọa độ (Kinh/Vĩ độ) của Cơ sở thứ ${index} bắt buộc phải là số.`,
    INVALID_LATITUDE: (index: number) => `Vĩ độ (Latitude) của Cơ sở thứ ${index} phải nằm trong khoảng từ -90 đến 90.`,
    INVALID_LONGITUDE: (index: number) => `Kinh độ (Longitude) của Cơ sở thứ ${index} phải nằm trong khoảng từ -180 đến 180.`,
    INVALID_HOURS_FORMAT: (index: number) => `Giờ hoạt động của Cơ sở thứ ${index} không đúng định dạng (Ví dụ đúng: 08:00 - 22:00).`,
    MIN_BRANCH_REQUIRED: 'Thương gia bắt buộc phải khai báo ít nhất 1 cơ sở chính.',
    ADD_BRANCH_SUCCESS: 'Đã thêm 1 chi nhánh trống. Vui lòng điền thông tin bên dưới.',
    REMOVE_BRANCH_SUCCESS: 'Đã xóa cơ sở khỏi danh sách.',
    STEP_INDICATOR: (current: number, total: number) => `Bước ${current} / ${total}`,
    FORM: {
      NAME_LABEL: 'Tên cơ sở / Chi nhánh',
      NAME_PLACEHOLDER: 'Ví dụ: FOOD AI - Chi Nhánh Hà Nội',
      ADDRESS_LABEL: 'Địa chỉ thực tế',
      ADDRESS_PLACEHOLDER: 'Ví dụ: 123 Nguyễn Trãi, Thanh Xuân, Hà Nội',
      LAT_LABEL: 'Vĩ độ (Latitude)',
      LAT_PLACEHOLDER: 'Ví dụ: 20.976094137561798',
      LNG_LABEL: 'Kinh độ (Longitude)',
      LNG_PLACEHOLDER: 'Ví dụ: 105.76295609115984',
      MAP_URL_LABEL: 'Link bản đồ Google Maps (Tùy chọn)',
      MAP_URL_PLACEHOLDER: 'Ví dụ: https://maps.google.com/...',
      HOURS_LABEL: 'Giờ hoạt động (Tùy chọn)',
      HOURS_PLACEHOLDER: 'Ví dụ: 09:00 - 21:00',
      BIO_LABEL: 'Khẩu hiệu / Giới thiệu ngắn',
      BIO_PLACEHOLDER: 'Ví dụ: Đồ ăn sạch, tốt cho sức khỏe...',
    },
    QUESTIONS: {
      CUSTOMER: {
        GOAL: {
          Q: 'Mục tiêu ăn uống của bạn là gì?',
          DESC: 'Để AI gợi ý những món ăn phù hợp với sức khỏe của bạn.',
          OPT: { WEIGHT_LOSS: 'Giảm cân', MUSCLE_GAIN: 'Tăng cơ', EAT_CLEAN: 'Ăn sạch (Eat Clean)', ENJOY: 'Thưởng thức' }
        },
        CUISINE: {
          Q: 'Bạn đặc biệt thích phong cách ẩm thực nào?',
          DESC: 'Chúng tôi sẽ ưu tiên hiển thị các quán có hương vị này.',
          OPT: { VIETNAMESE: 'Việt Nam', KOREAN: 'Hàn Quốc', JAPANESE: 'Nhật Bản', WESTERN: 'Âu Mỹ' }
        },
        BUDGET: {
          Q: 'Ngân sách cho một bữa ăn của bạn?',
          DESC: 'Gợi ý các quán ăn phù hợp với túi tiền của bạn.',
          OPT: { UNDER_100K: 'Dưới 100k', '100K_200K': '100k - 200k', '200K_400K': '200k - 400k', OVER_400K: 'Trên 400k' }
        },
        ALLERGIES: {
          Q: 'Bạn có bị dị ứng với gì không?',
          DESC: 'An toàn của bạn là trên hết. Hãy cho AI biết nhé!',
          OPT: { SEAFOOD: 'Hải sản', PEANUTS: 'Đậu phộng', DAIRY: 'Sữa/Phô mai', NONE: 'Không dị ứng' }
        }
      },
      RESTAURANT: {
        STYLE: {
          Q: 'Phong cách quán của bạn là gì?',
          DESC: 'Giúp khách hàng hình dung về không gian quán.',
          OPT: { LUXURY: 'Sang trọng', CASUAL: 'Bình dân', STREET: 'Vỉa hè/Đường phố', TAKEAWAY: 'Bán mang về' }
        },
        FLAVOR: {
          Q: 'Hương vị chủ đạo của quán là gì?',
          DESC: 'Khách hàng thường tìm kiếm theo hương vị ưa thích.',
          OPT: { SPICY: 'Cay nồng', SWEET: 'Ngọt ngào', SAVORY: 'Đậm đà', LIGHT: 'Thanh đạm' }
        },
        TARGET: {
          Q: 'Đối tượng khách hàng bạn muốn tiếp cận?',
          DESC: 'AI sẽ ưu tiên hiển thị quán cho tệp khách này.',
          OPT: { STUDENTS: 'Sinh viên', OFFICE: 'Dân văn phòng', FAMILY: 'Gia đình', TOURISTS: 'Khách du lịch' }
        }
      }
    }
  },
  CATEGORIES: {
    NAMES: {
      WATER: 'Món nước',
      RICE: 'Cơm / Xôi',
      SNACK: 'Ăn vặt',
      DESSERT: 'Tráng miệng',
      CASUAL: 'Bình dân',
      LUXURY: 'Cao cấp'
    },
    TAGS: {
      TRADITIONAL: 'truyền thống',
      FASTFOOD: 'ăn nhanh',
      FRIED: 'đồ chiên',
      ALONE: 'một mình',
      GROUP: 'nhiều người',
      OFFICE: 'văn phòng',
      SPICY: 'cay',
      HEALTHY: 'healthy'
    }
  },
  AI_CHAT: {
    SIDEBAR: {
      NEW_CHAT: 'Đoạn chat mới',
      RECENT: 'Gần đây',
      NO_CHAT: 'Chưa có đoạn chat nào',
      CLOSE_SIDEBAR: 'Đóng sidebar',
      DELETE_CHAT: 'Xóa đoạn chat',
      CUSTOMER: 'Khách hàng',
      FREE_PLAN: 'Free Plan',
      REFRESH_LIST: 'Làm mới danh sách',
    },
    HEADER: {
      OPEN_SIDEBAR: 'Mở sidebar',
      SIMULATE_CONTEXT: 'Thời tiết tại',
      COLLAPSE_CHAT: 'Thu gọn khung chat',
      ACTIVE: 'Đang hoạt động',
    },
    CONFIG: {
      WEATHER_TITLE: 'Thời tiết Thực tế',
      TEMPERATURE: 'Nhiệt độ',
      STATUS: 'Trạng thái',
      RAINY: 'Có mưa 🌧️',
      DRY: 'Khô ráo ☀️',
      LOCATION_TITLE: 'Vị trí & Tọa độ GPS',
      GPS_COORDS: 'Tọa độ GPS',
      UPDATE_GPS: 'Cập nhật vị trí hiện tại',
      TIPS_TITLE: '💡 Cơ chế tự động phát hiện:',
      TIP_1: '1. Hệ thống tự động lấy tọa độ GPS từ trình duyệt để đồng bộ thời tiết thực tế từ Open-Meteo.',
      TIP_2: '2. Trợ lý AI sẽ tự động phân tích (nhiệt độ, mưa, độ ẩm, gió) để gợi ý các món ăn tối ưu nhất.',
      WEATHER_TEMP_LIMITS: {
        MIN: 15,
        MAX: 42,
      },
      GPS_DEFAULTS: {
        LAT: 21.0285,
        LNG: 105.8542,
      },
      CITY_DEFAULTS: {
        NAME: 'Hà Nội',
      },
      SYNCING_WEATHER: 'Đang đồng bộ thời tiết...',
      FEELS_LIKE: (temp: number) => `Cảm nhận ${temp}°C`,
      HUMIDITY: 'Độ ẩm',
      WIND_SPEED: 'Sức gió',
      NO_WEATHER_DATA: 'Chưa có dữ liệu thời tiết. Hãy cập nhật GPS để kích hoạt.',
      LATITUDE: 'Vĩ độ (Lat)',
      LONGITUDE: 'Kinh độ (Lng)',
      UPDATE_BTN: 'Cập nhật',
    },
    FEED: {
      WELCOME: 'Xin chào! Tôi có thể giúp gì cho bạn hôm nay?',
      WELCOME_SUB: 'Hãy hỏi tôi bất kỳ điều gì (Ví dụ: "Hôm nay ăn gì ngon", "Tôi muốn tìm quán bún chả gần đây",...)',
      SUGGESTION: 'Gợi ý cho bạn:',
      SEND_MESSAGE: 'Gửi tin nhắn',
      FEEDBACK_LIKE: '👍 Hữu ích',
      FEEDBACK_DISLIKE: '👎 Không phù hợp',
    },
    INPUT: {
      PLACEHOLDER: 'Hỏi trợ lý ẩm thực AI...',
      SEND: 'Gửi',
      SEARCH: 'Trò chuyện ngay!'
    },
    PREFERENCES: {
      TITLE: 'Cài đặt gợi ý AI',
      TAB_LIKED: 'Món ăn đã thích',
      TAB_DISLIKED: 'Đề xuất đã ẩn',
      LOADING: 'Đang tải danh sách...',
      EMPTY_LIST: 'Danh sách trống',
      EMPTY_LIKED_DESC: 'Bấm nút hữu ích (LIKE) trên các món ăn đề xuất trong đoạn chat để lưu vào đây.',
      EMPTY_DISLIKED_DESC: 'Bấm nút không phù hợp (DISLIKE) trong đoạn chat để ẩn các món ăn và lưu vào đây.',
      VOICE_INPUT_LABEL: 'Bật nhập bằng giọng nói',
      REMOVE_LIKE_SUCCESS: 'Đã bỏ thích món ăn!',
      REMOVE_DISLIKE_SUCCESS: 'Đã gỡ món ăn khỏi danh sách ẩn đề xuất!',
      LOAD_ERROR: 'Không thể tải danh sách sở thích.',
      REMOVE_ERROR: 'Không thể gỡ phản hồi. Vui lòng thử lại.',
      TOOLTIP_REMOVE: 'Gỡ phản hồi',
      TAB_GENERAL: 'Chung',
      TAB_PERSONALIZATION: 'Cá nhân hóa',
      TAB_DATA_CONTROL: 'Kiểm soát dữ liệu',
      TAB_ACCOUNT: 'Tài khoản',
      THEME_LABEL: 'Giao diện',
      THEME_MIXED: 'Pha trộn (Mixed)',
      THEME_LIGHT: 'Sáng',
      THEME_DARK: 'Tối',
      LANG_LABEL: 'Ngôn ngữ',
      LANG_AUTO: 'Dò tìm tự động',
      LANG_VI: 'Tiếng Việt',
      LANG_EN: 'Tiếng Anh',
      DELETE_FEEDBACKS_TITLE: 'Xóa toàn bộ phản hồi gợi ý AI',
      DELETE_FEEDBACKS_DESC: 'Hành động này sẽ xóa sạch danh sách món ăn đã Thích (LIKE) và Đề xuất đã ẩn (DISLIKE), đưa mô hình gợi ý AI cá nhân hóa về trạng thái mặc định.',
      DELETE_FEEDBACKS_BTN: 'Xóa tất cả phản hồi',
      DELETE_FEEDBACKS_CONFIRM: 'Bạn có chắc chắn muốn xóa toàn bộ lịch sử phản hồi Like/Dislike không? Hành động này cũng sẽ gỡ các món ăn khỏi danh sách yêu thích của bạn!',
      DELETE_FEEDBACKS_SUCCESS: 'Đã xóa toàn bộ phản hồi thành công!',
      DELETE_FEEDBACKS_ERROR: 'Lỗi khi xóa phản hồi. Vui lòng thử lại.',
      ACCOUNT_INFO_TITLE: 'Thông tin tài khoản thực khách',
      ACCOUNT_NAME: 'Họ tên',
      ACCOUNT_EMAIL: 'Địa chỉ Email',
      ACCOUNT_ROLE: 'Vai trò tài khoản',
      ACCOUNT_PLAN: 'Gói dịch vụ',
    },
    CONFIRM: {
      DELETE_CHAT: 'Bạn có chắc chắn muốn xóa đoạn hội thoại này không?',
      EMPTY_CHAT_WARNING: 'Bạn đã có một đoạn chat mới chưa sử dụng.',
      ERROR_FALLBACK: 'Xin lỗi, tôi gặp chút trục trặc hệ thống.',
    },
    TOAST: {
      GPS_SUCCESS: 'Đã cập nhật tọa độ từ GPS của thiết bị.',
      GPS_ERROR: 'Không thể lấy tọa độ GPS từ trình duyệt.',
      GPS_NOT_SUPPORTED: 'Trình duyệt không hỗ trợ GPS.',
      LOAD_HISTORY_ERROR: 'Lỗi tải lịch sử cuộc hội thoại:',
      SEND_FIRST_ERROR: 'Lỗi gửi tin nhắn đầu tiên:',
      GPS_WARN: 'Không lấy được GPS thực tế, dùng GPS giả lập mặc định:',
      FEEDBACK_LIKE_SUCCESS: 'Đã đánh dấu hữu ích! AI sẽ gợi ý các món ăn tương tự.',
      FEEDBACK_DISLIKE_SUCCESS: 'Đã ghi nhận phản hồi! AI sẽ hạn chế gợi ý món ăn này.',
      FEEDBACK_ERROR: 'Lỗi khi gửi phản hồi.',
    }
  },
  LOYALTY: {
    TITLE: 'Tích điểm & Đổi Voucher',
    POINTS_BALANCE: 'Số dư điểm thưởng:',
    LEVEL: 'Cấp độ:',
    BADGE: 'Danh hiệu:',
    REDEEM: 'Đổi ngay',
    REDEEM_SUCCESS: 'Đổi voucher thành công!',
    REDEEM_ERROR: 'Không đủ điểm để đổi voucher.',
    VOUCHERS_TITLE: 'Chợ Voucher giảm giá',
    MY_VOUCHERS_TITLE: 'Vouchers của tôi',
    VOUCHER_REDEEMED_BADGE: 'Đã đổi',
    VOUCHER_CODE_PREFIX: 'Mã: ',
    VOUCHER_MIN_SPEND_PREFIX: 'Đơn tối thiểu: ',
    VOUCHER_EXPIRY_PREFIX: 'Hạn dùng: ',
    VOUCHER_EXPIRY_SUFFIX: ' ngày kể từ lúc đổi',
    VOUCHER_EMPTY: 'Bạn chưa đổi voucher nào.',
    VOUCHER_EARN_DESC: 'Tích điểm qua các hoạt động đặt món, review và đóng góp cho cộng đồng Food AI.',
    REDEEM_SUCCESS_WITH_CODE: (code: string) => `Đổi voucher thành công! Mã code của bạn: ${code}`,
    XP_PROGRESS: 'Kinh nghiệm (XP) để lên cấp tiếp theo',
    REQUIRED_POINTS: (points: number) => `${points} Điểm`,
    LEVEL_UP_SUCCESS: (level: number) => `🎉 Chúc mừng! Bạn đã thăng cấp lên Level ${level}!`,
    AWARD_POINTS_SUCCESS: (points: number, reason: string) => `+${points} điểm tích lũy: ${reason}`,
    BADGES: {
      EXPERT: 'Chuyên Gia Ẩm Thực',
      VIP: 'Thánh Review Cao Cấp',
    },
    AVAILABLE_VOUCHERS: [
      {
        id: 'v1',
        code: 'FOODAI15K',
        title: 'Giảm trực tiếp 15,000đ',
        description: 'Áp dụng cho mọi đơn hàng từ đối tác Food AI.',
        pointsCost: 300,
        discountValue: '15,000đ',
        minSpend: '50,000đ',
        expiryDays: 30,
      },
      {
        id: 'v2',
        code: 'FOODAI30K',
        title: 'Giảm trực tiếp 30,000đ',
        description: 'Áp dụng cho đơn hàng được đề xuất bởi AI.',
        pointsCost: 500,
        discountValue: '30,000đ',
        minSpend: '100,000đ',
        expiryDays: 15,
      },
      {
        id: 'v3',
        code: 'FOODAI50K',
        title: 'Ưu đãi đặc quyền 50,000đ',
        description: 'Voucher cao cấp cho thành viên VIP.',
        pointsCost: 800,
        discountValue: '50,000đ',
        minSpend: '150,000đ',
        expiryDays: 45,
      },
      {
        id: 'v4',
        code: 'FREESHIPAI',
        title: 'Miễn phí vận chuyển (Tối đa 20k)',
        description: 'Áp dụng cho các nhà hàng lân cận trong bán kính 3km.',
        pointsCost: 150,
        discountValue: 'FreeShip',
        minSpend: '0đ',
        expiryDays: 7,
      },
    ],
    DEFAULT_BADGES: [
      { id: 'b1', role: 'CUSTOMER' as const, title: 'Thực Khách Năng Động', points: 300 },
      { id: 'b2', role: 'CUSTOMER' as const, title: 'Chuyên Gia Ẩm Thực', points: 1000 },
      { id: 'b3', role: 'CUSTOMER' as const, title: 'Thánh Review Cao Cấp', points: 3000 },
      { id: 'b4', role: 'RESTAURANT' as const, title: 'Đối Tác Tiềm Năng', points: 500 },
      { id: 'b5', role: 'RESTAURANT' as const, title: 'Đối Tác Uy Tín', points: 2000 },
      { id: 'b6', role: 'RESTAURANT' as const, title: 'Thương Hiệu Xuất Sắc', points: 5000 },
    ],
  },
  OFFERS: {
    TITLE: 'Ưu đãi & Khuyến mãi',
    BANNER_BADGE: 'Cơn lốc ưu đãi ẩm thực',
    BANNER_TITLE: 'Khuyến Mãi \nĐặc Biệt Hôm Nay',
    BANNER_DESC: 'Khám phá các combo cực hời, mã giảm giá sâu từ hàng trăm nhà hàng đối tác uy tín được FOOD AI đề xuất riêng cho bạn.',
    CREATE_BTN: 'Đăng tin Khuyến mãi',
    MERCHANT_ONLY_TITLE: 'Dành cho Nhà hàng',
    MERCHANT_ONLY_DESC: 'Đăng nhập tài khoản Thương gia để đăng tin quảng bá quán của bạn.',
    FILTER: {
      ALL: 'Tất cả',
      DISCOUNT: 'Giảm giá',
      COMBO: 'Combo bán chạy',
      GIFT: 'Quà tặng kèm',
      OTHER: 'Ưu đãi khác',
    },
    SHOWING_COUNT: (count: number) => `Hiển thị ${count} ưu đãi`,
    EMPTY_TITLE: 'Chưa có khuyến mãi nào',
    EMPTY_DESC: 'Hiện tại chưa có chương trình khuyến mãi nào thuộc danh mục này. Quay lại sau nhé!',
    VALID_UNTIL: (date: string) => `Hạn dùng: ${date}`,
    VIEW_STORE: 'Xem quán',
    CONTACT_TOAST: (name: string) => `Liên hệ ${name} để áp dụng ưu đãi!`,
    CREATE_MODAL_TITLE: 'Đăng chương trình Khuyến mãi',
    FORM: {
      TITLE_LABEL: 'Tiêu đề chương trình',
      TITLE_PLACEHOLDER: 'Ví dụ: Giảm giá cực mạnh cơm gà xối mỡ...',
      TYPE_LABEL: 'Loại khuyến mãi',
      TYPE_OPTIONS: {
        DISCOUNT: 'Giảm giá (%)',
        COMBO: 'Combo combo',
        GIFT: 'Tặng kèm (Gift)',
        OTHER: 'Ưu đãi khác',
      },
      VALUE_LABEL: 'Giá trị ưu đãi',
      VALUE_PLACEHOLDER: 'Ví dụ: Giảm 30%, Mua 1 Tặng 1...',
      EXPIRY_LABEL: 'Hạn sử dụng chương trình',
      MERCHANT_LABEL: 'Nhà hàng đăng tin (Mặc định)',
      MERCHANT_FALLBACK: 'Nhà hàng của bạn',
      DESC_LABEL: 'Mô tả chi tiết chương trình',
      DESC_PLACEHOLDER: 'Nhập mô tả cụ thể về món ăn áp dụng, điều kiện áp dụng nếu có...',
      IMAGE_LABEL: 'Chọn hình ảnh minh họa phù hợp',
      CANCEL: 'Hủy bỏ',
      SUBMIT: 'Đăng ngay',
    },
    TOAST: {
      TITLE_REQUIRED: 'Vui lòng nhập tiêu đề chương trình khuyến mãi!',
      VALUE_REQUIRED: 'Vui lòng nhập giá trị ưu đãi (ví dụ: Giảm 30%, Mua 1 Tặng 1)!',
      EXPIRY_REQUIRED: 'Vui lòng chọn hạn sử dụng ưu đãi!',
      DESC_REQUIRED: 'Vui lòng nhập mô tả chi tiết!',
      CREATE_SUCCESS: 'Đăng bài khuyến mãi thành công!',
    },
    PROMO_TYPES: {
      DISCOUNT: 'GIẢM GIÁ',
      COMBO: 'COMBO',
      GIFT: 'TẶNG KÈM',
      OTHER: 'ƯU ĐÃI KHÁC',
    },
    DEFAULT_TEMPLATES: [
      { name: 'Pizza & Fastfood', url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80' },
      { name: 'Gà rán & Burgers', url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80' },
      { name: 'Món nước & Lẩu', url: 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=600&q=80' },
      { name: 'Đồ uống & Trà sữa', url: 'https://images.unsplash.com/photo-1541658016709-82535e94bc69?auto=format&fit=crop&w=600&q=80' },
      { name: 'Tráng miệng & Bánh ngọt', url: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80' },
    ],
    SEED_OFFERS: [
      {
        id: 1,
        title: 'Đại tiệc lẩu Thái giảm sâu cuối tuần',
        description: 'Ưu đãi cực khủng cho nhóm từ 4 người trở lên. Trải nghiệm hương vị lẩu Thái chua cay chuẩn vị với nguyên liệu hải sản tươi sống nhập khẩu trong ngày.',
        promoType: 'DISCOUNT' as const,
        discountValue: 'Giảm 30%',
        restaurantName: 'Thái Express Royal',
        image: 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=600&q=80',
        validUntil: '30/06/2026',
      },
      {
        id: 2,
        title: 'Siêu Combo Gà Rán - Mua 1 Tặng 1',
        description: 'Mua ngay 1 phần gà rán siêu giòn cay cỡ lớn, nhận ngay 1 phần gà rán tương tự hoàn toàn miễn phí. Chương trình áp dụng cho cả giao hàng và ăn tại quán.',
        promoType: 'COMBO' as const,
        discountValue: 'Mua 1 Tặng 1',
        restaurantName: 'KFC Food Central',
        image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
        validUntil: '25/06/2026',
      },
      {
        id: 3,
        title: 'Tặng Matcha Cake khi mua Trà sữa size L',
        description: 'Mừng tháng thương hiệu, Gong Cha gửi tặng 1 phần bánh ngọt Matcha kem phô mai hảo hạng cho mỗi hóa đơn trà sữa size L bất kỳ.',
        promoType: 'GIFT' as const,
        discountValue: 'Tặng Bánh Ngọt',
        restaurantName: 'Gong Cha Tea',
        image: 'https://images.unsplash.com/photo-1541658016709-82535e94bc69?auto=format&fit=crop&w=600&q=80',
        validUntil: '20/06/2026',
      }
    ]
  },
  SOCIAL: {
    FEED_TITLE: 'Bảng tin ẩm thực',
    CREATE_POST: 'Đăng bài viết mới',
    POST_TYPE_NORMAL: 'Thông thường',
    POST_TYPE_REVIEW: 'Đánh giá quán',
    POST_TYPE_PROMOTION: 'Khuyến mãi',
    SELECT_POST_TYPE: 'Chọn loại bài viết',
    TITLE_LABEL: 'Tiêu đề bài viết',
    TITLE_PLACEHOLDER: 'Tiêu đề bài viết...',
    CONTENT_LABEL: 'Nội dung bài viết',
    CONTENT_PLACEHOLDER: 'Bạn đang nghĩ gì thế? Chia sẻ trải nghiệm ăn uống của bạn...',
    IMAGE_LABEL: 'Hình ảnh bài đăng (URL)',
    IMAGE_URL_PLACEHOLDER: 'URL Hình ảnh bài viết (tùy chọn)...',
    NO_LINK_OPTION: '-- Không liên kết --',
    RATING: 'Đánh giá sao:',
    SELECT_RESTAURANT: 'Chọn nhà hàng liên kết (tùy chọn)',
    SELECT_FOOD: 'Chọn món ăn liên kết (tùy chọn)',
    SUBMIT_POST: 'Đăng bài',
    LIKE: 'Thích',
    UNLIKE: 'Bỏ thích',
    COMMENT_PLACEHOLDER: 'Viết bình luận...',
    TOGGLE_COMMENTS: 'Xem bình luận',
    REPORT_COMMENT: 'Báo cáo bình luận',
    NO_COMMENTS: 'Chưa có bình luận nào. Hãy là người đầu tiên!',
    SEND_COMMENT: 'Gửi',
    REPORT: 'Báo cáo',
    COMMENTS_TITLE: 'Bình luận',
    POST_SUCCESS: 'Đăng bài viết thành công!',
    COMMENT_SUCCESS: 'Đã gửi bình luận!',
    LIKE_SUCCESS: 'Đã thích bài viết!',
    UNLIKE_SUCCESS: 'Đã bỏ thích bài viết!',
    TITLE_REQUIRED: 'Vui lòng nhập tiêu đề bài viết.',
    CONTENT_REQUIRED: 'Vui lòng nhập nội dung bài viết.',
    AUTHOR_FALLBACK: 'Bạn',
    SHARED_BADGE: 'Đã chia sẻ',
    SHARE: 'Chia sẻ',
    REPLY: 'Trả lời',
    REPLY_PLACEHOLDER: (userName: string) => `Phản hồi ${userName}...`,
    SEND: 'Gửi',
    DELETE_REPLY: 'Xóa phản hồi',
    DELETE_COMMENT: 'Xóa bình luận',
    RATING_STAR: (star: number) => `Đánh giá ${star} sao`,
    TOAST: {
      ACTION_DONE: (action: string) => `Đã thực hiện: ${action}`,
      SAVE_SUCCESS: 'Đã lưu bài viết thành công vào bộ sưu tập!',
      UNSAVE_SUCCESS: 'Đã bỏ lưu bài viết khỏi bộ sưu tập!',
      LOGIN_REQUIRED: 'Vui lòng đăng nhập để thực hiện chức năng này!',
      TITLE_REQUIRED: 'Vui lòng nhập tiêu đề bài viết.',
      CONTENT_REQUIRED: 'Vui lòng nhập nội dung bài viết.',
      POST_SUCCESS: 'Đăng bài viết thành công!',
      COMMENT_SUCCESS: 'Đã gửi bình luận!',
      LIKE_SUCCESS: 'Đã thích bài viết!',
      UNLIKE_SUCCESS: 'Đã bỏ thích bài viết!',
      CONTACT_TOAST: (name: string) => `Liên hệ ${name} để áp dụng ưu đãi!`,
    },
    DROPDOWN: {
      PIN: 'Ghim bài viết',
      EDIT: 'Chỉnh sửa bài viết',
      EDIT_AUDIENCE: 'Chỉnh sửa đối tượng',
      MUTE: 'Tắt thông báo về bài viết này',
      SHARE_PROMO: 'Chia sẻ mã quảng cáo hợp tác',
      UNTRANSLATE: 'Tắt bản dịch',
      EDIT_DATE: 'Chỉnh sửa ngày',
      REFRESH_ATTACHMENT: 'Làm mới file đính kèm được chia sẻ',
      SAVE: 'Lưu bài viết',
      UNSAVE: 'Bỏ lưu bài viết',
      REPORT: 'Báo cáo bài viết',
    }
  },
  MODERATION: {
    TITLE: 'Kiểm duyệt nội dung',
    PENDING_REPORTS: 'Hàng đợi báo cáo vi phạm',
    TARGET_TYPE: 'Loại vi phạm:',
    TARGET_ID: 'ID mục tiêu:',
    REPORT_REASON: 'Lý do báo cáo:',
    STATUS_PENDING: 'Đang chờ',
    STATUS_RESOLVED: 'Đã gỡ bỏ',
    STATUS_REJECTED: 'Đã bác bỏ',
    ACTION_APPROVE: 'Gỡ bài viết',
    ACTION_REJECT: 'Bác bỏ báo cáo',
    NO_REPORTS: 'Không có báo cáo nào cần xử lý.',
    RESOLVE_SUCCESS: 'Đã xử lý báo cáo thành công.',
    REPORT_SUBMITTED: 'Đã gửi báo cáo vi phạm. Cảm ơn sự hợp tác của bạn!',
    REPORT_TITLE: 'Báo cáo bài viết/bình luận vi phạm',
    REPORT_REASON_LABEL: 'Mô tả lý do báo cáo vi phạm:',
    REPORT_MAIN_REASON_LABEL: 'Lý do chính',
    REPORT_DETAILS_PLACEHOLDER: 'Nhập thông tin mô tả chi tiết tại đây (nếu có)...',
    REPORT_BANNER: 'Báo cáo của bạn sẽ được chuyển đến đội ngũ Quản trị viên của Food AI để kiểm duyệt. Vui lòng chọn lý do chính xác để giúp chúng tôi xây dựng cộng đồng ẩm thực an toàn.',
    DEFAULT_REPORT_CONTENT: 'Báo cáo vi phạm nội dung',
    REPORT_SUBMIT: 'Gửi báo cáo',
    REPORT_REASONS: [
      'Spam / Quảng cáo rác',
      'Ngôn từ kích động thù hận / Thô tục',
      'Nội dung không lành mạnh / Nhạy cảm',
      'Thông tin sai lệch / Gian lận',
      'Món ăn hoặc nhà hàng không có thực',
      'Lý do khác (Mô tả chi tiết bên dưới)',
    ],
    REPORT_OTHER_PREFIX: 'Lý do khác',
    REPORT_DETAIL_PREFIX: ' - Chi tiết: ',
    REJECT_SUCCESS: 'Đã bác bỏ báo cáo vi phạm. Nội dung được giữ nguyên.',
    CLEAN_STATE_DESC: 'Hệ thống của bạn đang rất sạch sẽ và an toàn. ✨',
    NOTIFICATIONS: {
      CONTENT_REMOVED_TITLE: 'Nội dung đã bị gỡ',
      POST_REMOVED_BODY: (title: string) => `Bài viết "${title}" của bạn đã bị gỡ do vi phạm tiêu chuẩn cộng đồng.`,
      COMMENT_REMOVED_BODY: (postTitle: string) => `Bình luận của bạn trên bài viết "${postTitle}" đã bị gỡ do vi phạm tiêu chuẩn cộng đồng.`,
      REPORT_RESOLVED_TITLE: 'Báo cáo đã xử lý',
      REPORT_RESOLVED_BODY: (targetType: string, id: number) => `Báo cáo của bạn về ${targetType === 'POST' ? 'bài viết' : 'bình luận'} #${id} đã được xử lý: Nội dung vi phạm đã bị gỡ bỏ.`,
      REPORT_DISMISSED_BODY: (targetType: string, id: number) => `Báo cáo của bạn về ${targetType === 'POST' ? 'bài viết' : 'bình luận'} #${id} đã được kiểm duyệt: Không phát hiện vi phạm.`,
    }
  },
  ANALYTICS: {
    TITLE: 'Thống kê & Phân tích Cửa hàng',
    VIEWS: 'Lượt xem món ăn',
    RECOMMENDATIONS: 'Số lần AI gợi ý',
    AI_CONVERSION_RATE: 'Hiệu suất chuyển đổi AI',
    AI_INSIGHTS: 'Lời khuyên kinh doanh tự động từ Trợ lý AI',
    TIME_PERIOD: 'Thời gian: 30 ngày qua',
    CHART_TITLE: 'Tương quan lượt xem và tần suất gợi ý AI',
    CHART_TOOLTIP_VIEWS: 'Lượt xem',
    CHART_TOOLTIP_AI: 'AI gợi ý',
    INSIGHT_TIPS: [
      'Món ăn nổi bật nhất của bạn được gợi ý nhiều nhất bởi AI nhờ vào lượt click xem ổn định.',
      'Tối ưu hóa hình ảnh món ăn ít lượt xem để tăng khả năng AI lựa chọn đề xuất.',
      'Khách hàng có xu hướng thích các món có nhãn "Khuyến mãi" vào thời điểm 11h - 13h trưa.',
    ],
    EMPTY_TITLE: 'Chưa có dữ liệu phân tích',
    EMPTY_DESC: 'Thêm món ăn vào thực đơn để bắt đầu theo dõi lượt xem và gợi ý.',
    ERROR_OCCURRED: 'Đã xảy ra lỗi',
    COMPARE_SELECT_TITLE: 'Chọn món ăn để so sánh (Tối đa 8 món)',
    COMPARE_SELECT_ARIA: 'Danh sách món ăn so sánh',
    CHART_EMPTY_COMPARE: 'Vui lòng chọn ít nhất một món ăn ở danh sách bên dưới để xem so sánh trên biểu đồ.',
    CHART_SVG_TITLE: 'Biểu đồ cột kép so sánh lượt xem và đề xuất AI',
    CHART_ARIA_LABEL: 'Biểu đồ so sánh lượt xem và lượt đề xuất AI của các món ăn',
    CHART_GROUP_ARIA: (name: string) => `Món ăn ${name}`,
    CHART_BAR_VIEWS_ARIA: (name: string, views: number) => `${name}: ${views} lượt xem`,
    CHART_BAR_AI_ARIA: (name: string, aiSuggestions: number) => `${name}: ${aiSuggestions} lượt đề xuất AI`,
    ERROR_FETCH_FAILED: 'Không thể tải dữ liệu thống kê từ hệ thống.',
    TOAST_MAX_SELECTION: 'Bạn chỉ nên chọn tối đa 8 món để biểu đồ hiển thị đẹp nhất!',
    LOADING_ARIA: 'Đang tải dữ liệu thống kê',
  },
  BUG_REPORT: {
    TITLE: 'Báo cáo lỗi kỹ thuật',
    SUBTITLE: 'Gặp sự cố? Hãy gửi báo cáo lỗi ngay để chúng tôi hỗ trợ bạn!',
    CATEGORY: 'Danh mục sự cố',
    DESC: 'Mô tả chi tiết sự cố',
    DESC_PLACEHOLDER: 'Vui lòng mô tả chi tiết lỗi bạn gặp phải và các bước tái hiện (nếu có)...',
    IMAGE: 'Ảnh minh họa sự cố (URL)',
    IMAGE_PLACEHOLDER: 'Dán link ảnh chụp sự cố màn hình (nếu có)...',
    SUBMIT: 'Gửi báo cáo lỗi',
    SUCCESS: 'Đã gửi báo cáo lỗi thành công! Đội ngũ kỹ thuật sẽ sớm phản hồi.',
    DESC_TOO_SHORT: 'Mô tả sự cố phải tối thiểu 10 ký tự.',
    CATEGORIES: {
      AI: 'Lỗi gợi ý/AI chat',
      UI: 'Lỗi giao diện hiển thị',
      PERFORMANCE: 'Hệ thống phản hồi chậm',
      OTHER: 'Lỗi khác',
    },
  }
};

let clientLanguage = 'vi';

// Only use AsyncLocalStorage on the server
let serverStorage: { enterWith: (val: string) => void; getStore: () => string | undefined } | null = null;
if (typeof window === 'undefined') {
  try {
    const { AsyncLocalStorage } = eval('require')('async_hooks');
    serverStorage = new AsyncLocalStorage();
  } catch (e) { }
}

export const setLanguageForRequest = (lang: string) => {
  if (typeof window === 'undefined') {
    if (serverStorage) {
      serverStorage.enterWith(lang);
    }
  } else {
    clientLanguage = lang;
  }
};

const getIsEnglish = () => {
  if (typeof window === 'undefined') {
    if (serverStorage) {
      const lang = serverStorage.getStore();
      if (lang) return lang === 'en';
    }
    return false;
  }
  return clientLanguage === 'en';
};

export const LABELS = new Proxy({}, {
  get(target, prop) {
    const isEnglish = getIsEnglish();
    const dictionary = isEnglish ? LABELS_EN : LABELS_VI;
    return (dictionary as Record<string | symbol, unknown>)[prop];
  }
}) as typeof LABELS_EN;

