export const LABELS = {
  COMMON: {
    SAVE: 'Lưu thay đổi',
    CANCEL: 'Hủy',
    DELETE: 'Xóa',
    EDIT: 'Chỉnh sửa',
    APPROVE: 'Phê duyệt',
    REJECT: 'Từ chối',
    LOGOUT: 'Đăng xuất',
    BACK_HOME: 'Quay lại trang chủ',
    LOADING: 'Đang tải...',
    SUCCESS: 'Thành công',
    ERROR: 'Lỗi',
    NEXT: 'Tiếp theo',
    BACK: 'Quay lại',
    SEARCH: 'Tìm kiếm...',
    OTHER: 'Khác...',
    APP_TITLE: 'FOOD AI - Món ngon mỗi ngày',
    PROCESSING: 'Đang xử lý...',
    DEVELOPING: 'Tính năng đang phát triển',
    DEVELOPING_DESC: 'Chúng tôi đang phát triển tính năng này. Quay lại sau nhé! ✨',
    SEE_MORE: 'Xem thêm',
    UNNAMED: 'Chưa đặt tên',
    SCROLL_LEFT: 'Cuộn sang trái',
    SCROLL_RIGHT: 'Cuộn sang phải',
    TOGGLE_THEME: 'Chuyển đổi giao diện sáng/tối',
    CLOSE: 'Đóng',
    AI_BUSY: 'Rất tiếc, AI đang bận. Bạn thử lại sau nhé!',

    UNKNOWN: 'Chưa xác định',
    BRAND_NAME: 'Food AI',
    BRAND_LOGO_ALT: 'Food AI Logo',
    AI_ASSISTANT_NAME: 'Food AI Assistant',
    USER: 'Người dùng',
    STORE: 'Cửa hàng',
    PAGINATION: {
      PREVIOUS: 'Trang trước',
      NEXT: 'Trang sau',
      JUMP_TO_PAGE: 'Nhảy nhanh đến trang',
    },
  },
  AUTH: {
    LOGIN: 'Đăng nhập',
    REGISTER: 'Đăng ký',
    ADMIN: 'Quản trị viên',
    RESTAURANT_ROLE: 'Chủ nhà hàng',
    PROFILE: 'Hồ sơ cá nhân',
    LOGIN_TITLE: 'Đăng nhập',
    LOGIN_SUBTITLE: 'Chào mừng bạn quay trở lại với FoodAI',
    PASSWORD: 'Mật khẩu',
    OR_LOGIN_WITH: 'Hoặc đăng nhập bằng',
    SOCIAL_GOOGLE: 'Google',
    SOCIAL_FACEBOOK: 'Facebook',
    FORGOT_PASSWORD: 'Quên mật khẩu?',
    NO_ACCOUNT: 'Chưa có tài khoản?',
    REGISTER_NOW: 'Đăng ký ngay',
    REGISTER_TITLE: 'Tạo tài khoản',
    REGISTER_SUBTITLE: 'Bắt đầu hành trình khám phá ẩm thực thông minh',
    WHO_ARE_YOU: 'Bạn là ai?',
    CUSTOMER: 'Khách hàng',
    RESTAURANT: 'Nhà hàng',
    CONFIRM_PASSWORD: 'Xác nhận mật khẩu',
    LEGAL_DOCS: 'Giấy tờ pháp lý / Thông tin xác thực',
    LEGAL_DOCS_PLACEHOLDER: 'Số giấy phép kinh doanh hoặc link ảnh giấy tờ...',
    AGREE_TERMS: 'Tôi đồng ý với các điều khoản bảo mật và chính sách sử dụng.',
    ALREADY_HAVE_ACCOUNT: 'Đã có tài khoản?',
    VERIFY_ACCOUNT: 'Xác minh tài khoản',
    LOGIN_GO: 'Đi tới Đăng nhập',
    REGISTER_SUCCESS_PENDING: 'Đăng ký thành công! Đang chờ Admin phê duyệt.',
    REGISTER_SUCCESS_VERIFY: 'Đăng ký thành công! Vui lòng xác minh tài khoản.',
    LOGIN_REQUIRED: 'Vui lòng đăng nhập để thực hiện chức năng này!',
  },
  RESTAURANT: {
    DASHBOARD_TITLE: 'Chào mừng quay trở lại!',
    MENU_MANAGEMENT: 'Quản lý thực đơn',
    AI_HISTORY: 'Lịch sử đề xuất AI',
    SUBTITLE: 'Cửa hàng của bạn đang hoạt động rất tốt ✨',
    MERCHANT_HUB: 'Merchant Hub',
    STATUS: 'Trạng thái',
    ADD_FOOD: 'Đăng món mới',
    RECENT_ACTIVITY: 'Hoạt động gần đây',
    DELETE_BRANCH: 'Xóa cơ sở',
    BRANCH_NUMBER: (num: number) => `📍 Cơ sở ${num}`,
    VIEW_INSIGHT: 'Xem Insight chi tiết',
    VIEW_AS_GUEST: 'Xem với tư cách khách',
    NO_FOOD: 'Chưa có món ăn nào.',
    SAVE_SUCCESS_EDIT: 'Đã lưu! Chờ Admin duyệt.',
    SAVE_SUCCESS_ADD: 'Đã đăng! Chờ Admin duyệt.',
    AI_SUGGESTION_TITLE: 'Gợi ý AI cho quán',
    AI_SUGGESTION_DESC: 'Món "Phở cuốn" đang là xu hướng. Bạn có muốn thêm vào thực đơn?',
    STATUS_OPEN: 'Đang mở cửa',
    STATUS_CLOSED: 'Tạm nghỉ',
    STATUS_TOOLTIP: 'Khi chủ động đóng cửa (Tạm nghỉ), toàn bộ món ăn của bạn sẽ bị ẩn khỏi kết quả tìm kiếm và danh sách đề xuất của hệ thống.',
    SETTINGS_TITLE: 'Cài đặt Cửa hàng',
    OPERATING_HOURS: 'Giờ hoạt động định kỳ',
    CONTACT_PHONE: 'Số điện thoại liên hệ',
    SAVE: 'Lưu',
    STATUS_OPEN_SUCCESS: 'Cửa hàng đã mở cửa đón khách.',
    STATUS_CLOSE_SUCCESS: 'Cửa hàng đã tạm đóng cửa đột xuất.',
    STATUS_UPDATE_ERROR: 'Không thể cập nhật trạng thái cửa hàng.',
    DELETE_FOOD_CONFIRM: 'Bạn có chắc chắn muốn xóa món ăn này khỏi thực đơn không? Món ăn sẽ bị ẩn và không hiển thị đối với thực khách nữa.',
    DELETE_FOOD_CONFIRM_TITLE: 'Xác nhận xóa món ăn',
    HOURS_UPDATE_SUCCESS: 'Cập nhật giờ mở cửa thành công.',
    HOURS_UPDATE_ERROR: 'Không thể cập nhật giờ mở cửa.',
    CLOSED_WARNING_TITLE: 'Cửa hàng hiện đang tạm đóng cửa',
    CLOSED_BY_MERCHANT: 'Nhà hàng đã chủ động đóng cửa tạm thời.',
    CLOSED_OUTSIDE_HOURS: (hours: string) => `Ngoài khung giờ hoạt động của cửa hàng (${hours}).`,
    NOT_SET: 'chưa thiết lập',
    OPERATING_HOURS_LABEL: 'Giờ hoạt động',
    HOURS_PLACEHOLDER: 'Ví dụ: 08:00 - 22:00',
    HOURS_FORMAT_ERROR: 'Giờ hoạt động không đúng định dạng (Ví dụ đúng: 08:00 - 22:00).',
    TABS: {
      OVERVIEW: 'Tổng quan',
      CATEGORIES: 'Danh mục',
      MENU: 'Thực đơn của tôi',
      HISTORY: 'Lịch sử đề xuất',
    },
    EDIT_MODAL: {
      LIVE_PREVIEW: 'Live Card Preview',
      VERIFIED: 'Verified',
      BIO_PLACEHOLDER: 'Giới thiệu ngắn về nhà hàng...',
      NOT_OPENED: 'Chưa mở cửa',
      TIP: 'Thay đổi ảnh Logo và Ảnh bìa của quán sẽ cập nhật lập tức trên lưới Khám phá và trang hồ sơ công khai của nhà hàng.',
      SUBTITLE: 'Tùy chỉnh thương hiệu và thông tin liên hệ của quán ăn',
      TAB_INFO: 'Thông tin cơ bản',
      TAB_IMAGES: 'Hình ảnh thương hiệu',
      TAB_CONTACT: 'Liên hệ & Vận hành',
      NAME_LABEL: 'Tên nhà hàng',
      NAME_PLACEHOLDER: 'Ví dụ: FOOD AI - Chi nhánh Đống Đa',
      NAME_REQUIRED: 'Vui lòng nhập tên nhà hàng',
      BIO_LABEL: 'Giới thiệu ngắn (Bio)',
      BIO_INPUT_PLACEHOLDER: 'Món ăn sạch, thuần khiết tự nhiên...',
      DESC_LABEL: 'Mô tả chi tiết',
      DESC_PLACEHOLDER: 'Mô tả chi tiết về thực đơn, phong cách quán ăn của bạn...',
      LOGO_LABEL: 'URL Logo nhà hàng',
      LOGO_PLACEHOLDER: 'https://example.com/logo.png',
      SYNC_AVATAR: 'Đồng bộ ảnh Logo này làm ảnh đại diện cá nhân của bạn',
      COVER_LABEL: 'URL Ảnh bìa (Cover Image)',
      COVER_PLACEHOLDER: 'https://example.com/cover.png',
      SYNC_COVER: 'Đồng bộ ảnh bìa này làm ảnh bìa cá nhân của bạn',
      CITY_LABEL: 'Tỉnh / Thành phố',
      DISTRICT_LABEL: 'Quận / Huyện',
      ADDRESS_LABEL: 'Địa chỉ thực tế chi tiết',
      ADDRESS_PLACEHOLDER: 'Ví dụ: 123 Đường Láng, Láng Thượng',
      HOURS_LABEL: 'Giờ mở cửa (HH:MM - HH:MM)',
      PHONE_LABEL: 'Số điện thoại liên hệ',
      PHONE_PLACEHOLDER: '0987654321',
      EMAIL_LABEL: 'Email liên hệ',
      EMAIL_PLACEHOLDER: 'contact@quanphobac.com',
      MAPS_LABEL: 'Bản đồ chỉ đường (Google Maps Link)',
      MAPS_PLACEHOLDER: 'https://maps.app.goo.gl/...',
      CANCEL: 'Hủy bỏ',
      SUBMIT: 'Lưu cài đặt',
      SAVING: 'Đang lưu...',
      SAVE_ERROR: 'Lỗi khi cập nhật thông tin cửa hàng',
      CONFIRM_TITLE: 'Xác nhận lưu cài đặt',
      CONFIRM_DESC: 'Bạn có chắc chắn muốn lưu các thay đổi này cho cửa hàng không?',
    },
    CARD_LABELS: {
      DEFAULT_BIO: 'Hân hạnh được phục vụ quý khách thực đơn món ngon cao cấp.',
      FOLLOWERS_SUFFIX: 'người theo dõi',
      FOODS_SUFFIX: 'món ăn',
      DEFAULT_LOCATION: 'Việt Nam',
      DEFAULT_CATEGORY: 'Quán ăn',
    },
    TABLE: {
      FOOD: 'Món ăn',
      STATUS: 'Trạng thái',
      ACTION: 'Thao tác',
      FEATURE: 'Nổi bật',
      RECOMMEND: 'Đề xuất',
    },
    MODAL: {
      ADD_TITLE: 'Đăng món mới',
      EDIT_TITLE: 'Chỉnh sửa món ăn',
      SUBMIT_ADD: 'Đăng món ngay',
      SUBMIT_EDIT: 'Lưu thay đổi',
      BRANCH_LABEL: 'Cơ sở kinh doanh',
      BRANCH_PLACEHOLDER: '-- Chọn cơ sở --',
      CATEGORY_LABEL: 'Danh mục món ăn (Tùy chọn)',
      CATEGORY_PLACEHOLDER: '-- Không thuộc danh mục nào --',
      AUTO_FILL_BRANCH: '(Tự động điền theo cơ sở)',
      AUTO_FILL_LAT_LNG: '(Tự động điền)',
    },
    PUBLIC_PROFILE: {
      NOT_FOUND: 'Không tìm thấy quán ăn',
      NOT_FOUND_DESC: 'Đường dẫn không hợp lý hoặc cơ sở kinh doanh đã ngừng hoạt động.',
      MENU_TAB: 'Thực đơn món ăn',
      INFO_TAB: 'Thông tin quán ăn',
      EMPTY_MENU: 'Thực đơn trống',
      EMPTY_MENU_DESC: 'Quán ăn hiện chưa đăng tải món ăn nào đã được phê duyệt.',
      DETAIL_INFO: 'Thông tin Chi tiết',
      NO_HOURS: 'Chưa thiết lập giờ hoạt động',
      NO_PHONE: 'Chưa thiết lập số điện thoại',
      CONTACT_EMAIL: 'Email liên hệ',
      MAP_TITLE: 'Bản đồ chỉ đường',
      MAP_OPEN: 'Mở vị trí trên Google Maps',
      BIO_TITLE: 'Giới thiệu quán',
      BIO_EMPTY: 'Quán ăn chưa cập nhật thông tin giới thiệu chi tiết.',
      FOLLOWERS_TITLE: 'Người đang theo dõi',
      FOLLOWERS_EMPTY: 'Chưa có người theo dõi nào.',
      FOLLOWING_TITLE: 'Đang theo dõi quán',
      FOLLOWING_EMPTY: 'Chưa theo dõi quán ăn nào.',
      LOGIN_REQUIRED: 'Vui lòng đăng nhập để thực hiện tính năng này',
      FOLLOWERS_PRIVATE: 'Danh sách người theo dõi đã được ẩn bởi chủ quán',
      FOLLOWING_PRIVATE: 'Danh sách đang theo dõi đã được ẩn bởi chủ quán',
      LOAD_ERROR: 'Không thể tải danh sách',
      VIEWING_AS_GUEST: 'Bạn đang xem cửa hàng của mình dưới tư cách khách.',
      PRIVACY_TITLE: '🔒 Cài đặt quyền riêng tư',
      PRIVACY_LABEL: 'Hiển thị danh sách theo dõi',
      PRIVACY_DESC: 'Bật/tắt chế độ hiển thị danh sách người theo dõi và đang theo dõi trên trang của bạn.',
      PRIVACY_SUCCESS: 'Cập nhật quyền riêng tư thành công!',
      PRIVACY_ERROR: 'Lỗi cập nhật cài đặt.',
      MENU_CATEGORIES: 'Danh mục món ăn',
      ALL_FOODS: 'Tất cả món ăn',
      LOADING_FOODS: 'Đang tải món ăn...',
      LOADING_MORE: 'Đang tải...',
      LOAD_MORE: 'Xem thêm món',
      GO_TO_ADMIN: '[Vào trang quản trị]',
      MANAGE_RESTAURANT: 'Quản lý quán ăn',
      CATEGORY_MANAGER: {
        TITLE: 'Quản lý Nhóm & Danh mục',
        LOADING: 'Đang tải danh mục...',
        HELP_TOOLTIP: 'Nhóm (Group) là thư mục gốc ngoài cùng. Sau khi tạo Nhóm, bạn có thể ấn nút dấu [+] trên nhóm đó để tạo ra các Phân loại con (Category) bên trong.',
        ADD_GROUP: 'Thêm Nhóm Mới',
        GUIDE_TITLE: '💡 Hướng dẫn phân loại món ăn:',
        GUIDE_GROUP: 'Nhóm danh mục (Ví dụ: Đồ uống): Bạn có thể gán món ăn trực tiếp vào Nhóm này.',
        GUIDE_CATEGORY: 'Phân loại con (Ví dụ: Trà sữa, Nước ép): Nếu muốn chi tiết hơn, hãy ấn nút [+] trên Nhóm để tạo Phân loại con, sau đó gán món vào Phân loại con tương ứng.',
        PRIORITY_PREFIX: 'Ưu tiên hiển thị thứ: #',
        PRIORITY_SHORT: 'Ưu tiên số: #',
        ADD_ROOT_CATEGORY: 'Thêm danh mục gốc',
        ADD_SUB_CATEGORY: 'Thêm phân loại con',
        EMPTY_GROUP_NOTE: '📌 Bạn có thể gán món trực tiếp vào nhóm này, hoặc ấn nút [+] để tạo thêm phân loại con.',
        EMPTY_GROUPS: 'Chưa có nhóm danh mục nào',
        EDIT_GROUP: 'Sửa Nhóm',
        GROUP_NAME: 'Tên nhóm',
        DISPLAY_ORDER: 'Thứ tự hiển thị',
        ORDER_DESC_GROUP: 'Dùng để sắp xếp vị trí hiển thị trên Menu. Số càng nhỏ, nhóm càng được ưu tiên xếp lên trên. Ví dụ: Nhập 0 sẽ xếp đầu tiên, 1 xếp thứ hai.',
        GROUP_PLACEHOLDER: 'VD: Cơm phần, Đồ uống...',
        EDIT_CATEGORY: 'Sửa Phân Loại',
        ADD_CATEGORY: 'Thêm Phân Loại',
        CATEGORY_NAME: 'Tên phân loại',
        CATEGORY_PLACEHOLDER: 'VD: Cơm sườn, Nước ép...',
        ORDER_DESC_CATEGORY: 'Dùng để sắp xếp vị trí hiển thị trên Menu. Số càng nhỏ, phân loại này càng được ưu tiên xếp lên trước. Ví dụ: 0 là xếp đầu tiên.',
        CONFIRM_DELETE_TITLE: 'Xác nhận xóa',
        CONFIRM_DELETE_MESSAGE: (type: string) => `Bạn có chắc chắn muốn xóa ${type} này? Toàn bộ các danh mục con (nếu có) cũng sẽ bị xóa theo!`
      }
    },
    UPLOAD_EXCEL: {
      MAIN_GROUP: '📁 Nhóm chính',
      COLS: {
        NAME: 'Tên món',
        PRICE: 'Giá',
        DESC: 'Mô tả',
        IMAGE: 'Ảnh',
        TAGS: 'Tags'
      },
      FILE_NAME: 'mau-nhap-mon-an.xlsx',
      SHEET_NAME: 'Danh sách món ăn',
      DOWNLOAD_SUCCESS: 'Đã tải xuống file mẫu!',
      READ_SUCCESS: (count: number) => `Đọc thành công ${count} món từ file!`,
      READ_ERROR: 'Lỗi khi đọc file Excel. Vui lòng kiểm tra định dạng.',
      INVALID_DATA: 'Không tìm thấy dữ liệu hợp lệ. Kiểm tra lại tên cột và dữ liệu.',
      BRANCH_REQUIRED: 'Vui lòng chọn cơ sở áp dụng',
      EMPTY_DATA: 'Dữ liệu trống hoặc không hợp lệ',
      UPLOAD_SUCCESS: (count: number) => `Đã thêm thành công ${count} món ăn!`,
      UPLOAD_ERROR: 'Có lỗi xảy ra khi tải dữ liệu lên hệ thống.',
      TITLE: 'Upload Excel',
      GUIDE_TITLE: 'Hướng dẫn Upload Excel:',
      DOWNLOAD_BTN: 'Tải file mẫu',
      STEP_1: 'Bước 1: Chọn cơ sở',
      STEP_2: 'Bước 2: Chọn danh mục',
      STEP_3: 'Bước 3: Chọn file Excel',
      SELECT_BRANCH: '-- Chọn cơ sở --',
      SELECT_CATEGORY: '-- Chưa phân loại (bỏ qua) --',
      NO_CATEGORY_WARN: '⚠ Cơ sở này chưa có danh mục. Vào tab "Danh mục" để tạo trước.',
      LOADING_CATEGORY: 'Đang tải danh mục...',
      PREVIEW_TITLE: (count: number) => `Xem trước dữ liệu (${count} món)`,
      SAVING: 'Đang xử lý...',
      SAVE_BTN: (count: number) => `Lưu ${count > 0 ? count + ' món' : ''} vào hệ thống`,
      OPTIONAL: '(Tuỳ chọn)'
    }
  },
  ADMIN: {
    PANEL_TITLE: 'Admin Panel',
    APPROVE_MERCHANTS: 'Duyệt Thương gia',
    MANAGE_MERCHANTS: 'Quản lý Thương gia',
    MANAGE_CUSTOMERS: 'Quản lý Thực khách',
    MANAGE_MENU: 'Quản lý Thực đơn',
    IMPORT_EXCEL: 'Import Excel',
    SYSTEM_FOOD: 'Món ăn hệ thống',
    MERCHANT_FOOD: 'Món ăn đối tác',
    BATCH_SAVE: 'Lưu',
    BATCH_CANCEL: 'Hủy',
    DESELECT_ALL: 'Bỏ chọn tất cả',
    BATCH_SAVE_ALL: 'Lưu thay đổi',
    BATCH_CANCEL_ALL: 'Hủy thay đổi',
    UNSAVED_CHANGES: (count: number) => `Bạn có ${count} thay đổi chưa lưu trên các thực đơn đối tác.`,
    EDIT_MODE_LABEL: 'Chỉnh sửa',
    VIEW_MODE_LABEL: 'Xem',
    FILTER_ALL: 'Tất cả',
    FILTER_RECOMMENDED: 'Đề xuất',
    FILTER_UNRECOMMENDED: 'Chưa đề xuất',
    DONE: 'Hoàn tất',
    SAVE_SUCCESS: 'Cập nhật thành công!',
    DELETE_SUCCESS: 'Xóa thành công!',
    FEATURE_TODAY_ON: 'Đã Bật Nổi bật Ngày',
    FEATURE_TODAY_OFF: 'Đã Tắt Nổi bật Ngày',
    FEATURE_WEEKLY_ON: 'Đã Bật Nổi bật Tuần',
    FEATURE_WEEKLY_OFF: 'Đã Tắt Nổi bật Tuần',
    RECOMMEND_ON: 'Đã Bật Gợi ý',
    RECOMMEND_OFF: 'Đã Tắt Gợi ý',
    UPDATE_FAILED: 'Cập nhật thất bại',
    DELETE_WARNING: 'Bạn có chắc chắn muốn xóa tài khoản này?',
    CONFIRM_DELETE_USER: 'Bạn có chắc chắn muốn xóa tài khoản này?',
    MODAL: {
      EDIT_TITLE: 'Chỉnh sửa món ăn',
      FOOD_NAME: 'Tên món',
      PRICE: 'Giá (VNĐ)',
      TAGS: 'Tags',
      IMAGE_URL: 'URL Hình ảnh',
      DESCRIPTION: 'Mô tả',
    },
    TABLE: {
      NAME: 'Tên tài khoản',
      FOOD_NAME: 'Món ăn',
      SOURCE: 'Nguồn',
      EMAIL: 'Email',
      PRICE: 'Giá',
      DATE: 'Ngày đăng ký',
      ACTION: 'Thao tác',
      EMPTY: 'Không tìm thấy dữ liệu nào.',
      FEATURE_TODAY: 'Món ngon hôm nay',
      FEATURE_WEEKLY: 'Món ngon tuần',
      ADMIN_RECOMMEND: 'Admin khuyên dùng',
      SHOWING_FOODS: (count: number) => `Có ${count} món ăn`,
      SHOWING_RESTAURANTS: (count: number) => `Có ${count} quán ăn`,
      SHOWING_REQUESTS: (count: number) => `Có ${count} yêu cầu`,
      SHOWING_ACCOUNTS: (count: number) => `Có ${count} tài khoản`,
      DRAFT: 'Nháp',
    },
    CONFIRM: {
      DELETE_USER: 'Bạn có chắc chắn muốn xóa tài khoản này?',
      DELETE_FOOD: 'Bạn có chắc chắn muốn xóa món ăn này?',
      DELETE_FOOD_DESC: 'Hành động này không thể hoàn tác. Món ăn này sẽ bị xóa khỏi hệ thống vĩnh viễn.',
      DELETE_USER_DESC: 'Hành động này không thể hoàn tác. Người dùng này sẽ bị xóa khỏi hệ thống vĩnh viễn.',
      BATCH_SAVE: 'Xác nhận lưu thay đổi?',
      BATCH_SAVE_DESC: 'Bạn có chắc chắn muốn áp dụng toàn bộ các thay đổi nháp này lên các thực đơn món ăn đối tác không?',
      BATCH_DISCARD: 'Xác nhận hủy thay đổi?',
      BATCH_DISCARD_DESC: 'Tất cả các thay đổi nháp hiện tại trên các thực đơn đối tác sẽ bị xóa sạch. Hành động này không thể hoàn tác. Bạn có chắc chắn muốn hủy không?',
      APPROVE_FOOD: 'Xác nhận phê duyệt món ăn',
      APPROVE_FOOD_DESC: (name: string) => `Bạn có chắc chắn muốn phê duyệt món ăn "${name}"? Món ăn sẽ lập tức hiển thị công khai trên thực đơn của khách hàng.`,
      REJECT_FOOD: 'Xác nhận từ chối món ăn',
      REJECT_FOOD_DESC: (name: string) => `Bạn có chắc chắn muốn từ chối món ăn "${name}"? Món ăn này sẽ bị ẩn và không hiển thị trên thực đơn công khai.`,
      SAVE_FOOD: 'Xác nhận lưu thay đổi món ăn',
      SAVE_FOOD_DESC: 'Bạn có chắc chắn muốn lưu các thay đổi này cho món ăn không?',
    },
    PENDING_APPROVAL: 'CẦN DUYỆT',
    VIEW_MODE: {
      TABLE: 'Bảng',
      ROW: 'Dòng (1x1)',
      TITLE_TABLE: 'Xem bảng',
      TITLE_ROW: 'Xem dòng trực quan',
      TITLE_GRID: 'Xem khối trực quan',
    },
    LEGAL_DOCS: (docs: string) => `Tài liệu pháp lý: ${docs}`,
    REGISTER_DATE: (date: string) => `Đăng ký: ${date}`,
    JOIN_DATE: (date: string) => `Tham gia: ${date}`,
  },
  CUSTOMER: {
    GREETING: (name: string) => `Chào bạn, ${name}! 👋`,
    SUBTITLE: 'Hôm nay bạn muốn AI gợi ý món gì cho bữa trưa không?',
    FAVORITES: 'Yêu thích',
    AI_SUGGESTION: 'Gợi ý AI dành riêng cho bạn',
    AI_SUGGESTION_DESC: (food: string) => `Dựa trên lịch sử ăn uống, chúng tôi đề xuất món ${food} cho hôm nay.`,
    RECENT_FOODS: 'Gần đây bạn đã xem',
    RECENT_FOODS_DESC: (limit: number) => `${limit} món ăn được xem gần đây nhất của bạn`,
    RECENT_FOOD_SUGGEST: (days: number) => `AI gợi ý ${days} ngày trước`,
    PLACEHOLDER_FOOD: 'Phở Bò Gia Truyền',
    OLDER_HISTORY: 'Lịch sử trước đó',
    OLDER_HISTORY_DESC: (limit: number) => `Các món ăn bạn đã xem trong ${limit} lượt gần đây`,
    OLDER_FOODS_TITLE: 'Các món đã xem trước đó',
    PLACEHOLDER_FOOD_2: 'Bún chả Hà Nội',
    INFO: 'Thông tin cá nhân',
    UPDATE_PREFERENCES: 'Cập nhật sở thích AI',
    SUCCESS_UPDATE: 'Cập nhật thành công!',
    AI_HISTORY: 'Lịch sử đề xuất',
    AI_CONTEXT: 'Sở thích ăn uống (AI Context)',
    ONBOARDING_SUCCESS: 'Tuyệt vời!',
    ONBOARDING_PREPARING: 'Chờ mình một chút nhé ... !',
    STEP: (current: number, total: number) => `Bước ${current} / ${total}`,
    NO_HISTORY: 'Chưa có lịch sử món ăn đã xem',
    AI_LOGIN_REQUIRED: 'Vui lòng đăng nhập để sử dụng tính năng AI tư vấn món ngon bạn nhé! ✨',
    AI_CUSTOMER_ONLY: 'Tính năng AI tư vấn hiện chỉ dành cho khách hàng. Cảm ơn bạn!',
    QUESTION: 'Câu hỏi',
  },
  SETTINGS: {
    TITLE: 'Cài đặt tài khoản',
    SUBTITLE: 'Quản lý thông tin và bảo mật tài khoản của bạn',
    TABS: {
      PROFILE: 'Thông tin',
      SECURITY: 'Bảo mật',
      VERIFICATION: 'Xác minh',
    },
    SECURITY: {
      CURRENT_PASSWORD: 'Mật khẩu hiện tại',
      NEW_PASSWORD: 'Mật khẩu mới',
      CONFIRM_PASSWORD: 'Xác nhận mật khẩu mới',
      CHANGE_PASSWORD: 'Đổi mật khẩu',
      CHANGE_SUCCESS: 'Đổi mật khẩu thành công!',
      MISMATCH: 'Mật khẩu mới không trùng khớp.',
    },
    VERIFICATION: {
      TITLE: 'Xác minh tài khoản email của bạn',
      LABEL: 'Nhập email để xác minh',
      SUCCESS: 'Xác minh email thành công!',
      VERIFIED: 'Tài khoản đã được xác minh.',
      VERIFY_NOW: 'Xác minh ngay',
    },
    PROFILE: {
      TITLE: 'Hồ sơ của bạn',
      FULL_NAME: 'Họ và tên',
      NOT_UPDATED: 'Chưa cập nhật',
      EDIT_COVER: 'Chỉnh sửa ảnh bìa',
      FOLLOWERS: 'người theo dõi',
      FOLLOWING: 'đang theo dõi',
      DASHBOARD: 'Bảng điều khiển',
      FOLLOW: 'Theo dõi',
      UNFOLLOW: 'Bỏ theo dõi',
      SAVE_SUCCESS: 'Cập nhật thông tin thành công!',
      BIO_EMPTY: 'Người dùng này chưa có tiểu sử.',
      TABS: {
        POSTS: 'Bài viết',
        ABOUT: 'Giới thiệu',
        FRIENDS: 'Bạn bè',
        PHOTOS: 'Ảnh',
      },
      INTRO: {
        TITLE: 'Giới thiệu',
        WORK: (work: string) => `Làm việc tại ${work}`,
        LIVES: (city: string) => `Sống tại ${city}`,
        JOINED: (year: number) => `Tham gia từ ${year}`,
        EDIT_DETAILS: 'Chỉnh sửa chi tiết',
      },
      POSTS: {
        EMPTY_TITLE: 'Chưa có bài viết nào',
        EMPTY_DESC: 'Bắt đầu chia sẻ những trải nghiệm ẩm thực của bạn ngay hôm nay!',
        THINKING: (name: string) => `${name} ơi, bạn đang nghĩ gì thế?`,
      },
      EDIT_MODAL: {
        TITLE: 'Chỉnh sửa hồ sơ',
        SUCCESS: 'Cập nhật hồ sơ thành công!',
        NAME: 'Tên hiển thị',
        PHONE: 'Số điện thoại',
        AVATAR: 'URL Ảnh đại diện',
        COVER: 'URL Ảnh bìa',
        BIO: 'Tiểu sử',
        ADDRESS: 'Địa chỉ / Nơi sống',
        WORK: 'Nơi làm việc',
        CITY: 'Tỉnh/Thành phố',
        DISTRICT: 'Quận/Huyện',
        DISTRICT_PLACEHOLDER: 'Chọn Quận/Huyện',
        STREET: 'Địa chỉ chi tiết (Số nhà, tên đường...)',
        STREET_PLACEHOLDER: 'Ví dụ: 123 Đường Láng',
        MERCHANT_SYNC: 'Đồng bộ sang Cửa hàng (Merchant Sync)',
        SYNC_AVATAR: 'Đồng bộ avatar làm Logo quán',
        SYNC_COVER: 'Đồng bộ ảnh bìa sang trang quán',
      },
      MODALS: {
        FOLLOWERS_TITLE: 'Người theo dõi',
        FOLLOWERS_EMPTY: 'Chưa có người theo dõi nào',
        FOLLOWING_TITLE: 'Đang theo dõi',
        FOLLOWING_EMPTY: 'Chưa theo dõi ai',
        PRIVATE_LIST_ERROR: 'Danh sách này là riêng tư hoặc đã bị ẩn.',
      }
    },
    DANGER_ZONE: {
      TITLE: '⚠️ Vùng nguy hiểm (Danger Zone)',
      WARNING: 'CẢNH BÁO: Hành động này là vĩnh viễn và không thể đảo ngược. Khi bạn xác nhận xóa tài khoản: Toàn bộ dữ liệu của bạn bao gồm hồ sơ cá nhân, các bài viết, lượt thích, đánh giá, lịch sử gợi ý AI, thông tin chi nhánh nhà hàng (nếu có) sẽ bị xóa hoàn toàn khỏi hệ thống và KHÔNG THỂ KHÔI PHỤC.',
      BUTTON: 'Xóa tài khoản của tôi',
      MODAL_TITLE: 'Xác nhận xóa tài khoản?',
      MODAL_WARNING: 'Hành động này sẽ xóa vĩnh viễn toàn bộ dữ liệu của bạn. Đây là thao tác tuyệt đối không thể khôi phục lại!',
      PASSWORD_LABEL: 'Nhập mật khẩu của bạn để xác nhận:',
      PASSWORD_PLACEHOLDER: 'Mật khẩu tài khoản của bạn',
      CONFIRM_BUTTON: 'Xác nhận xóa',
      CANCEL_BUTTON: 'Hủy bỏ',
      TOAST_PASSWORD_REQUIRED: 'Vui lòng nhập mật khẩu để xác nhận.',
      TOAST_SUCCESS: 'Tài khoản của bạn đã được xóa vĩnh viễn khỏi hệ thống.',
      TOAST_ERROR: 'Mật khẩu không chính xác hoặc có lỗi xảy ra.'
    }
  },
  NAV: {
    HOME: 'Trang chủ',
    EXPLORE: 'Khám phá',
    OFFERS: 'Ưu đãi',
    ADMIN_PANEL: 'Panel Admin',
    RESTAURANT_PANEL: 'Quản lý quán',
    DASHBOARD: 'Dashboard cá nhân',
    SETTINGS: 'Cài đặt',
    FEATURES: 'Tính năng',
    SEARCH_PLACEHOLDER: 'Tính năng tìm kiếm chức năng đang phát triển!',
    USER_MENU: 'Menu người dùng',
  },
  FOOTER: {
    DESCRIPTION: 'Nền tảng gợi ý món ăn thông minh bằng AI, giúp bạn tìm thấy hương vị yêu thích mọi lúc mọi nơi.',
    QUICK_LINKS: 'Liên kết nhanh',
    FOLLOW_US: 'Theo dõi chúng tôi',
    RIGHTS: '© 2026 Food AI. Tất cả quyền được bảo lưu.',
    TERMS: 'Quy định',
    POLICY: 'Chính sách',
    CONTACT: 'Liên hệ',
  },
  HERO: {
    TITLE_START: 'Bạn muốn ăn gì',
    TITLE_HIGHLIGHT: 'hôm nay?',
    DESCRIPTION: 'Hãy kể cho AI nghe về tâm trạng, ngân sách hoặc sở thích của bạn. Chúng tôi sẽ gợi ý món ăn hoàn hảo nhất ngay gần bạn.',
    PLACEHOLDER_AUTH: 'Hãy kể cho AI nghe bạn muốn ăn gì...',
    PLACEHOLDER_GUEST: 'Đăng nhập để chat với AI tư vấn...',
    SEARCH_BUTTON: 'Tìm',
    AI_THINKING: 'Đang suy nghĩ món ngon cho bạn...',
    SUGGESTED_TITLE: 'Các món ăn gợi ý cho bạn:',
    FEATURES: {
      MOOD: 'Gợi ý theo tâm trạng',
      BUDGET: 'Phù hợp túi tiền',
      LOCATION: 'Quán ăn gần bạn',
    }
  },
  HOME: {
    NEARBY_TITLE: "Quán ngon Quanh đây",
    NEARBY_SUBTITLE: "Khám phá các món ăn hấp dẫn ngay tại vị trí của bạn",
    TODAY_TITLE: "Món ngon Nổi bật hôm nay",
    TODAY_SUBTITLE: "Những lựa chọn tuyệt vời được tuyển chọn trong ngày",
    WEEKLY_TITLE: "Món ngon Nổi bật tuần qua",
    WEEKLY_SUBTITLE: "Danh sách các món ăn được cộng đồng yêu thích nhất tuần này",
    RECOMMENDED_TITLE: "Món ăn Được gợi ý",
    RECOMMENDED_SUBTITLE: "Các món ngon được chính Admin lựa chọn và đề xuất cho bạn",
  },
  FORM: {
    FOOD_NAME: 'Tên món ăn',
    PRICE: 'Giá (VNĐ)',
    DESCRIPTION: 'Mô tả',
    IMAGE_URL: 'Hình ảnh (URL)',
    TAGS: 'Tags',
    EMAIL: 'Email',
    ADDRESS: 'Địa chỉ',
    PHONE: 'Số điện thoại',
    MAP_URL: 'Link Google Maps',
    LAT: 'Vĩ độ (Latitude)',
    LNG: 'Kinh độ (Longitude)',
    NOT_SET: 'Chưa cập nhật',
    NO_PREFERENCES: 'Bạn chưa cập nhật sở thích.',
    OPINION_PLACEHOLDER: 'Hãy nhập ý kiến của bạn tại đây...',
    EMAIL_REQUIRED: 'Vui lòng nhập email',
    EMAIL_INVALID: 'Email không đúng định dạng',
    PASSWORD_REQUIRED: 'Vui lòng nhập mật khẩu',
    PASSWORD_INVALID: 'Mật khẩu phải từ 8 ký tự, gồm cả chữ và số',
    CONFIRM_PASSWORD_MISMATCH: 'Mật khẩu nhập lại không trùng khớp',
    NAME_REQUIRED: 'Tên phải có ít nhất 2 ký tự',
    LEGAL_DOCS_REQUIRED: 'Vui lòng cung cấp thông tin giấy tờ pháp lý rõ ràng',
    PLACEHOLDERS: {
      NAME: 'Nguyễn Văn User',
      EMAIL: 'user123@gmail.com',
      PASSWORD: '••••••••',
      ADDRESS: 'Hà Nội, Việt Nam...',
      WORK: 'Công ty ABC...',
    }
  },
  EXPLORE: {
    TITLE: 'Khám phá theo danh mục',
    TITLE_TAG: (tag: string) => tag ? `Khám phá "${tag}"` : 'Khám phá quán ăn',
    FOUND_COUNT: (count: number) => `Tìm thấy ${count} quán ăn phù hợp`,
    SEARCH_IN_TAG: (tag: string) => tag ? `Tìm kiếm quán ăn trong mục ${tag}...` : 'Tìm kiếm quán ăn...',
    EMPTY_TITLE: 'Rất tiếc, không tìm thấy quán ăn nào!',
    EMPTY_DESC: 'Bạn hãy thử tìm kiếm với từ khóa khác nhé.',
    LOADING: 'Đang tải trang khám phá...',
    SEARCHING: 'Đang tìm kiếm quán ăn cho bạn...',
    TAG_PLACEHOLDER: 'Nhập 1 hoặc nhiều tag cách nhau bởi dấu phẩy bạn nhé!',
    SUGGESTED_TAGS: 'Gợi ý:',
    ALL_DISTRICTS: 'Tất cả Quận/Huyện',
  },
  FOOD: {
    DETAIL_TITLE: 'Mô tả món ăn',
    RESTAURANT_TITLE: 'Địa chỉ quán',
    VIEW_MAP: 'Xem vị trí trên bản đồ',
    NO_ADDRESS: 'Chưa cập nhật địa chỉ',
    STORE_PAGE: 'Trang Quán ăn',
    REVIEWS: 'Xem các bài đánh giá',
    ADD_FAVORITE: 'Thêm vào yêu thích',
    VIEW_DETAIL: 'Xem chi tiết',
    NO_DESCRIPTION: 'Không có mô tả',
    UNCATEGORIZED: 'Chưa phân loại',
    SYSTEM: 'Hệ thống',
  },
  UI_MESSAGES: {
    CATEGORY: {
      LOAD_ERROR: 'Lỗi khi tải danh mục',
      GROUP_NAME_REQUIRED: 'Vui lòng nhập tên nhóm',
      GROUP_UPDATE_SUCCESS: 'Đã cập nhật nhóm',
      GROUP_ADD_SUCCESS: 'Đã thêm nhóm mới',
      GROUP_DELETE_SUCCESS: 'Đã xóa nhóm',
      CATEGORY_NAME_REQUIRED: 'Vui lòng nhập tên phân loại',
      CATEGORY_UPDATE_SUCCESS: 'Đã cập nhật phân loại',
      CATEGORY_ADD_SUCCESS: 'Đã thêm phân loại mới',
      CATEGORY_DELETE_SUCCESS: 'Đã xóa phân loại',
      HAS_FOODS_ERROR: 'Có lỗi xảy ra (có thể danh mục đang có món ăn)',
    },
    RESTAURANT: {
      SELECT_REQUIRED: 'Vui lòng chọn cơ sở kinh doanh',
    },
    ADMIN: {
      UPDATE_FAILED: 'Cập nhật thất bại',
      UPDATE_SUCCESS: 'Cập nhật thành công',
      LOAD_ERROR: 'Lỗi lấy dữ liệu admin:',
    },
  },
  IMPORT_EXCEL: {
    MESSAGES: {
      INVALID_FILE_TYPE: 'Vui lòng chọn file Excel (.xlsx) hoặc CSV (.csv)',
      IMPORT_SUCCESS: (created: number, appended: number) => `Import thành công! Đã tạo ${created} nhà hàng, gộp ${appended} nhà hàng.`,
      IMPORT_ERROR_DEFAULT: 'Lỗi khi import file Excel',
      VALID_TYPES: [
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'application/vnd.ms-excel',
        'text/csv'
      ],
      TEMPLATE_HEADERS: 'Email,Password,Owner Name,Restaurant Name,Address,Latitude,Longitude,Restaurant Map URL,Food Name,Food Price,Food Desc,Food Image URL,Food Tags\n',
      TEMPLATE_SAMPLE: 'merchant@gmail.com,password123,Nguyen Van A,Pizza Ha Noi,Ha Noi,21.0285,105.8542,https://maps.app.goo.gl/example,Pizza Hai San,150000,Pizza ngon thuong hang,https://example.com/pizza.jpg,"ngon,hai san"\n',
      TEMPLATE_FILENAME: 'merchant_template.csv',
    },
    UI: {
      TITLE: 'Import dữ liệu hàng loạt',
      TEMPLATE_TITLE: 'Tải file mẫu (Template)',
      TEMPLATE_DESC: 'Sử dụng file CSV/Excel mẫu để nhập liệu chuẩn xác.',
      BTN_DOWNLOAD: 'Tải mẫu',
      DROPZONE_TITLE_FILE: 'Click hoặc kéo thả file vào đây',
      DROPZONE_SUBTITLE_FILE: 'Hỗ trợ định dạng .xlsx, .csv',
      BTN_REMOVE_FILE: 'Xóa file',
      BTN_CANCEL: 'Hủy',
      BTN_IMPORT: 'Import Ngay',
      BTN_LOADING: 'Đang xử lý...'
    }
  },
  ONBOARDING: {
    BRANCH_STEP_TITLE: 'Thiết lập vị trí & chi nhánh kinh doanh',
    BRANCH_STEP_DESC: 'Khai báo cơ sở (tên quán, địa chỉ chính xác, Google Maps) để AI tối ưu hóa hiển thị cho thực khách xung quanh.',
    ADD_BRANCH_BTN: 'Thêm Cơ Sở Khác (+ Chi Nhánh)',
    BACK_BTN: 'Quay Lại',
    COMPLETE_BTN: 'Hoàn Tất & Khởi Tạo',
    REQUIRED_BRANCH_FIELDS: (index: number) => `Vui lòng điền đầy đủ Tên và Địa chỉ của Cơ sở thứ ${index}.`,
    INVALID_COORDINATES: (index: number) => `Tọa độ (Kinh/Vĩ độ) của Cơ sở thứ ${index} bắt buộc phải là số.`,
    INVALID_LATITUDE: (index: number) => `Vĩ độ (Latitude) của Cơ sở thứ ${index} phải nằm trong khoảng từ -90 đến 90.`,
    INVALID_LONGITUDE: (index: number) => `Kinh độ (Longitude) của Cơ sở thứ ${index} phải nằm trong khoảng từ -180 đến 180.`,
    INVALID_HOURS_FORMAT: (index: number) => `Giờ hoạt động của Cơ sở thứ ${index} không đúng định dạng (Ví dụ đúng: 08:00 - 22:00).`,
    MIN_BRANCH_REQUIRED: 'Thương gia bắt buộc phải khai báo ít nhất 1 cơ sở chính.',
    ADD_BRANCH_SUCCESS: 'Đã thêm 1 chi nhánh trống. Vui lòng điền thông tin bên dưới.',
    REMOVE_BRANCH_SUCCESS: 'Đã xóa cơ sở khỏi danh sách.',
    STEP_INDICATOR: (current: number, total: number) => `Bước ${current} / ${total}`,
    FORM: {
      NAME_LABEL: 'Tên cơ sở / Chi nhánh',
      NAME_PLACEHOLDER: 'Ví dụ: FOOD AI - Chi Nhánh Hà Nội',
      ADDRESS_LABEL: 'Địa chỉ thực tế',
      ADDRESS_PLACEHOLDER: 'Ví dụ: 123 Nguyễn Trãi, Thanh Xuân, Hà Nội',
      LAT_LABEL: 'Vĩ độ (Latitude)',
      LAT_PLACEHOLDER: 'Ví dụ: 20.976094137561798',
      LNG_LABEL: 'Kinh độ (Longitude)',
      LNG_PLACEHOLDER: 'Ví dụ: 105.76295609115984',
      MAP_URL_LABEL: 'Link bản đồ Google Maps (Tùy chọn)',
      MAP_URL_PLACEHOLDER: 'Ví dụ: https://maps.google.com/...',
      HOURS_LABEL: 'Giờ hoạt động (Tùy chọn)',
      HOURS_PLACEHOLDER: 'Ví dụ: 09:00 - 21:00',
      BIO_LABEL: 'Khẩu hiệu / Giới thiệu ngắn',
      BIO_PLACEHOLDER: 'Ví dụ: Đồ ăn sạch, tốt cho sức khỏe...',
    },
    QUESTIONS: {
      CUSTOMER: {
        GOAL: {
          Q: 'Mục tiêu ăn uống của bạn là gì?',
          DESC: 'Để AI gợi ý những món ăn phù hợp với sức khỏe của bạn.',
          OPT: { WEIGHT_LOSS: 'Giảm cân', MUSCLE_GAIN: 'Tăng cơ', EAT_CLEAN: 'Ăn sạch (Eat Clean)', ENJOY: 'Thưởng thức' }
        },
        CUISINE: {
          Q: 'Bạn đặc biệt thích phong cách ẩm thực nào?',
          DESC: 'Chúng tôi sẽ ưu tiên hiển thị các quán có hương vị này.',
          OPT: { VIETNAMESE: 'Việt Nam', KOREAN: 'Hàn Quốc', JAPANESE: 'Nhật Bản', WESTERN: 'Âu Mỹ' }
        },
        BUDGET: {
          Q: 'Ngân sách cho một bữa ăn của bạn?',
          DESC: 'Gợi ý các quán ăn phù hợp với túi tiền của bạn.',
          OPT: { UNDER_100K: 'Dưới 100k', '100K_200K': '100k - 200k', '200K_400K': '200k - 400k', OVER_400K: 'Trên 400k' }
        },
        ALLERGIES: {
          Q: 'Bạn có bị dị ứng với gì không?',
          DESC: 'An toàn của bạn là trên hết. Hãy cho AI biết nhé!',
          OPT: { SEAFOOD: 'Hải sản', PEANUTS: 'Đậu phộng', DAIRY: 'Sữa/Phô mai', NONE: 'Không dị ứng' }
        }
      },
      RESTAURANT: {
        STYLE: {
          Q: 'Phong cách quán của bạn là gì?',
          DESC: 'Giúp khách hàng hình dung về không gian quán.',
          OPT: { LUXURY: 'Sang trọng', CASUAL: 'Bình dân', STREET: 'Vỉa hè/Đường phố', TAKEAWAY: 'Bán mang về' }
        },
        FLAVOR: {
          Q: 'Hương vị chủ đạo của quán là gì?',
          DESC: 'Khách hàng thường tìm kiếm theo hương vị ưa thích.',
          OPT: { SPICY: 'Cay nồng', SWEET: 'Ngọt ngào', SAVORY: 'Đậm đà', LIGHT: 'Thanh đạm' }
        },
        TARGET: {
          Q: 'Đối tượng khách hàng bạn muốn tiếp cận?',
          DESC: 'AI sẽ ưu tiên hiển thị quán cho tệp khách này.',
          OPT: { STUDENTS: 'Sinh viên', OFFICE: 'Dân văn phòng', FAMILY: 'Gia đình', TOURISTS: 'Khách du lịch' }
        }
      }
    }
  },
  CATEGORIES: {
    NAMES: {
      WATER: 'Món nước',
      RICE: 'Cơm / Xôi',
      SNACK: 'Ăn vặt',
      DESSERT: 'Tráng miệng',
      CASUAL: 'Bình dân',
      LUXURY: 'Cao cấp'
    },
    TAGS: {
      TRADITIONAL: 'truyền thống',
      FASTFOOD: 'ăn nhanh',
      FRIED: 'đồ chiên',
      ALONE: 'một mình',
      GROUP: 'nhiều người',
      OFFICE: 'văn phòng',
      SPICY: 'cay',
      HEALTHY: 'healthy'
    }
  }
};
