export const LABELS = {
  COMMON: {
    SAVE: 'Lưu thay đổi',
    CANCEL: 'Hủy',
    DELETE: 'Xóa',
    EDIT: 'Chỉnh sửa',
    APPROVE: 'Phê duyệt',
    REJECT: 'Từ chối',
    LOGOUT: 'Đăng xuất',
    BACK_HOME: 'Quay lại trang chủ',
    LOADING: 'Đang tải...',
    SUCCESS: 'Thành công',
    ERROR: 'Lỗi',
    NEXT: 'Tiếp theo',
    BACK: 'Quay lại',
    SEARCH: 'Tìm kiếm...',
    OTHER: 'Khác...',
  },
  AUTH: {
    LOGIN: 'Đăng nhập',
    REGISTER: 'Đăng ký',
    ADMIN: 'Quản trị viên',
    RESTAURANT_ROLE: 'Chủ nhà hàng',
    PROFILE: 'Hồ sơ cá nhân',
    LOGIN_TITLE: 'Đăng nhập',
    LOGIN_SUBTITLE: 'Chào mừng bạn quay trở lại với FoodAI',
    PASSWORD: 'Mật khẩu',
    OR_LOGIN_WITH: 'Hoặc đăng nhập bằng',
    SOCIAL_GOOGLE: 'Google',
    SOCIAL_FACEBOOK: 'Facebook',
    FORGOT_PASSWORD: 'Quên mật khẩu?',
    NO_ACCOUNT: 'Chưa có tài khoản?',
    REGISTER_NOW: 'Đăng ký ngay',
    REGISTER_TITLE: 'Tạo tài khoản',
    REGISTER_SUBTITLE: 'Bắt đầu hành trình khám phá ẩm thực thông minh',
    WHO_ARE_YOU: 'Bạn là ai?',
    CUSTOMER: 'Khách hàng',
    RESTAURANT: 'Nhà hàng',
    CONFIRM_PASSWORD: 'Xác nhận mật khẩu',
    LEGAL_DOCS: 'Giấy tờ pháp lý / Thông tin xác thực',
    LEGAL_DOCS_PLACEHOLDER: 'Số giấy phép kinh doanh hoặc link ảnh giấy tờ...',
    AGREE_TERMS: 'Tôi đồng ý với các điều khoản bảo mật và chính sách sử dụng.',
    ALREADY_HAVE_ACCOUNT: 'Đã có tài khoản?',
    VERIFY_ACCOUNT: 'Xác minh tài khoản',
    LOGIN_GO: 'Đi tới Đăng nhập',
    REGISTER_SUCCESS_PENDING: 'Đăng ký thành công! Đang chờ Admin phê duyệt.',
    REGISTER_SUCCESS_VERIFY: 'Đăng ký thành công! Vui lòng xác minh tài khoản.',
    LOGIN_REQUIRED: 'Vui lòng đăng nhập để thực hiện chức năng này!',
  },
  RESTAURANT: {
    DASHBOARD_TITLE: 'Chào mừng quay trở lại!',
    MENU_MANAGEMENT: 'Quản lý thực đơn',
    AI_HISTORY: 'Lịch sử đề xuất AI',
    SUBTITLE: 'Cửa hàng của bạn đang hoạt động rất tốt ✨',
    MERCHANT_HUB: 'Merchant Hub',
    STATUS: 'Trạng thái',
    ADD_FOOD: 'Đăng món mới',
    RECENT_ACTIVITY: 'Hoạt động gần đây',
    VIEW_INSIGHT: 'Xem Insight chi tiết',
    NO_FOOD: 'Chưa có món ăn nào.',
    SAVE_SUCCESS_EDIT: 'Đã lưu! Chờ Admin duyệt.',
    SAVE_SUCCESS_ADD: 'Đã đăng! Chờ Admin duyệt.',
    AI_SUGGESTION_TITLE: 'Gợi ý AI cho quán',
    AI_SUGGESTION_DESC: 'Món "Phở cuốn" đang là xu hướng. Bạn có muốn thêm vào thực đơn?',
    TABS: {
      OVERVIEW: 'Tổng quan',
      MENU: 'Thực đơn của tôi',
      HISTORY: 'Lịch sử đề xuất',
    },
    TABLE: {
      FOOD: 'Món ăn',
      STATUS: 'Trạng thái',
      ACTION: 'Thao tác',
      FEATURE: 'Nổi bật',
      RECOMMEND: 'Đề xuất',
    },
    MODAL: {
      ADD_TITLE: 'Đăng món mới',
      EDIT_TITLE: 'Chỉnh sửa món ăn',
      SUBMIT_ADD: 'Đăng món ngay',
      SUBMIT_EDIT: 'Lưu thay đổi',
    }
  },
  ADMIN: {
    PANEL_TITLE: 'Admin Panel',
    APPROVE_MERCHANTS: 'Duyệt Thương gia',
    MANAGE_MERCHANTS: 'Quản lý Thương gia',
    MANAGE_CUSTOMERS: 'Quản lý Thực khách',
    MANAGE_MENU: 'Quản lý Thực đơn',
    SYSTEM_FOOD: 'Món ăn hệ thống',
    MERCHANT_FOOD: 'Món ăn đối tác',
    SAVE_SUCCESS: 'Cập nhật thành công!',
    DELETE_SUCCESS: 'Xóa thành công!',
    MODAL: {
      EDIT_TITLE: 'Chỉnh sửa món ăn',
      FOOD_NAME: 'Tên món',
      PRICE: 'Giá (VNĐ)',
      TAGS: 'Tags',
      IMAGE_URL: 'URL Hình ảnh',
      DESCRIPTION: 'Mô tả',
    },
    TABLE: {
      NAME: 'Tên tài khoản',
      FOOD_NAME: 'Món ăn',
      SOURCE: 'Nguồn',
      EMAIL: 'Email',
      PRICE: 'Giá',
      DATE: 'Ngày đăng ký',
      ACTION: 'Thao tác',
      EMPTY: 'Không tìm thấy dữ liệu nào.',
    },
    CONFIRM: {
      DELETE_USER: 'Bạn có chắc chắn muốn xóa tài khoản này?',
      DELETE_FOOD: 'Bạn có chắc chắn muốn xóa món ăn này?',
    }
  },
  CUSTOMER: {
    GREETING: (name: string) => `Chào bạn, ${name}! 👋`,
    SUBTITLE: 'Hôm nay bạn muốn AI gợi ý món gì cho bữa trưa không?',
    FAVORITES: 'Yêu thích',
    AI_SUGGESTION: 'Gợi ý AI dành riêng cho bạn',
    AI_SUGGESTION_DESC: (food: string) => `Dựa trên lịch sử ăn uống, chúng tôi đề xuất món ${food} cho hôm nay.`,
    RECENT_FOODS: 'Gần đây bạn đã xem',
    RECENT_FOOD_SUGGEST: (days: number) => `AI gợi ý ${days} ngày trước`,
    PLACEHOLDER_FOOD: 'Phở Bò Gia Truyền',
    PLACEHOLDER_FOOD_2: 'Bún chả Hà Nội',
    INFO: 'Thông tin cá nhân',
    UPDATE_PREFERENCES: 'Cập nhật sở thích AI',
    SUCCESS_UPDATE: 'Cập nhật thành công!',
    AI_HISTORY: 'Lịch sử đề xuất',
    AI_CONTEXT: 'Sở thích ăn uống (AI Context)',
    ONBOARDING_SUCCESS: 'Tuyệt vời!',
    ONBOARDING_PREPARING: 'AI đã học được những sở thích đầu tiên của bạn. Đang chuẩn bị bàn ăn của bạn...',
    STEP: (current: number, total: number) => `Bước ${current} / ${total}`,
  },
  SETTINGS: {
    TITLE: 'Cài đặt tài khoản',
    SUBTITLE: 'Quản lý thông tin và bảo mật tài khoản của bạn',
    TABS: {
      PROFILE: 'Thông tin',
      SECURITY: 'Bảo mật',
      VERIFICATION: 'Xác minh',
    },
    SECURITY: {
      CURRENT_PASSWORD: 'Mật khẩu hiện tại',
      NEW_PASSWORD: 'Mật khẩu mới',
      CONFIRM_PASSWORD: 'Xác nhận mật khẩu mới',
      CHANGE_PASSWORD: 'Đổi mật khẩu',
      CHANGE_SUCCESS: 'Đổi mật khẩu thành công!',
      MISMATCH: 'Mật khẩu mới không trùng khớp.',
    },
    VERIFICATION: {
      TITLE: 'Xác minh tài khoản email của bạn',
      LABEL: 'Nhập email để xác minh',
      SUCCESS: 'Xác minh email thành công!',
      VERIFIED: 'Tài khoản đã được xác minh.',
      VERIFY_NOW: 'Xác minh ngay',
    },
    PROFILE: {
      TITLE: 'Hồ sơ của bạn',
      FULL_NAME: 'Họ và tên',
      NOT_UPDATED: 'Chưa cập nhật',
      EDIT_COVER: 'Chỉnh sửa ảnh bìa',
      FOLLOWERS: 'người theo dõi',
      FOLLOWING: 'đang theo dõi',
      DASHBOARD: 'Bảng điều khiển',
      FOLLOW: 'Theo dõi',
      UNFOLLOW: 'Bỏ theo dõi',
      SAVE_SUCCESS: 'Cập nhật thông tin thành công!',
      BIO_EMPTY: 'Người dùng này chưa có tiểu sử.',
      TABS: {
        POSTS: 'Bài viết',
        ABOUT: 'Giới thiệu',
        FRIENDS: 'Bạn bè',
        PHOTOS: 'Ảnh',
      },
      INTRO: {
        TITLE: 'Giới thiệu',
        WORK: (work: string) => `Làm việc tại ${work}`,
        LIVES: (city: string) => `Sống tại ${city}`,
        JOINED: (year: number) => `Tham gia từ ${year}`,
        EDIT_DETAILS: 'Chỉnh sửa chi tiết',
      },
      POSTS: {
        EMPTY_TITLE: 'Chưa có bài viết nào',
        EMPTY_DESC: 'Bắt đầu chia sẻ những trải nghiệm ẩm thực của bạn ngay hôm nay!',
        THINKING: (name: string) => `${name} ơi, bạn đang nghĩ gì thế?`,
      },
      EDIT_MODAL: {
        TITLE: 'Chỉnh sửa hồ sơ',
        SUCCESS: 'Cập nhật hồ sơ thành công!',
        NAME: 'Tên hiển thị',
        PHONE: 'Số điện thoại',
        AVATAR: 'URL Ảnh đại diện',
        COVER: 'URL Ảnh bìa',
        BIO: 'Tiểu sử',
        ADDRESS: 'Địa chỉ / Nơi sống',
        WORK: 'Nơi làm việc',
      }
    }
  },
  NAV: {
    HOME: 'Trang chủ',
    EXPLORE: 'Khám phá',
    OFFERS: 'Ưu đãi',
    ADMIN_PANEL: 'Panel Admin',
    RESTAURANT_PANEL: 'Quản lý quán',
    DASHBOARD: 'Dashboard cá nhân',
    SETTINGS: 'Cài đặt',
    FEATURES: 'Tính năng',
    SEARCH_PLACEHOLDER: 'Tính năng tìm kiếm chức năng đang phát triển!',
  },
  FOOTER: {
    DESCRIPTION: 'Nền tảng gợi ý món ăn thông minh bằng AI, giúp bạn tìm thấy hương vị yêu thích mọi lúc mọi nơi.',
    QUICK_LINKS: 'Liên kết nhanh',
    FOLLOW_US: 'Theo dõi chúng tôi',
    RIGHTS: '© 2026 Food AI. Tất cả quyền được bảo lưu.',
    TERMS: 'Quy định',
    POLICY: 'Chính sách',
    CONTACT: 'Liên hệ',
  },
  HERO: {
    TITLE_START: 'Bạn muốn ăn gì',
    TITLE_HIGHLIGHT: 'hôm nay?',
    DESCRIPTION: 'Hãy kể cho AI nghe về tâm trạng, ngân sách hoặc sở thích của bạn. Chúng tôi sẽ gợi ý món ăn hoàn hảo nhất ngay gần bạn.',
    PLACEHOLDER_AUTH: 'Hãy kể cho AI nghe bạn muốn ăn gì...',
    PLACEHOLDER_GUEST: 'Đăng nhập để chat với AI tư vấn...',
    SEARCH_BUTTON: 'Tìm',
    AI_THINKING: 'Đang suy nghĩ món ngon cho bạn...',
    SUGGESTED_TITLE: 'Các món ăn gợi ý cho bạn:',
    FEATURES: {
      MOOD: 'Gợi ý theo tâm trạng',
      BUDGET: 'Phù hợp túi tiền',
      LOCATION: 'Quán ăn gần bạn',
    }
  },
  HOME: {
    NEARBY_TITLE: "Món ngon Quanh đây",
    NEARBY_SUBTITLE: "Khám phá các món ăn hấp dẫn ngay tại vị trí của bạn",
    TODAY_TITLE: "Món ngon Nổi bật hôm nay",
    TODAY_SUBTITLE: "Những lựa chọn tuyệt vời được tuyển chọn trong ngày",
    WEEKLY_TITLE: "Món ngon Nổi bật tuần qua",
    WEEKLY_SUBTITLE: "Danh sách các món ăn được cộng đồng yêu thích nhất tuần này",
    RECOMMENDED_TITLE: "Món ăn Được gợi ý",
    RECOMMENDED_SUBTITLE: "Các món ngon được chính Admin lựa chọn và đề xuất cho bạn",
  },
  FORM: {
    FOOD_NAME: 'Tên món ăn',
    PRICE: 'Giá (VNĐ)',
    DESCRIPTION: 'Mô tả',
    IMAGE_URL: 'Hình ảnh (URL)',
    TAGS: 'Tags',
    EMAIL: 'Email',
    ADDRESS: 'Địa chỉ',
    PHONE: 'Số điện thoại',
    MAP_URL: 'Link Google Maps',
    LAT: 'Vĩ độ (Latitude)',
    LNG: 'Kinh độ (Longitude)',
    NOT_SET: 'Chưa cập nhật',
    NO_PREFERENCES: 'Bạn chưa cập nhật sở thích.',
    EMAIL_REQUIRED: 'Vui lòng nhập email',
    EMAIL_INVALID: 'Email không đúng định dạng',
    PASSWORD_REQUIRED: 'Vui lòng nhập mật khẩu',
    PASSWORD_INVALID: 'Mật khẩu phải từ 8 ký tự, gồm cả chữ và số',
    CONFIRM_PASSWORD_MISMATCH: 'Mật khẩu nhập lại không trùng khớp',
    NAME_REQUIRED: 'Tên phải có ít nhất 2 ký tự',
    LEGAL_DOCS_REQUIRED: 'Vui lòng cung cấp thông tin giấy tờ pháp lý rõ ràng',
    PLACEHOLDERS: {
      NAME: 'Nguyễn Văn User',
      EMAIL: 'user123@gmail.com',
      PASSWORD: '••••••••',
      ADDRESS: 'Hà Nội, Việt Nam...',
      WORK: 'Công ty ABC...',
    }
  },
  EXPLORE: {
    TITLE: 'Khám phá theo danh mục',
    TITLE_TAG: (tag: string) => `Khám phá "${tag}"`,
    FOUND_COUNT: (count: number) => `Tìm thấy ${count} món ngon trong danh mục này`,
    SEARCH_IN_TAG: (tag: string) => `Tìm kiếm trong mục ${tag}...`,
    EMPTY_TITLE: 'Rất tiếc, không tìm thấy món nào!',
    EMPTY_DESC: 'Bạn hãy thử tìm kiếm với từ khóa khác nhé.',
    LOADING: 'Đang tải trang khám phá...',
    SEARCHING: 'Đang tìm món ngon cho bạn...',
    TAG_PLACEHOLDER: 'Nhập 1 hoặc nhiều tag cách nhau bởi dấu phẩy bạn nhé!',
    SUGGESTED_TAGS: 'Gợi ý:',
  },
  FOOD: {
    DETAIL_TITLE: 'Mô tả món ăn',
    RESTAURANT_TITLE: 'Địa chỉ quán',
    VIEW_MAP: 'Xem vị trí trên bản đồ',
    NO_ADDRESS: 'Chưa cập nhật địa chỉ',
    STORE_PAGE: 'Trang Quán ăn',
    REVIEWS: 'Xem các bài đánh giá',
    ADD_FAVORITE: 'Thêm vào yêu thích',
    VIEW_DETAIL: 'Xem chi tiết',
    SYSTEM: 'Hệ thống',
  },
};
