// Mục đích: Khai báo đối tượng hằng số LABELS_EN chứa toàn bộ văn bản hiển thị (UI text) tiếng Anh.
// Các file khác hay file này có ý nghĩa như nào: Cung cấp bản dịch tiếng Anh để labels.ts truy xuất động dựa trên cấu hình ngôn ngữ.
// Các chức năng đặc biệt: Định nghĩa bản dịch cho toàn bộ giao diện (Common, Navigation, Settings, Restaurant, AI Chat...).
// Kiến thức, Design Pattern, nguyên tắc (SOLID, OOP...) đang được áp dụng trong file: Constant pattern, Namespace grouping, Localization/i18n.
// Các biến, hàm đặc biệt trong file: LABELS_EN.
export const LABELS_EN = {
  COMMON: {
    SAVE: 'Save changes',
    CANCEL: 'Cancel',
    DELETE: 'Delete',
    EDIT: 'Edit',
    APPROVE: 'Approve',
    REJECT: 'Reject',
    LOGOUT: 'Logout',
    BACK_HOME: 'Back to home',
    LOADING: 'Loading...',
    SUCCESS: 'Success',
    ERROR: 'Error',
    NEXT: 'Next',
    BACK: 'Back',
    SEARCH: 'Search...',
    OTHER: 'Other...',
    APP_TITLE: 'FOOD AI - Daily Delicious Dishes',
    PROCESSING: 'Processing...',
    DEVELOPING: 'Feature under development',
    DEVELOPING_DESC: 'We are developing this feature. Please come back later! ✨',
    SEE_MORE: 'See more',
    SEE_LESS: 'Show less',
    UNNAMED: 'Unnamed',
    SCROLL_LEFT: 'Scroll left',
    SCROLL_RIGHT: 'Scroll right',
    TOGGLE_THEME: 'Toggle light/dark theme',
    CLOSE: 'Close',
    AI_BUSY: 'Sorry, AI is busy. Please try again later!',
    ACTION: 'Actions',
    IMAGE: 'Image',
    UNKNOWN: 'Unknown',
    BRAND_NAME: 'Food AI',
    BRAND_LOGO_ALT: 'Food AI Logo',
    AI_ASSISTANT_NAME: 'Food AI Assistant',
    USER: 'User',
    STORE: 'Store',
    PAGINATION: {
      PREVIOUS: 'Previous page',
      NEXT: 'Next page',
      JUMP_TO_PAGE: 'Jump to page',
    },
    EMAIL_UNVERIFIED_BANNER: 'Your email is not verified. Verify now to unlock all features (Forgot Password, account security...).',
    VERIFY_NOW: 'Verify now →',
  },
  AUTH: {
    LOGIN: 'Login',
    REGISTER: 'Register',
    ADMIN: 'Administrator',
    RESTAURANT_ROLE: 'Restaurant Owner',
    PROFILE: 'Personal Profile',
    LOGIN_TITLE: 'Login',
    LOGIN_SUBTITLE: 'Welcome back to FoodAI',
    PASSWORD: 'Password',
    OR_LOGIN_WITH: 'Or login with',
    SOCIAL_GOOGLE: 'Google',
    SOCIAL_FACEBOOK: 'Facebook',
    FORGOT_PASSWORD: 'Forgot password?',
    NO_ACCOUNT: 'Don\'t have an account?',
    REGISTER_NOW: 'Register now',
    REGISTER_TITLE: 'Create Account',
    REGISTER_SUBTITLE: 'Start your smart culinary journey',
    WHO_ARE_YOU: 'Who are you?',
    CUSTOMER: 'Customer',
    RESTAURANT: 'Restaurant',
    CONFIRM_PASSWORD: 'Confirm Password',
    LEGAL_DOCS: 'Legal Documents / Verification Info',
    LEGAL_DOCS_PLACEHOLDER: 'Business license number or document image link...',
    AGREE_TERMS: 'I agree to the privacy terms and terms of use.',
    AGREE_TERMS_PREFIX: 'I agree to the ',
    AGREE_TERMS_LINK: 'Terms of Service',
    AGREE_TERMS_AND: ' and ',
    AGREE_POLICY_LINK: 'Privacy Policy',
    ALREADY_HAVE_ACCOUNT: 'Already have an account?',
    VERIFY_ACCOUNT: 'Verify Account',
    LOGIN_GO: 'Go to Login',
    REGISTER_SUCCESS_PENDING: 'Registration successful! Pending Admin approval.',
    REGISTER_SUCCESS_VERIFY: 'Registration successful! Please verify your account.',
    LOGIN_REQUIRED: 'Please login to perform this function!',
    FORGOT_PASSWORD_TITLE: 'Forgot Password?',
    FORGOT_PASSWORD_SUBTITLE: 'Don\'t worry! Enter your registered email address to receive a password reset OTP.',
    EMAIL_LABEL: 'Email Address',
    EMAIL_PLACEHOLDER: 'your-email@gmail.com',
    SEND_OTP: 'Send Reset OTP',
    BACK_TO_LOGIN: 'Back to Login',
    ENTER_EMAIL_ERROR: 'Please enter your email address',
    SEND_OTP_SUCCESS: 'Password reset OTP has been sent to your email.',
    SEND_OTP_SUCCESS_TOAST: 'Password reset OTP has been sent!',
    SEND_OTP_ERROR: 'An error occurred. Please check your email.',
    VERIFY_EMAIL_TITLE: 'Account Verification',
    VERIFY_EMAIL_SUBTITLE: (email: string) => `A 6-digit OTP has been sent to: ${email}`,
    VERIFY_OTP_REQUIRED: 'Please enter the full 6-digit OTP',
    VERIFY_SUCCESS_PENDING: 'Email verified successfully! Account is pending approval.',
    VERIFY_SUCCESS: 'Account verified successfully!',
    VERIFY_SUCCESS_TOAST: 'Account verified successfully! Logging you in...',
    VERIFY_OTP_INVALID: 'Invalid or expired OTP code.',
    RESEND_OTP_SUCCESS: 'New OTP code has been sent.',
    RESEND_OTP_ERROR: 'Unable to resend code. Please try again later.',
    OTP_INPUT_LABEL: 'OTP Verification Code',
    CONFIRM_OTP: 'Confirm OTP',
    NO_OTP_RECEIVED: 'Didn\'t receive code?',
    RESEND_OTP_COOLDOWN: (sec: number) => `Resend (${sec}s)`,
    RESEND_OTP_BTN: 'Resend OTP',
    LOADING_VERIFY: 'Loading verification details...',
    RESET_PASSWORD_TITLE: 'Reset Password',
    RESET_PASSWORD_SUBTITLE: (email: string) => `Please enter the OTP sent to: ${email}`,
    PASSWORD_MIN_LENGTH: 'New password must be at least 8 characters long',
    PASSWORD_MISMATCH: 'Confirm password does not match',
    RESET_SUCCESS: 'Password reset successfully!',
    RESET_SUCCESS_TOAST: 'Password reset successfully!',
    RESET_ERROR: 'Invalid OTP code or an error occurred.',
    NEW_PASSWORD_LABEL: 'New Password',
    NEW_PASSWORD_PLACEHOLDER: 'Minimum 8 characters',
    CONFIRM_NEW_PASSWORD_LABEL: 'Confirm New Password',
    YOUR_EMAIL: 'your email',
    PROCEED_VERIFY: 'Proceed to verification',
    LOGIN_SUCCESS_UNVERIFIED: 'Login successful! Your email is not verified — please verify to unlock all features (Forgot Password, account security...)',
  },
  RESTAURANT: {
    DASHBOARD_TITLE: 'Welcome back!',
    MENU_MANAGEMENT: 'Menu Management',
    AI_HISTORY: 'AI Suggestion History',
    SUBTITLE: 'Your store is doing very well ✨',
    MERCHANT_HUB: 'Merchant Hub',
    STATUS: 'Status',
    ADD_FOOD: 'Add New Food',
    RECENT_ACTIVITY: 'Recent Activity',
    DELETE_BRANCH: 'Delete Branch',
    BRANCH_NUMBER: (num: number) => `📍 Branch ${num}`,
    VIEW_INSIGHT: 'View detailed insights',
    VIEW_AS_GUEST: 'View as guest',
    NO_FOOD: 'No food items yet.',
    SAVE_SUCCESS_EDIT: 'Saved! Pending Admin approval.',
    SAVE_SUCCESS_ADD: 'Posted! Pending Admin approval.',
    AI_SUGGESTION_TITLE: 'AI Suggestions for Store',
    AI_SUGGESTION_DESC: 'Dish "Pho Cuon" is trending. Would you like to add it to the menu?',
    STATUS_OPEN: 'Open',
    STATUS_CLOSED: 'Closed temporarily',
    STATUS_TOOLTIP: 'When closed temporarily, all your food items will be hidden from search results and recommendations.',
    SETTINGS_TITLE: 'Store Settings',
    OPERATING_HOURS: 'Operating Hours',
    CONTACT_PHONE: 'Contact Phone',
    SAVE: 'Save',
    STATUS_OPEN_SUCCESS: 'Store is now open for customers.',
    STATUS_CLOSE_SUCCESS: 'Store has been closed temporarily.',
    STATUS_UPDATE_ERROR: 'Unable to update store status.',
    DELETE_FOOD_CONFIRM: 'Are you sure you want to delete this food item from the menu? It will be hidden and no longer visible to guests.',
    DELETE_FOOD_CONFIRM_TITLE: 'Confirm Food Deletion',
    HOURS_UPDATE_SUCCESS: 'Operating hours updated successfully.',
    HOURS_UPDATE_ERROR: 'Unable to update operating hours.',
    CLOSED_WARNING_TITLE: 'Store is temporarily closed',
    CLOSED_BY_MERCHANT: 'Restaurant has temporarily closed.',
    CLOSED_OUTSIDE_HOURS: (hours: string) => `Outside operating hours (${hours}).`,
    NOT_SET: 'not set',
    OPERATING_HOURS_LABEL: 'Operating Hours',
    HOURS_PLACEHOLDER: 'E.g., 08:00 - 22:00',
    HOURS_FORMAT_ERROR: 'Operating hours format is invalid (Correct e.g.: 08:00 - 22:00).',
    EDIT_STORE: 'store',
    TABS: {
      OVERVIEW: 'Overview',
      CATEGORIES: 'Categories',
      MENU: 'My Menu',
      HISTORY: 'Suggestion History',
    },
    EDIT_MODAL: {
      LIVE_PREVIEW: 'Live Card Preview',
      VERIFIED: 'Verified',
      BIO_PLACEHOLDER: 'Short introduction of the restaurant...',
      NOT_OPENED: 'Not opened',
      TIP: 'Changes to Logo and Cover images will update immediately on the Explore grid and public profile.',
      SUBTITLE: 'Customize brand details and contact info of the store',
      TAB_INFO: 'Basic Info',
      TAB_IMAGES: 'Brand Images',
      TAB_CONTACT: 'Contact & Operation',
      NAME_LABEL: 'Restaurant Name',
      NAME_PLACEHOLDER: 'E.g., FOOD AI - Dong Da Branch',
      NAME_REQUIRED: 'Please enter restaurant name',
      BIO_LABEL: 'Short bio',
      BIO_INPUT_PLACEHOLDER: 'Clean food, pure nature...',
      DESC_LABEL: 'Detailed Description',
      DESC_PLACEHOLDER: 'Describe your menu and style in detail...',
      LOGO_LABEL: 'Logo URL',
      LOGO_PLACEHOLDER: 'https://example.com/logo.png',
      SYNC_AVATAR: 'Synchronize this logo as your personal avatar',
      COVER_LABEL: 'Cover Image URL',
      COVER_PLACEHOLDER: 'https://example.com/cover.png',
      SYNC_COVER: 'Synchronize this cover image as your personal cover image',
      CITY_LABEL: 'City / Province',
      DISTRICT_LABEL: 'District',
      ADDRESS_LABEL: 'Detailed Address',
      ADDRESS_PLACEHOLDER: 'E.g., 123 Duong Lang, Lang Thuong',
      HOURS_LABEL: 'Operating hours (HH:MM - HH:MM)',
      PHONE_LABEL: 'Contact Phone Number',
      PHONE_PLACEHOLDER: '0987654321',
      EMAIL_LABEL: 'Contact Email',
      EMAIL_PLACEHOLDER: 'contact@quanphobac.com',
      MAPS_LABEL: 'Google Maps Link',
      MAPS_PLACEHOLDER: 'https://maps.app.goo.gl/...',
      CANCEL: 'Cancel',
      SUBMIT: 'Save Settings',
      SAVING: 'Saving...',
      SAVE_ERROR: 'Error updating restaurant details',
      CONFIRM_TITLE: 'Confirm Settings Save',
      CONFIRM_DESC: 'Are you sure you want to save these changes for the store?',
      CLOSE_SETTINGS: 'Close store settings',
    },
    CARD_LABELS: {
      DEFAULT_BIO: 'We are pleased to serve you premium delicious dishes.',
      FOLLOWERS_SUFFIX: 'followers',
      FOODS_SUFFIX: 'food items',
      DEFAULT_LOCATION: 'Vietnam',
      DEFAULT_CATEGORY: 'Restaurant',
    },
    TABLE: {
      FOOD: 'Food Item',
      STATUS: 'Status',
      ACTION: 'Action',
      FEATURE: 'Featured',
      RECOMMEND: 'Recommended',
    },
    MODAL: {
      ADD_TITLE: 'Post New Food',
      EDIT_TITLE: 'Edit Food Item',
      SUBMIT_ADD: 'Post Food Now',
      SUBMIT_EDIT: 'Save Changes',
      BRANCH_LABEL: 'Business Branch',
      BRANCH_PLACEHOLDER: '-- Select Branch --',
      CATEGORY_LABEL: 'Food Category (Optional)',
      CATEGORY_PLACEHOLDER: '-- Uncategorized --',
      AUTO_FILL_BRANCH: '(Auto-filled by branch)',
      AUTO_FILL_LAT_LNG: '(Auto-filled)',
    },
    PUBLIC_PROFILE: {
      NOT_FOUND: 'Restaurant not found',
      NOT_FOUND_DESC: 'Invalid link or the business has stopped operating.',
      MENU_TAB: 'Food Menu',
      INFO_TAB: 'Restaurant Info',
      EMPTY_MENU: 'Menu is empty',
      EMPTY_MENU_DESC: 'The restaurant has not published any approved food items yet.',
      DETAIL_INFO: 'Detailed Information',
      NO_HOURS: 'Operating hours not configured',
      NO_PHONE: 'Phone number not configured',
      CONTACT_EMAIL: 'Contact Email',
      MAP_TITLE: 'Google Maps Location',
      MAP_OPEN: 'Open location on Google Maps',
      BIO_TITLE: 'About Us',
      BIO_EMPTY: 'The restaurant has not updated its introduction details.',
      FOLLOWERS_TITLE: 'Current Followers',
      FOLLOWERS_EMPTY: 'No followers yet.',
      FOLLOWING_TITLE: 'Following restaurants',
      FOLLOWING_EMPTY: 'Not following any restaurants.',
      LOGIN_REQUIRED: 'Please login to perform this action',
      FOLLOWERS_PRIVATE: 'Follower list is hidden by owner',
      FOLLOWING_PRIVATE: 'Following list is hidden by owner',
      LOAD_ERROR: 'Failed to load list',
      VIEWING_AS_GUEST: 'You are viewing your own store as guest.',
      PRIVACY_TITLE: '🔒 Privacy Settings',
      PRIVACY_LABEL: 'Show followers/following list',
      PRIVACY_DESC: 'Toggle visibility of followers and following lists on your page.',
      PRIVACY_SUCCESS: 'Privacy settings updated successfully!',
      PRIVACY_ERROR: 'Error updating privacy settings.',
      MENU_CATEGORIES: 'Menu Categories',
      COLLAPSE_CATEGORY: 'Collapse Category',
      EXPAND_CATEGORY: 'Expand Category',
      ALL_FOODS: 'All Dishes',
      LOADING_FOODS: 'Loading dishes...',
      LOADING_MORE: 'Loading...',
      LOAD_MORE: 'See more dishes',
      GO_TO_ADMIN: '[Go to Admin Panel]',
      MANAGE_RESTAURANT: 'Manage Restaurant',
      CATEGORY_MANAGER: {
        TITLE: 'Groups & Categories',
        LOADING: 'Loading categories...',
        HELP_TOOLTIP: 'Group is the root folder. Once created, click [+] on it to create child Categories inside.',
        ADD_GROUP: 'Add New Group',
        GUIDE_TITLE: '💡 Categorizing Guide:',
        GUIDE_GROUP: 'Category Group (E.g.: Drinks): You can assign food items directly to this Group.',
        GUIDE_CATEGORY: 'Sub-category (E.g.: Milk tea, Juice): If you want more details, click [+] on Group to create a Sub-category, then assign food items to it.',
        PRIORITY_PREFIX: 'Display Priority Order: #',
        PRIORITY_SHORT: 'Priority: #',
        ADD_ROOT_CATEGORY: 'Add Root Category',
        ADD_SUB_CATEGORY: 'Add Sub-category',
        EMPTY_GROUP_NOTE: '📌 You can assign food items directly to this group, or click [+] to create a sub-category.',
        EMPTY_GROUPS: 'No groups yet',
        EDIT_GROUP: 'Edit Group',
        GROUP_NAME: 'Group Name',
        DISPLAY_ORDER: 'Display Order',
        ORDER_DESC_GROUP: 'Used for sorting display positions on Menu. Smaller numbers have higher priority. E.g., 0 ranks first, 1 ranks second.',
        GROUP_PLACEHOLDER: 'E.g., Mains, Drinks...',
        EDIT_CATEGORY: 'Edit Category',
        ADD_CATEGORY: 'Add Category',
        CATEGORY_NAME: 'Category Name',
        CATEGORY_PLACEHOLDER: 'E.g., Rice, Juices...',
        ORDER_DESC_CATEGORY: 'Used for sorting display positions on Menu. Smaller numbers have higher priority.',
        CONFIRM_DELETE_TITLE: 'Confirm Deletion',
        CONFIRM_DELETE_MESSAGE: (type: string) => `Are you sure you want to delete this ${type}? All sub-categories inside will also be deleted!`
      }
    },
    UPLOAD_EXCEL: {
      MAIN_GROUP: '📁 Main Group',
      COLS: {
        NAME: 'Food Name',
        PRICE: 'Price',
        DESC: 'Description',
        IMAGE: 'Image',
        TAGS: 'Tags'
      },
      FILE_NAME: 'sample-food-template.xlsx',
      SHEET_NAME: 'Food List',
      DOWNLOAD_SUCCESS: 'Sample file downloaded!',
      READ_SUCCESS: (count: number) => `Successfully read ${count} food items from file!`,
      READ_ERROR: 'Error reading Excel file. Please check format.',
      INVALID_DATA: 'No valid data found. Check column headers and data.',
      BRANCH_REQUIRED: 'Please select branch to apply',
      EMPTY_DATA: 'Empty or invalid data',
      UPLOAD_SUCCESS: (count: number) => `Successfully added ${count} food items!`,
      UPLOAD_ERROR: 'Error uploading data to system.',
      TITLE: 'Upload Excel',
      GUIDE_TITLE: 'Excel Upload Guide:',
      DOWNLOAD_BTN: 'Download Sample',
      STEP_1: 'Step 1: Select branch',
      STEP_2: 'Step 2: Select category',
      STEP_3: 'Step 3: Select Excel file',
      SELECT_BRANCH: '-- Select Branch --',
      SELECT_CATEGORY: '-- Uncategorized (skip) --',
      NO_CATEGORY_WARN: '⚠ This branch has no categories. Go to "Categories" tab to create one first.',
      LOADING_CATEGORY: 'Loading categories...',
      PREVIEW_TITLE: (count: number) => `Preview Data (${count} items)`,
      SAVING: 'Processing...',
      SAVE_BTN: (count: number) => `Save ${count > 0 ? count + ' items' : ''} to System`,
      OPTIONAL: '(Optional)',
      GUIDES: {
        COLS_INFO: 'Excel file must have exactly these columns:',
        REQUIRED_INFO: (col1: string, col2: string) => `${col1} and ${col2} are required columns.`,
        TAGS_INFO: 'enter multiple values separated by commas (e.g. Snacks, Drinks).',
        NO_FILE: 'No file yet? Download sample file, fill in, and upload.',
      }
    }
  },
  ADMIN: {
    PANEL_TITLE: 'Admin Panel',
    APPROVE_MERCHANTS: 'Approve Merchants',
    MANAGE_MERCHANTS: 'Manage Merchants',
    MANAGE_CUSTOMERS: 'Manage Customers',
    MANAGE_MENU: 'Manage Menus',
    MANAGE_LEVEL_BADGES: 'Manage Levels & Badges',
    SEND_NOTIFICATION: 'Send Notification',
    BADGES_MANAGER: {
      TITLE: 'Level & Badge Configurations',
      DESC: 'Manage minimum points and auto-assigned badges for customers and merchants.',
      ROLE: 'Role',
      BADGE_TITLE: 'Badge Title',
      MIN_POINTS: 'Min Points Required',
      ADD_BADGE: 'Add New Badge',
      DELETE_CONFIRM: 'Are you sure you want to delete this badge configuration?',
      SAVE_SUCCESS: 'Badge configuration saved successfully!',
      POINTS_REQUIRED: 'Please enter valid minimum points.',
      TITLE_REQUIRED: 'Please enter badge title.',
      TITLE_PLACEHOLDER: 'E.g., Food Expert',
      POINTS_PLACEHOLDER: 'E.g., 1000',
      CREATE_ERROR: 'Failed to create badge configuration',
      DELETE_ERROR: 'Failed to delete badge configuration',
      REFRESH_BTN: 'Refresh',
      ADD_BADGE_FORM_TITLE: 'Add New Badge',
      MIN_POINTS_LABEL: 'Min Points Required',
      MIN_REVIEWS_LABEL: 'Min Reviews',
      MIN_LIKES_LABEL: 'Min Likes',
      MIN_FOLLOWERS_LABEL: 'Min Followers',
      MIN_RATING_AVG_LABEL: 'Min Rating Avg',
      MIN_RATING_COUNT_LABEL: 'Min Rating Count',
      OPTIONAL_PLACEHOLDER: 'Optional',
      RULES_CONFIG_TITLE: 'Points & Penalty Config',
      RULES_LOADING: 'Loading rules...',
      RULES_POINTS_PER_LEVEL: 'Points Per Level (XP / Level)',
      RULES_REVIEW_POINTS: 'Review Points',
      RULES_COMMENT_POINTS: 'Comment Points',
      RULES_LIKE_POINTS: 'Like Points',
      RULES_DEDUCTION_MULTIPLIER: 'Penalty Multiplier (on Undo/Delete)',
      RULES_DEDUCTION_HELP: 'E.g., 1.2 means that on undo/delete, the points deducted will be 120% of the original reward.',
      RULES_SAVE_BTN: 'Save points configuration',
      RULES_SAVE_SUCCESS: 'Points configuration updated successfully',
      RULES_SAVE_ERROR: 'Failed to save points configuration',
      RULES_LOAD_ERROR: 'Failed to load gamification config:',
      RULES_LOAD_ERROR_TOAST: 'Failed to load gamification data',
      CUSTOMER_BADGES_TITLE: (count: number) => `Diner Badges (${count})`,
      RESTAURANT_BADGES_TITLE: (count: number) => `Restaurant Badges (${count})`,
      BADGES_LOADING: 'Loading badges...',
      XP_REQUIRED: '⭐ XP Required: ',
      REVIEWS_UNIT: ' reviews',
      FOLLOWERS_UNIT: ' followers',
      RATING_AVG_UNIT: '',
      RATING_COUNT_UNIT: ' ratings',
      REVIEWS_LABEL_SHORT: 'Reviews: ',
      LIKES_LABEL_SHORT: 'Likes: ',
      FOLLOWERS_LABEL_SHORT: 'Followers: ',
      RATING_AVG_LABEL_SHORT: 'Average Rating: ',
      RATING_COUNT_LABEL_SHORT: 'Rating Count: ',
    },
    NOTIFICATION_TAB: {
      TITLE: 'Send System Notification',
      DESC: 'Create and send notifications directly to the notification bell of all users or a specific individual.',
      SECTION_TITLE: 'Notification Content Details',
      RECIPIENT_LABEL: 'Recipient Target',
      RECIPIENT_ALL: (count: number) => `All Members (${count})`,
      RECIPIENT_SPECIFIC: 'Specific Member',
      SELECT_USER_LABEL: 'Select Member',
      SELECT_USER_PLACEHOLDER: '-- Select recipient --',
      USER_OPTION: (name: string, role: string, email: string) => `${name} (${role === 'CUSTOMER' ? 'Customer' : 'Restaurant'} - ${email})`,
      NOTIF_TYPE_LABEL: 'Notification Type',
      NOTIF_TYPE_OPTIONS: {
        SYSTEM: 'System (SYSTEM)',
        WARNING: 'Warning (WARNING)',
        PROMOTION: 'Promotion (PROMOTION)',
      },
      TITLE_LABEL: 'Notification Title',
      TITLE_PLACEHOLDER: 'Enter a concise title...',
      CONTENT_LABEL: 'Detailed Content',
      CONTENT_PLACEHOLDER: 'Enter full notification content to send to users...',
      SEND_BTN: 'Send Notification Now',
      SENDING: 'Sending...',
      PREVIEW_TITLE: 'Notification Preview',
      PREVIEW_TITLE_DEFAULT: '(Sample Title)',
      PREVIEW_CONTENT_DEFAULT: 'Your detailed notification content will be displayed here as you draft...',
      PREVIEW_TIME: 'Just now',
      TIP_TITLE: 'Quick Tip',
      TIP_DESC: 'Sent notifications will display a flashing red dot on the recipient\'s bell icon and be saved permanently on their device.',
      TOAST: {
        TITLE_REQUIRED: 'Please enter a notification title!',
        CONTENT_REQUIRED: 'Please enter notification content!',
        USER_REQUIRED: 'Please select a recipient member!',
        NO_USERS: 'No members found on the system to send notifications to.',
        SEND_ALL_SUCCESS: (count: number) => `Successfully sent system notification to ${count} members!`,
        USER_NOT_FOUND: 'Selected member does not exist.',
        SEND_SPECIFIC_SUCCESS: (name: string) => `Successfully sent notification to member: ${name}!`,
        SEND_ERROR: 'An error occurred while sending notification.',
      }
    },
    IMPORT_EXCEL: 'Import Excel',
    SYSTEM_FOOD: 'System Foods',
    MERCHANT_FOOD: 'Merchant Foods',
    BATCH_SAVE: 'Save',
    BATCH_CANCEL: 'Cancel',
    DESELECT_ALL: 'Deselect all',
    BATCH_SAVE_ALL: 'Save changes',
    BATCH_CANCEL_ALL: 'Cancel changes',
    UNSAVED_CHANGES: (count: number) => `You have ${count} unsaved changes on partner menus.`,
    EDIT_MODE_LABEL: 'Edit',
    VIEW_MODE_LABEL: 'View',
    FILTER_ALL: 'All',
    FILTER_RECOMMENDED: 'Recommended',
    FILTER_UNRECOMMENDED: 'Not Recommended',
    SOURCE_PARTNER: 'Partner',
    DONE: 'Completed',
    SAVE_SUCCESS: 'Updated successfully!',
    DELETE_SUCCESS: 'Deleted successfully!',
    FEATURE_TODAY_ON: 'Enabled Today\'s Featured',
    FEATURE_TODAY_OFF: 'Disabled Today\'s Featured',
    FEATURE_WEEKLY_ON: 'Enabled Weekly Featured',
    FEATURE_WEEKLY_OFF: 'Disabled Weekly Featured',
    RECOMMEND_ON: 'Enabled Recommendations',
    RECOMMEND_OFF: 'Disabled Recommendations',
    UPDATE_FAILED: 'Update failed',
    DELETE_WARNING: 'Are you sure you want to delete this account?',
    CONFIRM_DELETE_USER: 'Are you sure you want to delete this account?',
    MODAL: {
      EDIT_TITLE: 'Edit Food Item',
      FOOD_NAME: 'Food Name',
      PRICE: 'Price (VND)',
      TAGS: 'Tags',
      IMAGE_URL: 'Image URL',
      DESCRIPTION: 'Description',
    },
    TABLE: {
      NAME: 'Account Name',
      FOOD_NAME: 'Food Name',
      SOURCE: 'Source',
      EMAIL: 'Email',
      PRICE: 'Price',
      DATE: 'Registration Date',
      ACTION: 'Action',
      EMPTY: 'No data found.',
      FEATURE_TODAY: 'Today\'s Specials',
      FEATURE_WEEKLY: 'Weekly Specials',
      ADMIN_RECOMMEND: 'Admin Pick',
      SHOWING_FOODS: (count: number) => `Showing ${count} food items`,
      SHOWING_RESTAURANTS: (count: number) => `Showing ${count} restaurants`,
      SHOWING_REQUESTS: (count: number) => `Showing ${count} requests`,
      SHOWING_ACCOUNTS: (count: number) => `Showing ${count} accounts`,
      DRAFT: 'Draft',
    },
    CONFIRM: {
      DELETE_USER: 'Are you sure you want to delete this account?',
      DELETE_FOOD: 'Are you sure you want to delete this food item?',
      DELETE_FOOD_DESC: 'This action cannot be undone. This food item will be deleted permanently.',
      DELETE_USER_DESC: 'This action cannot be undone. This user will be deleted permanently.',
      BATCH_SAVE: 'Confirm save changes?',
      BATCH_SAVE_DESC: 'Are you sure you want to apply all draft changes to partner menus?',
      BATCH_DISCARD: 'Confirm discard changes?',
      BATCH_DISCARD_DESC: 'All current draft changes on partner menus will be discarded. This cannot be undone. Confirm discard?',
      APPROVE_FOOD: 'Confirm Food Approval',
      APPROVE_FOOD_DESC: (name: string) => `Are you sure you want to approve food item "${name}"? It will immediately show on the customer menu.`,
      REJECT_FOOD: 'Confirm Food Rejection',
      REJECT_FOOD_DESC: (name: string) => `Are you sure you want to reject food item "${name}"? It will be hidden from the public menu.`,
      SAVE_FOOD: 'Confirm Food Save',
      SAVE_FOOD_DESC: 'Are you sure you want to save these changes for the food item?',
    },
    PENDING_APPROVAL: 'PENDING',
    VIEW_MODE: {
      TABLE: 'Table',
      ROW: 'Row (1x1)',
      TITLE_TABLE: 'View table',
      TITLE_ROW: 'View rows',
      TITLE_GRID: 'View grid',
    },
    LEGAL_DOCS: (docs: string) => `Legal documents: ${docs}`,
    REGISTER_DATE: (date: string) => `Registered: ${date}`,
    JOIN_DATE: (date: string) => `Joined: ${date}`,
  },
  CUSTOMER: {
    GREETING: (name: string) => `Hello, ${name}! 👋`,
    SUBTITLE: 'Would you like some AI food recommendations for lunch today?',
    FAVORITES: 'Favorites',
    FAVORITE_UPDATE_ERROR: 'Unable to update favorites list.',
    AI_SUGGESTION: 'AI Suggestions for You',
    AI_SUGGESTION_DESC: (food: string) => `Based on your history, we suggest ${food} for today.`,
    RECENT_FOODS: 'Recently Viewed',
    RECENT_FOODS_DESC: (limit: number) => `Your ${limit} most recently viewed food items`,
    RECENT_FOOD_SUGGEST: (days: number) => `AI suggested ${days} days ago`,
    PLACEHOLDER_FOOD: 'Traditional Beef Pho',
    OLDER_HISTORY: 'Earlier History',
    OLDER_HISTORY_DESC: (limit: number) => `Dishes you viewed in your last ${limit} visits`,
    OLDER_FOODS_TITLE: 'Previously Viewed Dishes',
    PLACEHOLDER_FOOD_2: 'Hanoi Bun Cha',
    INFO: 'Personal Info',
    UPDATE_PREFERENCES: 'Update AI Context',
    UPDATE_PREFERENCES2: 'This data is used to train the AI for better food recommendations. You can customize this later in your Dashboard.',
    SUCCESS_UPDATE: 'Successfully updated!',
    AI_HISTORY: 'Recommendation History',
    AI_CONTEXT: 'Dietary Preferences (AI Context)',
    ONBOARDING_SUCCESS: 'Awesome!',
    ONBOARDING_PREPARING: 'Wait a moment ... !',
    STEP: (current: number, total: number) => `Step ${current} / ${total}`,
    NO_HISTORY: 'No recently viewed dishes history',
    AI_LOGIN_REQUIRED: 'Please login to use AI suggestions! ✨',
    AI_CUSTOMER_ONLY: 'AI suggestions are currently for customers only. Thank you!',
    QUESTION: 'Question',
  },
  SETTINGS: {
    TITLE: 'Account Settings',
    SUBTITLE: 'Manage your profile and account security',
    TABS: {
      PROFILE: 'Profile',
      SECURITY: 'Security',
      VERIFICATION: 'Verification',
      LANGUAGE: 'Language',
      DANGER_ZONE: 'Danger Zone',
    },
    LANG_DESC: 'Select the display language for the interface and system notifications',
    LANGUAGE_CONFIRM_TITLE: 'Confirm Language Change',
    LANGUAGE_CONFIRM_DESC: 'Are you sure you want to change the display language of the system? The page will reload.',
    SECURITY_CONFIRM_TITLE: 'Confirm Password Change',
    SECURITY_CONFIRM_DESC: 'Are you sure you want to change your account password?',
    VERIFY_CONFIRM_TITLE: 'Confirm Verification Request',
    VERIFY_CONFIRM_DESC: 'The system will send a verification link to your email. Do you want to proceed?',
    PRIVACY_CONFIRM_TITLE: 'Confirm Privacy Change',
    PRIVACY_CONFIRM_DESC: 'Are you sure you want to change the visibility of your followers/following lists on your profile page?',
    PROFILE_CONFIRM_TITLE: 'Confirm Save Changes',
    PROFILE_CONFIRM_DESC: 'Are you sure you want to save these changes to your personal profile?',
    SECURITY: {
      CURRENT_PASSWORD: 'Current password',
      NEW_PASSWORD: 'New password',
      CONFIRM_PASSWORD: 'Confirm new password',
      CHANGE_PASSWORD: 'Change Password',
      CHANGE_SUCCESS: 'Password changed successfully!',
      CHANGE_PASSWORD_ERROR: 'Failed to change password. Please try again.',
      MISMATCH: 'New passwords do not match.',
    },
    VERIFICATION: {
      TITLE: 'Verify your email address',
      LABEL: 'Enter email to verify',
      SUCCESS: 'Email verified successfully!',
      SEND_EMAIL_ERROR: 'Failed to send verification email.',
      VERIFIED: 'Account verified.',
      VERIFY_NOW: 'Verify now',
    },
    PROFILE: {
      TITLE: 'Your Profile',
      NOTIFICATIONS: {
        UPDATE_TITLE: 'Account Updated',
        UPDATE_BODY: 'Your account information has been updated successfully.',
      },
      FULL_NAME: 'Full name',
      NOT_UPDATED: 'Not updated',
      EDIT_COVER: 'Edit cover image',
      FOLLOWERS: 'followers',
      FOLLOWING: 'following',
      DASHBOARD: 'Dashboard',
      FOLLOW: 'Follow',
      UNFOLLOW: 'Unfollow',
      SAVE_SUCCESS: 'Profile updated successfully!',
      BIO_EMPTY: 'This user has no bio.',
      PRIVACY_TITLE: '🔒 Personal Info Privacy Settings',
      PRIVACY_DESC: 'Customize which personal information fields you want to show or hide on posts and your profile page.',
      PRIVACY_TOAST_SUCCESS: (label: string, enabled: boolean) => `Display for ${label} has been turned ${enabled ? 'on' : 'off'}`,
      FOLLOW_LIST_PRIVATE: 'Following list has been hidden',
      PRIVACY_FIELDS: {
        showLevel: { label: 'Level', desc: 'Display level (Lv.) on posts and profile page.' },
        showBadge: { label: 'Badge Title', desc: 'Display badge title on posts and profile page.' },
        showPoints: { label: 'Reward Points', desc: 'Display reward points balance on profile page.' },
        showXpBar: { label: 'XP Progress Bar', desc: 'Display XP progress bar on profile page.' },
        showFollowList: { label: 'Follow List', desc: 'Display followers and following lists on profile page.' },
        showEmail: { label: 'Email Address', desc: 'Display email address on about section of profile.' },
        showPhone: { label: 'Phone Number', desc: 'Display phone number on personal info section of profile.' },
        showAddress: { label: 'Address / Location', desc: 'Display address or location on about section of profile.' },
      },
      TABS: {
        POSTS: 'Posts',
        ABOUT: 'About',
        FRIENDS: 'Friends',
        PHOTOS: 'Photos',
      },
      INTRO: {
        TITLE: 'Introduction',
        WORK: (work: string) => `Works at ${work}`,
        LIVES: (city: string) => `Lives in ${city}`,
        JOINED: (year: number) => `Joined in ${year}`,
        EDIT_DETAILS: 'Edit details',
        TITLE2: 'Intro',
        WORK_AT: 'Works at',
        LIVE_IN: 'Lives in',
        EMAIL: 'Email',
        JOINED_YEAR: 'Joined year',
        EDIT_BTN: 'Edit',
        EDIT_DETAILS_BTN: 'Edit details',
        BIO_PLACEHOLDER: 'No intro available. Add some words about yourself!',
      },
      POSTS: {
        EMPTY_TITLE: 'No posts yet',
        EMPTY_DESC: 'Start sharing your culinary experiences today!',
        THINKING: (name: string) => `What is on your mind, ${name}?`,
      },
      EDIT_MODAL: {
        TITLE: 'Edit Profile',
        SUCCESS: 'Profile updated successfully!',
        NAME: 'Display name',
        PHONE: 'Phone number',
        AVATAR: 'Avatar URL',
        COVER: 'Cover Image URL',
        BIO: 'Bio',
        ADDRESS: 'Address / Lives in',
        WORK: 'Works at',
        CITY: 'City / Province',
        DISTRICT: 'District',
        DISTRICT_PLACEHOLDER: 'Select District',
        STREET: 'Detailed Address (Street, House number...)',
        STREET_PLACEHOLDER: 'E.g., 123 Duong Lang',
        MERCHANT_SYNC: 'Merchant Sync',
        SYNC_AVATAR: 'Sync avatar as restaurant logo',
        SYNC_COVER: 'Sync cover image as restaurant cover image',
        CLOSE_SETTINGS: 'Close settings',
      },
      MODALS: {
        FOLLOWERS_TITLE: 'Followers',
        FOLLOWERS_EMPTY: 'No followers yet',
        FOLLOWING_TITLE: 'Following',
        FOLLOWING_EMPTY: 'Not following anyone yet',
        PRIVATE_LIST_ERROR: 'This list is private or hidden.',
      }
    },
    DANGER_ZONE: {
      TITLE: '⚠️ Danger Zone',
      WARNING: 'WARNING: This action is permanent and irreversible. Once you confirm deletion: All your data including personal profile, posts, likes, reviews, AI context, and restaurant branch information (if any) will be permanently deleted and CANNOT BE RECOVERED.',
      BUTTON: 'Delete my account',
      MODAL_TITLE: 'Confirm Account Deletion?',
      MODAL_WARNING: 'This action will permanently delete all your data. This operation absolutely cannot be undone!',
      PASSWORD_LABEL: 'Enter your password to confirm:',
      PASSWORD_PLACEHOLDER: 'Your account password',
      CONFIRM_BUTTON: 'Confirm delete',
      CANCEL_BUTTON: 'Cancel',
      TOAST_PASSWORD_REQUIRED: 'Please enter password to confirm.',
      TOAST_SUCCESS: 'Your account has been permanently deleted from the system.',
      TOAST_ERROR: 'Incorrect password or an error occurred.'
    }
  },
  IMAGE_VIEWER: {
    IMAGE_NUM: (num: number) => `Image ${num}`,
    THUMB_NUM: (num: number) => `Thumb ${num}`,
    PREV_IMAGE: 'Previous image',
    NEXT_IMAGE: 'Next image',
    MINIMIZE: 'Minimize',
    VIEW_IMAGE_NUM: (num: number) => `View image ${num}`,
    POST_IMAGE: 'Post image',
  },
  UPLOADER: {
    CROP_TITLE: 'Customize Frame',
    CROP_DESC: '— Drag and zoom to select display area',
    CROP_CANCEL: 'Cancel',
    CROP_CONFIRM: 'Apply',
    CROP_ERROR: 'Error cropping image, please try again.',
    CROP_POST_IMAGE: (current: number, total: number) => `Post image ${current}/${total}`,
    RECROP_IMAGE: (num: number) => `Customize image ${num}`,
    MAX_IMAGES_REACHED: (remaining: number, max: number) => `Only ${remaining} more images can be added (max ${max}).`,
    UPLOAD_ERROR: 'Error uploading image.',
    CROP_ZOOM: 'Zoom:',
    CROP_ROTATE: 'Rotate:',
    CROP_APPLY: 'Apply',
    CROP_RESET: 'Reset',
    CROP_PROCESSING: 'Processing...',
    AVATAR: 'Avatar',
    COVER: 'Cover Image',
    POST_IMAGE: 'Post Image',
    ACCEPT_FORMAT: 'Only accept image files (JPG, PNG, WEBP...)',
    MAX_SIZE: 'Image must not exceed 10MB',
    UPLOAD_SUCCESS: 'Image uploaded successfully!',
    UPLOAD_FAIL: 'Image upload failed. Please try again.',
    MAX_IMAGES: (max: number) => `Max ${max} images`,
    ADD_IMAGE: 'Add Image',
    DROP_HERE: 'Drop image here',
    CLICK_OR_DRAG: 'Click or drag and drop',
    CUSTOMIZE_FRAME: 'Customize frame',
    DELETING: 'Deleting...',
    DELETE_IMAGE: 'Delete image',
    CROP_IMAGE: 'Crop image',
    CONFIRM_DELETE: 'Confirm deleting this image?',
    DELETE_SUCCESS: 'Old image deleted from storage.',
    DELETE_FAIL: 'Failed to delete old image. Please try again.',
    CHANGE_IMAGE: 'Change image',
  },
  NAV: {
    HOME: 'Home',
    EXPLORE: 'Explore',
    FORUM: 'Forum',
    OFFERS: 'Offers',
    ADMIN_PANEL: 'Admin Panel',
    RESTAURANT_PANEL: 'Store Management',
    DASHBOARD: 'Personal Dashboard',
    SETTINGS: 'Settings',
    FEATURES: 'Features',
    SEARCH_PLACEHOLDER: 'Feature search is under development!',
    USER_MENU: 'User menu',
    AI_CHAT: 'AI Assistant',
    NOTIFICATIONS: {
      TITLE: 'Notifications',
      MARK_ALL_READ: 'Mark all as read',
      CLEAR_ALL: 'Clear all',
      EMPTY: 'You have no notifications.',
      SENT_AT: (dateStr: string) => `Sent at ${dateStr}`,
      GO_TO_POST: 'Go to post',
      DISMISS: 'Got it',
      TYPES: {
        LIKE: 'Like Interaction',
        COMMENT: 'New Comment',
        REPLY: 'Comment Reply',
        SHARE: 'Post Shared',
        LEVEL_UP: 'Level Up',
        PROFILE_UPDATE: 'Profile Updated',
        MODERATION_REMOVE: 'Content Moderation',
        MODERATION_RESOLVE: 'Report Resolved',
        MODERATION_DISMISS: 'Report Dismissed',
        SYSTEM: 'System Notification',
        WARNING: 'System Warning',
        PROMOTION: 'System Promotion',
        DEFAULT: 'Notification',
      }
    }
  },
  FOOTER: {
    DESCRIPTION: 'AI-powered smart food recommendation platform, helping you find your favorite taste anywhere, anytime.',
    QUICK_LINKS: 'Quick Links',
    FOLLOW_US: 'Follow us',
    RIGHTS: '© 2026 Food AI. All rights reserved.',
    TERMS: 'Terms',
    POLICY: 'Privacy Policy',
    CONTACT: 'Contact',
  },
  HERO: {
    TITLE_START: 'What do you want to eat',
    TITLE_HIGHLIGHT: 'today?',
    DESCRIPTION: 'Tell AI about your mood, budget or preferences. We will recommend the perfect dishes near you.',
    BG_ALT: 'Homepage background',
    OPEN_AI_TOOLTIP: 'Toggle AI Assistant',
    SEARCH_PLACEHOLDER: 'How are you feeling today?',
    PLACEHOLDER_AUTH: 'Tell AI what you want to eat...',
    PLACEHOLDER_GUEST: 'Log in to chat with AI recommendations...',
    SEARCH_BUTTON: 'Search',
    AI_THINKING: 'AI is thinking...',
    SUGGESTED_TITLE: 'Recommended dishes for you:',
    FEATURES: {
      MOOD: 'Mood Recommendations',
      BUDGET: 'Budget Friendly',
      LOCATION: 'Dishes Near You',
    }
  },
  HOME: {
    NEARBY_TITLE: "Good Food Nearby",
    NEARBY_SUBTITLE: "Explore delicious food right at your location",
    TODAY_TITLE: "Today\'s Specials",
    TODAY_SUBTITLE: "Great selected choices for today",
    WEEKLY_TITLE: "Featured Weekly Hits",
    WEEKLY_SUBTITLE: "The most liked dishes of the week",
    RECOMMENDED_TITLE: "Recommended for You",
    RECOMMENDED_SUBTITLE: "Delicious dishes selected and recommended by Admin",
    TAB_RECOMMENDED: "Recommended Dishes",
    TAB_TODAY: "Today's Specials",
    TAB_WEEKLY: "Weekly Hits",
    TAB_RECOMMENDED_SHORT: "Recommended",
    TAB_TODAY_SHORT: "Today's",
    TAB_WEEKLY_SHORT: "Weekly",
    LOAD_MORE: "Load More Delicious Dishes",
    LOAD_MORE_COUNT: (count: number) => `${count} more dishes`,
    EMPTY_TAB: "No dishes found in this category.",
    MASCOT_ALT: "Food AI Mascot",
  },
  FORM: {
    FOOD_NAME: 'Food Name',
    PRICE: 'Price (VND)',
    DESCRIPTION: 'Description',
    IMAGE_URL: 'Image (URL)',
    TAGS: 'Tags',
    EMAIL: 'Email',
    ADDRESS: 'Address',
    PHONE: 'Phone number',
    MAP_URL: 'Google Maps Link',
    LAT: 'Latitude',
    LNG: 'Longitude',
    NOT_SET: 'Not set',
    NO_PREFERENCES: 'You have not updated your preferences yet.',
    OPINION_PLACEHOLDER: 'Enter your message here...',
    EMAIL_REQUIRED: 'Email is required',
    EMAIL_INVALID: 'Email is invalid',
    PASSWORD_REQUIRED: 'Password is required',
    PASSWORD_INVALID: 'Password must be at least 8 characters, with letters and numbers',
    CONFIRM_PASSWORD_MISMATCH: 'Confirm password does not match',
    NAME_REQUIRED: 'Name must be at least 2 characters',
    LEGAL_DOCS_REQUIRED: 'Please provide clear legal verification document details',
    PLACEHOLDERS: {
      NAME: 'John Doe',
      EMAIL: 'user123@gmail.com',
      PASSWORD: '••••••••',
      ADDRESS: 'Hanoi, Vietnam...',
      WORK: 'ABC Company...',
    }
  },
  EXPLORE: {
    TITLE: 'Explore by Category',
    TITLE_TAG: (tag: string) => tag ? `Explore "${tag}"` : 'Explore Restaurants',
    FOUND_COUNT: (count: number) => `Found ${count} matching restaurants`,
    SEARCH_IN_TAG: (tag: string) => tag ? `Search restaurants in ${tag}...` : 'Search restaurants...',
    EMPTY_TITLE: 'Sorry, no restaurants found!',
    EMPTY_DESC: 'Please try searching with another keyword.',
    LOADING: 'Loading explore page...',
    SEARCHING: 'Searching restaurants for you...',
    TAG_PLACEHOLDER: 'Enter tags separated by commas!',
    SUGGESTED_TAGS: 'Suggested:',
    ALL_DISTRICTS: 'All Districts',
  },
  FOOD: {
    DETAIL_TITLE: 'Food Description',
    RESTAURANT_TITLE: 'Restaurant Address',
    VIEW_MAP: 'View location on Map',
    NO_ADDRESS: 'No address updated',
    STORE_PAGE: 'Restaurant Page',
    REVIEWS: 'View Reviews',
    ADD_FAVORITE: 'Add to Favorites',
    VIEW_DETAIL: 'View details',
    NO_DESCRIPTION: 'No description',
    NO_IMAGE: 'No image',
    UNCATEGORIZED: 'Uncategorized',
    SYSTEM: 'System',
  },
  UI_MESSAGES: {
    CATEGORY: {
      LOAD_ERROR: 'Error loading categories',
      GROUP_NAME_REQUIRED: 'Group name is required',
      GROUP_UPDATE_SUCCESS: 'Group updated successfully',
      GROUP_ADD_SUCCESS: 'Group added successfully',
      GROUP_DELETE_SUCCESS: 'Group deleted successfully',
      CATEGORY_NAME_REQUIRED: 'Category name is required',
      CATEGORY_UPDATE_SUCCESS: 'Category updated successfully',
      CATEGORY_ADD_SUCCESS: 'Category added successfully',
      CATEGORY_DELETE_SUCCESS: 'Category deleted successfully',
      HAS_FOODS_ERROR: 'An error occurred (the category might contain food items)',
      MAX_GROUPS_LIMIT_ERROR: (max: number) => `You are allowed to create at most ${max} Groups to avoid overloading the menu.`,
      GROUP_ORDER_DUPLICATE_ERROR: (order: number) => `Display order #${order} is already in use by another group. Choose another!`,
      CATEGORY_ORDER_DUPLICATE_ERROR: (order: number) => `Display order #${order} already exists in this group. Choose another!`,
    },
    RESTAURANT: {
      SELECT_REQUIRED: 'Please select a business branch',
    },
    ADMIN: {
      UPDATE_FAILED: 'Update failed',
      UPDATE_SUCCESS: 'Updated successfully',
      LOAD_ERROR: 'Error fetching admin data:',
    },
  },
  IMPORT_EXCEL: {
    MESSAGES: {
      INVALID_FILE_TYPE: 'Please select an Excel file (.xlsx) or CSV (.csv)',
      IMPORT_SUCCESS: (created: number, appended: number) => `Import successful! Created ${created} and merged ${appended} restaurants.`,
      IMPORT_ERROR_DEFAULT: 'Error importing Excel file',
      VALID_TYPES: [
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'application/vnd.ms-excel',
        'text/csv'
      ],
      TEMPLATE_HEADERS: 'Email,Password,Owner Name,Restaurant Name,Address,Latitude,Longitude,Restaurant Map URL,Food Name,Food Price,Food Desc,Food Image URL,Food Tags\n',
      TEMPLATE_SAMPLE: 'merchant@gmail.com,password123,Nguyen Van A,Pizza Ha Noi,Ha Noi,21.0285,105.8542,https://maps.app.goo.gl/example,Pizza Hai San,150000,Pizza ngon thuong hang,https://example.com/pizza.jpg,"ngon,hai san"\n',
      TEMPLATE_FILENAME: 'merchant_template.csv',
    },
    UI: {
      TITLE: 'Bulk Import Data',
      TEMPLATE_TITLE: 'Download sample CSV/Excel Template',
      TEMPLATE_DESC: 'Use sample template for correct data parsing.',
      BTN_DOWNLOAD: 'Download Sample',
      DROPZONE_TITLE_FILE: 'Click or drag file here',
      DROPZONE_SUBTITLE_FILE: 'Supports .xlsx, .csv formats',
      BTN_REMOVE_FILE: 'Remove file',
      BTN_CANCEL: 'Cancel',
      BTN_IMPORT: 'Import Now',
      BTN_LOADING: 'Processing...'
    }
  },
  ONBOARDING: {
    BRANCH_STEP_TITLE: 'Configure location & business branches',
    BRANCH_STEP_DESC: 'Declare branch details so that AI can optimize visibility for nearby diners.',
    ADD_BRANCH_BTN: 'Add Another Branch (+)',
    BACK_BTN: 'Back',
    COMPLETE_BTN: 'Complete & Initialize',
    REQUIRED_BRANCH_FIELDS: (index: number) => `Please fill Name and Address for Branch #${index}.`,
    INVALID_COORDINATES: (index: number) => `GPS Coordinates of Branch #${index} must be valid numbers.`,
    INVALID_LATITUDE: (index: number) => `Latitude of Branch #${index} must be between -90 and 90.`,
    INVALID_LONGITUDE: (index: number) => `Longitude of Branch #${index} must be between -180 and 180.`,
    INVALID_HOURS_FORMAT: (index: number) => `Operating hours format of Branch #${index} is invalid (E.g., 08:00 - 22:00).`,
    MIN_BRANCH_REQUIRED: 'You must declare at least 1 main branch.',
    ADD_BRANCH_SUCCESS: 'Added a blank branch. Please fill details below.',
    REMOVE_BRANCH_SUCCESS: 'Removed branch from list.',
    STEP_INDICATOR: (current: number, total: number) => `Step ${current} / ${total}`,
    FORM: {
      NAME_LABEL: 'Branch Name',
      NAME_PLACEHOLDER: 'E.g., FOOD AI - Hanoi Branch',
      ADDRESS_LABEL: 'Address',
      ADDRESS_PLACEHOLDER: 'E.g., 123 Nguyen Trai, Thanh Xuan, Hanoi',
      LAT_LABEL: 'Latitude',
      LAT_PLACEHOLDER: 'E.g., 20.9760',
      LNG_LABEL: 'Longitude',
      LNG_PLACEHOLDER: 'E.g., 105.7629',
      MAP_URL_LABEL: 'Google Maps Link (Optional)',
      MAP_URL_PLACEHOLDER: 'E.g., https://maps.google.com/...',
      HOURS_LABEL: 'Operating hours (Optional)',
      HOURS_PLACEHOLDER: 'E.g., 09:00 - 21:00',
      BIO_LABEL: 'Slogan / Bio',
      BIO_PLACEHOLDER: 'E.g., Clean food, healthy eating...',
    },
    QUESTIONS: {
      CUSTOMER: {
        GOAL: {
          Q: 'What is your dietary goal?',
          DESC: 'So AI can recommend dishes that fit your health goals.',
          OPT: { WEIGHT_LOSS: 'Weight loss', MUSCLE_GAIN: 'Muscle gain', EAT_CLEAN: 'Eat Clean', ENJOY: 'Enjoyment' }
        },
        CUISINE: {
          Q: 'Which cuisine style do you prefer?',
          DESC: 'We will prioritize showing restaurants with these styles.',
          OPT: { VIETNAMESE: 'Vietnamese', KOREAN: 'Korean', JAPANESE: 'Japanese', WESTERN: 'Western' }
        },
        BUDGET: {
          Q: 'What is your budget per meal?',
          DESC: 'Suggest dishes within your budget range.',
          OPT: { UNDER_100K: 'Under 100k', '100K_200K': '100k - 200k', '200K_400K': '200k - 400k', OVER_400K: 'Above 400k' }
        },
        ALLERGIES: {
          Q: 'Do you have any food allergies?',
          DESC: 'Your safety is first. Let AI know!',
          OPT: { SEAFOOD: 'Seafood', PEANUTS: 'Peanuts', DAIRY: 'Dairy/Cheese', NONE: 'None' }
        }
      },
      RESTAURANT: {
        STYLE: {
          Q: 'What is your restaurant style?',
          DESC: 'Help diners imagine the dining space.',
          OPT: { LUXURY: 'Luxury', CASUAL: 'Casual', STREET: 'Street Food', TAKEAWAY: 'Takeaway' }
        },
        FLAVOR: {
          Q: 'What is the main flavor of your dishes?',
          DESC: 'Diners usually search by preferred flavors.',
          OPT: { SPICY: 'Spicy', SWEET: 'Sweet', SAVORY: 'Savory', LIGHT: 'Light/Fresh' }
        },
        TARGET: {
          Q: 'Who is your main target audience?',
          DESC: 'AI will prioritize showing your store to this group.',
          OPT: { STUDENTS: 'Students', OFFICE: 'Office workers', FAMILY: 'Family', TOURISTS: 'Tourists' }
        }
      }
    }
  },
  CATEGORIES: {
    NAMES: {
      WATER: 'Soup/Noodles',
      RICE: 'Rice / Sticky rice',
      SNACK: 'Snacks',
      DESSERT: 'Desserts',
      CASUAL: 'Casual',
      LUXURY: 'Premium'
    },
    TAGS: {
      TRADITIONAL: 'traditional',
      FASTFOOD: 'fast food',
      FRIED: 'fried',
      ALONE: 'solo',
      GROUP: 'group',
      OFFICE: 'office',
      SPICY: 'spicy',
      HEALTHY: 'healthy'
    }
  },
  AI_CHAT: {
    SIDEBAR: {
      NEW_CHAT: 'New Chat',
      RECENT: 'Recent Chats',
      NO_CHAT: 'No chats yet',
      CLOSE_SIDEBAR: 'Close sidebar',
      DELETE_CHAT: 'Delete chat',
      CUSTOMER: 'Customer',
      FREE_PLAN: 'Free Plan',
      REFRESH_LIST: 'Refresh list',
    },
    HEADER: {
      OPEN_SIDEBAR: 'Open sidebar',
      SIMULATE_CONTEXT: 'Weather in',
      COLLAPSE_CHAT: 'Collapse chat',
      ACTIVE: 'Active',
    },
    CONFIG: {
      WEATHER_TITLE: 'Real-time Weather',
      TEMPERATURE: 'Temperature',
      STATUS: 'Status',
      RAINY: 'Rainy 🌧️',
      DRY: 'Clear ☀️',
      LOCATION_TITLE: 'GPS Coordinates & Location',
      GPS_COORDS: 'GPS Coordinates',
      UPDATE_GPS: 'Sync current GPS',
      TIPS_TITLE: '💡 Automatic Detection Mechanism:',
      TIP_1: '1. The system automatically reads GPS coordinates from your browser to sync weather details via Open-Meteo.',
      TIP_2: '2. The AI assistant automatically analyzes real-time weather (temp, rain, wind) to recommend the best dishes.',
      WEATHER_TEMP_LIMITS: {
        MIN: 15,
        MAX: 42,
      },
      GPS_DEFAULTS: {
        LAT: 21.0285,
        LNG: 105.8542,
      },
      CITY_DEFAULTS: {
        NAME: 'Hanoi',
      },
      SYNCING_WEATHER: 'Syncing weather...',
      FEELS_LIKE: (temp: number) => `Feels like ${temp}°C`,
      HUMIDITY: 'Humidity',
      WIND_SPEED: 'Wind speed',
      NO_WEATHER_DATA: 'No weather data. Sync GPS to activate.',
      LATITUDE: 'Latitude (Lat)',
      LONGITUDE: 'Longitude (Lng)',
      UPDATE_BTN: 'Update',
    },
    FEED: {
      WELCOME: 'Hello! How can I help you today?',
      WELCOME_SUB: 'Ask me anything (E.g., "What is delicious to eat today", "Search for bun cha near me",...)',
      SUGGESTION: 'Suggestions for you:',
      SEND_MESSAGE: 'Send message',
      FEEDBACK_LIKE: '👍 Helpful',
      FEEDBACK_DISLIKE: '👎 Irrelevant',
    },
    INPUT: {
      PLACEHOLDER: 'Ask culinary AI assistant...',
      SEND: 'Send',
      SEARCH: 'Chat Now!'
    },
    PREFERENCES: {
      TITLE: 'AI Recommendations Settings',
      TAB_LIKED: 'Liked Dishes',
      TAB_DISLIKED: 'Hidden Suggestions',
      LOADING: 'Loading...',
      EMPTY_LIST: 'Empty list',
      EMPTY_LIKED_DESC: 'Click thumbs up (LIKE) on AI recommended dishes to save here.',
      EMPTY_DISLIKED_DESC: 'Click thumbs down (DISLIKE) on AI recommendations to hide and save here.',
      VOICE_INPUT_LABEL: 'Enable voice input',
      REMOVE_LIKE_SUCCESS: 'Removed dish from likes!',
      REMOVE_DISLIKE_SUCCESS: 'Removed dish from hidden recommendations!',
      LOAD_ERROR: 'Could not load preferences.',
      REMOVE_ERROR: 'Could not remove feedback. Please try again.',
      TOOLTIP_REMOVE: 'Remove feedback',
      TAB_GENERAL: 'General',
      TAB_PERSONALIZATION: 'Personalization',
      TAB_DATA_CONTROL: 'Data Control',
      TAB_ACCOUNT: 'Account',
      THEME_LABEL: 'Theme',
      THEME_MIXED: 'Mixed',
      THEME_LIGHT: 'Light',
      THEME_DARK: 'Dark',
      LANG_LABEL: 'Language',
      LANG_AUTO: 'Auto Detect',
      LANG_VI: 'Tiếng Việt',
      LANG_EN: 'English',
      DELETE_FEEDBACKS_TITLE: 'Delete All AI Feedback',
      DELETE_FEEDBACKS_DESC: 'This will delete all Liked (LIKE) and Hidden (DISLIKE) feedback history, resetting the personalization AI model.',
      DELETE_FEEDBACKS_BTN: 'Clear All Feedback',
      DELETE_FEEDBACKS_CONFIRM: 'Are you sure you want to delete all Like/Dislike history? This will also remove dishes from your favorites list!',
      DELETE_FEEDBACKS_SUCCESS: 'Feedback cleared successfully!',
      DELETE_FEEDBACKS_ERROR: 'Error clearing feedback. Please try again.',
      ACCOUNT_INFO_TITLE: 'Customer Account Info',
      ACCOUNT_NAME: 'Full Name',
      ACCOUNT_EMAIL: 'Email Address',
      ACCOUNT_ROLE: 'Account Role',
      ACCOUNT_PLAN: 'Service Plan',
    },
    CONFIRM: {
      DELETE_CHAT: 'Are you sure you want to delete this chat conversation?',
      EMPTY_CHAT_WARNING: 'You already have an empty new chat ready.',
      ERROR_FALLBACK: 'Sorry, I encountered a system issue.',
    },
    TOAST: {
      GPS_SUCCESS: 'Device GPS coordinates updated successfully.',
      GPS_ERROR: 'Could not get GPS coordinates from browser.',
      GPS_NOT_SUPPORTED: 'Browser does not support GPS.',
      LOAD_HISTORY_ERROR: 'Error loading conversation history:',
      SEND_FIRST_ERROR: 'Error sending first message:',
      GPS_WARN: 'Could not read device GPS, using fallback defaults:',
      FEEDBACK_LIKE_SUCCESS: 'Marked helpful! AI will suggest similar dishes.',
      FEEDBACK_DISLIKE_SUCCESS: 'Feedback noted! AI will restrict this dish.',
      FEEDBACK_ERROR: 'Error sending feedback.',
    }
  },
  LOYALTY: {
    REASONS: {
      LIKE_POST: 'Liked post',
      UNLIKE_POST: 'Unliked post',
      COMMENT_POST: 'Commented on post',
      DELETE_COMMENT: 'Deleted comment',
      REPLY_COMMENT: 'Replied to comment',
      DELETE_REPLY: 'Deleted reply',
      CREATE_POST: 'Created new post',
      DELETE_POST: 'Deleted post',
      SHARE_POST: 'Shared post',
    },
    TITLE: 'Points & Rewards',
    POINTS_BALANCE: 'Reward Points Balance:',
    LEVEL: 'Level:',
    BADGE: 'Badge:',
    REDEEM: 'Redeem Now',
    REDEEM_SUCCESS: 'Voucher redeemed successfully!',
    REDEEM_ERROR: 'Not enough points to redeem voucher.',
    VOUCHERS_TITLE: 'Discount Voucher Mall',
    MY_VOUCHERS_TITLE: 'My Vouchers',
    VOUCHER_REDEEMED_BADGE: 'Redeemed',
    VOUCHER_CODE_PREFIX: 'Code: ',
    VOUCHER_MIN_SPEND_PREFIX: 'Min. Order: ',
    VOUCHER_EXPIRY_PREFIX: 'Expires: ',
    VOUCHER_EXPIRY_SUFFIX: ' days from redemption',
    VOUCHER_EMPTY: 'You have not redeemed any vouchers yet.',
    VOUCHER_EARN_DESC: 'Earn points through ordering, writing reviews, and contributing to the Food AI community.',
    REDEEM_SUCCESS_WITH_CODE: (code: string) => `Voucher redeemed! Your code: ${code}`,
    XP_PROGRESS: 'Experience (XP) to next level',
    REQUIRED_POINTS: (points: number) => `${points} Points`,
    LEVEL_UP_SUCCESS: (level: number) => `🎉 Congratulations! You have leveled up to Level ${level}!`,
    AWARD_POINTS_SUCCESS: (points: number, reason: string) => `+${points} reward points: ${reason}`,
    DEDUCT_POINTS_SUCCESS: (points: number, reason: string) => `-${points} reward points: ${reason}`,
    BADGES: {
      EXPERT: 'Food Expert',
      VIP: 'Elite Reviewer',
    },
    AVAILABLE_VOUCHERS: [
      {
        id: 'v1',
        code: 'FOODAI15K',
        title: 'Direct discount of 15,000 VND',
        description: 'Applicable to all orders from Food AI partners.',
        pointsCost: 300,
        discountValue: '15,000 VND',
        minSpend: '50,000 VND',
        expiryDays: 30,
      },
      {
        id: 'v2',
        code: 'FOODAI30K',
        title: 'Direct discount of 30,000 VND',
        description: 'Applicable to orders recommended by AI.',
        pointsCost: 500,
        discountValue: '30,000 VND',
        minSpend: '100,000 VND',
        expiryDays: 15,
      },
      {
        id: 'v3',
        code: 'FOODAI50K',
        title: 'Exclusive deal of 50,000 VND',
        description: 'Premium voucher for VIP members.',
        pointsCost: 800,
        discountValue: '50,000 VND',
        minSpend: '150,000 VND',
        expiryDays: 45,
      },
      {
        id: 'v4',
        code: 'FREESHIPAI',
        title: 'Free shipping (Max 20k)',
        description: 'Applicable to nearby restaurants within 3km radius.',
        pointsCost: 150,
        discountValue: 'FreeShip',
        minSpend: '0 VND',
        expiryDays: 7,
      },
    ],
    DEFAULT_BADGES: [
      { id: 'b1', role: 'CUSTOMER' as const, title: 'Active Diner', points: 300 },
      { id: 'b2', role: 'CUSTOMER' as const, title: 'Food Expert', points: 1000 },
      { id: 'b3', role: 'CUSTOMER' as const, title: 'Elite Reviewer', points: 3000 },
      { id: 'b4', role: 'RESTAURANT' as const, title: 'Potential Partner', points: 500 },
      { id: 'b5', role: 'RESTAURANT' as const, title: 'Reputable Partner', points: 2000 },
      { id: 'b6', role: 'RESTAURANT' as const, title: 'Outstanding Brand', points: 5000 },
    ],
    NOTIFICATIONS: {
      LEVEL_UP_TITLE: 'New Level Reached!',
      LEVEL_UP_BODY: (level: number) => `Congratulations! You have reached Level ${level} due to active participation!`,
    },
    LEVEL_UP_MODAL: {
      CONGRATS: 'Congratulations! 🎉',
      NEW_ACHIEVEMENT: 'New achievement unlocked',
      LEVEL_ACHIEVED: 'Level achieved:',
      NEW_BADGE: 'New badge:',
      GREAT: 'Awesome!',
    },
    BADGES_PAGE: {
      PAGE_TITLE: 'Levels & Badges',
      PAGE_SUBTITLE: 'Accumulate reward points from social interactions to unlock exclusive badges and level up.',
      REFRESH_DATA: 'Refresh data',
      UPDATING: 'Updating...',
      LOADING_DATA: 'Loading gamification data...',
      XP_PROGRESS_LABEL: 'Progress to next level',
      GUEST_TITLE: 'You are not logged in',
      GUEST_DESC: 'Log in to see your level progress, track your reward points, and claim your own badges!',
      LOGIN_NOW: 'Log in now',
      POINTS_BALANCE_LABEL: 'Accumulated points',
      POSTS_COUNT_LABEL: 'posts',
      RULES_TITLE: 'Points scoring rules',
      RULES_DESC: 'Different actions in the community yield different points.',
      ACTIVITY_COL: 'Activity',
      POINTS_COL: 'Scoring factor',
      DESC_COL: 'Description',
      ACT_POST: 'Post a review',
      ACT_POST_DESC: 'Write and publish a dining review post that gets approved.',
      ACT_COMMENT: 'Comment',
      ACT_COMMENT_DESC: 'Write a new comment on another user\'s post.',
      ACT_REPLY: 'Reply to comment',
      ACT_REPLY_DESC: 'Reply to an existing comment.',
      ACT_LIKE: 'Likes',
      ACT_LIKE_DESC: 'Like a food or restaurant review post.',
      ANTI_FARM_WARNING_TITLE: '⚠️ Anti-farming policy (Undo actions)',
      ANTI_FARM_WARNING_BODY: (multiplier: number, likePoints: number) =>
        `When you delete a post, comment, or unlike a post, your points will be deducted using a penalty multiplier of ${multiplier}x. (E.g., liking grants +${likePoints} pts; unliking deducts -${Math.round(likePoints * multiplier)} pts). Please contribute responsibly!`,
      BADGES_SYSTEM_TITLE: 'Badges System',
      BADGES_SYSTEM_DESC: 'Minimum requirements to unlock each badge.',
      TAB_CUSTOMER: 'Diners',
      TAB_RESTAURANT: 'Restaurants',
      USING_BADGE: 'Equipped',
      MIN_POINTS: 'Minimum points:',
      MIN_REVIEWS: 'Minimum reviews:',
      MIN_FOLLOWERS: 'Minimum followers:',
      LEADERBOARD_TITLE: 'Leaderboard',
      LEADERBOARD_SUBTITLE: 'Top 10 outstanding users.',
      LEADERBOARD_TIME_PERIOD: 'This Month',
      EMPTY_LEADERBOARD: 'No user rankings available.',
      YOU_LABEL: 'You',
      RESTAURANT_ROLE_LABEL: 'Restaurant Partner',
      CUSTOMER_ROLE_LABEL: 'Diner',
      POST_UNIT: 'posts',
      USER_UNIT: 'users',
      RANK_TOOLTIP: (rank: number) => `Rank ${rank}`,
    }
  },
  OFFERS: {
    TITLE: 'Offers & Promotions',
    BANNER_BADGE: 'Culinary Deals Frenzy',
    BANNER_TITLE: 'Special Promotions \nFor Today',
    BANNER_DESC: 'Discover super savings combos and deep discount codes from hundreds of partner restaurants recommended specifically for you by FOOD AI.',
    CREATE_BTN: 'Post Promotion',
    DELETE_BTN: 'Delete promotion',
    MERCHANT_ONLY_TITLE: 'For Restaurants',
    MERCHANT_ONLY_DESC: 'Log in with a Merchant account to post promotional deals for your store.',
    FILTER: {
      ALL: 'All',
      DISCOUNT: 'Discount',
      COMBO: 'Best Combos',
      GIFT: 'Free Gift',
      OTHER: 'Other Deals',
    },
    SHOWING_COUNT: (count: number) => `Showing ${count} offers`,
    EMPTY_TITLE: 'No promotions yet',
    EMPTY_DESC: 'There are currently no promotions in this category. Check back later!',
    VALID_UNTIL: (date: string) => `Expires: ${date}`,
    VIEW_STORE: 'View store',
    CONTACT_TOAST: (name: string) => `Contact ${name} to apply this offer!`,
    CREATE_MODAL_TITLE: 'Post Promotional Campaign',
    FORM: {
      TITLE_LABEL: 'Campaign Title',
      TITLE_PLACEHOLDER: 'E.g., Great discount on fried rice...',
      TYPE_LABEL: 'Promotion Type',
      TYPE_OPTIONS: {
        DISCOUNT: 'Discount (%)',
        COMBO: 'Combo Deal',
        GIFT: 'Free Gift',
        OTHER: 'Other Deal',
      },
      VALUE_LABEL: 'Offer Value',
      VALUE_PLACEHOLDER: 'E.g., 30% Off, Buy 1 Get 1 Free...',
      EXPIRY_LABEL: 'Campaign Expiry Date',
      MERCHANT_LABEL: 'Posting Restaurant (Default)',
      MERCHANT_FALLBACK: 'Your Restaurant',
      DESC_LABEL: 'Detailed Campaign Description',
      DESC_PLACEHOLDER: 'Enter details about applicable dishes, conditions, etc...',
      IMAGE_LABEL: 'Select Illustration Image',
      CANCEL: 'Cancel',
      SUBMIT: 'Post Now',
    },
    TOAST: {
      TITLE_REQUIRED: 'Please enter a promotion title!',
      VALUE_REQUIRED: 'Please enter an offer value (e.g. 30% Off, Buy 1 Get 1 Free)!',
      EXPIRY_REQUIRED: 'Please select an expiry date!',
      DESC_REQUIRED: 'Please enter a description!',
      CREATE_SUCCESS: 'Promotion posted successfully!',
      CREATE_ERROR: 'Failed to create promotion!',
      DELETE_CONFIRM: 'Are you sure you want to delete this promotion?',
      DELETE_SUCCESS: 'Promotion deleted successfully!',
      DELETE_ERROR: 'Failed to delete promotion!',
    },
    PROMO_TYPES: {
      DISCOUNT: 'DISCOUNT',
      COMBO: 'COMBO',
      GIFT: 'FREE GIFT',
      OTHER: 'OTHER DEAL',
    },
    DEFAULT_TEMPLATES: [
      { name: 'Pizza & Fastfood', url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80' },
      { name: 'Fried Chicken & Burgers', url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80' },
      { name: 'Noodles & Hotpot', url: 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=600&q=80' },
      { name: 'Drinks & Bubble tea', url: 'https://images.unsplash.com/photo-1541658016709-82535e94bc69?auto=format&fit=crop&w=600&q=80' },
      { name: 'Desserts & Pastries', url: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80' },
    ]
  },
  SOCIAL: {
    FEED_TITLE: 'Culinary Feed',
    FEED_DESC: 'A space to share food reviews, quality restaurant ratings, and fascinating culinary tips from the Food AI community.',
    CREATE_POST: 'Create New Post',
    FEED_EMPTY: 'No posts on the forum yet',
    FEED_EMPTY_DESC: 'Follow other foodies or write reviews to see new posts!',
    SIDEBAR: {
      NEW_MEMBER: 'New member',
      LEVEL: 'Level',
      POINTS: 'Points',
      LEVEL_PROGRESS: 'Level progress',
      JOIN_COMMUNITY: 'Join community',
      JOIN_COMMUNITY_DESC: 'Log in to write posts, like, and discuss with other diners.',
      LOGIN_NOW: 'Log in now',
      LEADERBOARD_TITLE: 'Elite Diners',
      LEADERBOARD_EMPTY: 'No leaderboard available.',
      NEW: 'New',
    },
    POST_TYPE_NORMAL: 'Normal',
    POST_TYPE_REVIEW: 'Restaurant Review',
    POST_TYPE_PROMOTION: 'Promotion',
    SELECT_POST_TYPE: 'Select Post Type',
    TITLE_LABEL: 'Post Title',
    TITLE_PLACEHOLDER: 'Post title...',
    CONTENT_LABEL: 'Post Content',
    CONTENT_PLACEHOLDER: 'What are you thinking? Share your dining experience...',
    IMAGE_LABEL: 'Post Image (URL)',
    IMAGE_URL_PLACEHOLDER: 'Post Image URL (optional)...',
    NO_LINK_OPTION: '-- No link --',
    RATING: 'Rating:',
    SELECT_RESTAURANT: 'Link Restaurant (optional)',
    SELECT_FOOD: 'Link Food Item (optional)',
    SUBMIT_POST: 'Post',
    LIKE: 'Like',
    UNLIKE: 'Unlike',
    COMMENT_PLACEHOLDER: 'Write a comment...',
    TOGGLE_COMMENTS: 'View comments',
    REPORT_COMMENT: 'Report comment',
    NO_COMMENTS: 'No comments yet. Be the first!',
    SEND_COMMENT: 'Send',
    REPORT: 'Report',
    COMMENTS_TITLE: 'Comments',
    POST_SUCCESS: 'Post created successfully!',
    COMMENT_SUCCESS: 'Comment posted!',
    LIKE_SUCCESS: 'Liked post!',
    UNLIKE_SUCCESS: 'Unliked post!',
    TITLE_REQUIRED: 'Please enter a post title.',
    CONTENT_REQUIRED: 'Please enter post content.',
    AUTHOR_FALLBACK: 'You',
    SHARED_BADGE: 'Shared',
    SHARE: 'Share',
    PINNED_BADGE: '📌 Pinned',
    EDIT_POST_TITLE: 'Edit post',
    REPLY: 'Reply',
    REPLY_PLACEHOLDER: (userName: string) => `Reply to ${userName}...`,
    SEND: 'Send',
    DELETE_REPLY: 'Delete reply',
    DELETE_COMMENT: 'Delete comment',
    RATING_STAR: (star: number) => `Rate ${star} star${star > 1 ? 's' : ''}`,
    TOAST: {
      ACTION_DONE: (action: string) => `Action performed: ${action}`,
      SAVE_SUCCESS: 'Post saved successfully to your collection!',
      UNSAVE_SUCCESS: 'Post removed from your collection!',
      LOGIN_REQUIRED: 'Please login to perform this function!',
      TITLE_REQUIRED: 'Please enter a post title.',
      CONTENT_REQUIRED: 'Please enter post content.',
      POST_SUCCESS: 'Post created successfully!',
      COMMENT_SUCCESS: 'Comment posted!',
      LIKE_SUCCESS: 'Liked post!',
      UNLIKE_SUCCESS: 'Unliked post!',
      CONTACT_TOAST: (name: string) => `Contact ${name} to apply this offer!`,
      INTERACTION_ERROR: 'Failed to perform interaction!',
      COMMENT_ERROR: 'Failed to post comment!',
      SHARE_SUCCESS: 'Post shared to your profile successfully!',
      SHARE_ERROR: 'Failed to share post!',
      COMMENT_DELETE_SUCCESS: 'Comment deleted successfully!',
      COMMENT_DELETE_ERROR: 'Failed to delete comment!',
      REPLY_SUCCESS: 'Reply posted successfully!',
      REPLY_ERROR: 'Failed to post reply!',
      REPLY_DELETE_SUCCESS: 'Reply deleted successfully!',
      REPLY_DELETE_ERROR: 'Failed to delete reply!',
      LOGIN_REQUIRED_SHARE: 'Please login to share this post!',
      POST_DELETE_CONFIRM: 'Are you sure you want to delete this post? This action will deduct your reward points.',
      COMMENT_DELETE_CONFIRM: 'Are you sure you want to delete this comment? This action will deduct your reward points.',
      REPLY_DELETE_CONFIRM: 'Are you sure you want to delete this reply? This action will deduct your reward points.',
      POST_DELETE_SUCCESS: 'Post deleted successfully!',
      POST_DELETE_ERROR: 'Failed to delete post!',
      SAVE_ERROR: 'Failed to save post',
      MUTE_ON: 'Turned on notifications for this post.',
      MUTE_OFF: 'Turned off notifications for this post.',
      TRANSLATE_ON: 'Turned on auto translation.',
      TRANSLATE_OFF: 'Turned off translation for this post.',
      REFRESH_ATTACHMENT_DOING: 'Refreshing attachment...',
      REFRESH_ATTACHMENT_DONE: 'Attachment refreshed.',
      COPY_LINK_SUCCESS: 'Post link copied to clipboard.',
      COPY_LINK_ERROR: 'Error occurred while copying link.',
      PIN_SUCCESS: 'Pinned post to top of profile.',
      UNPIN_SUCCESS: 'Unpinned post.',
      PIN_ERROR: 'Failed to pin post. Please try again.',
      UPDATE_SUCCESS: 'Post updated successfully!',
      UPDATE_ERROR: 'Failed to update post. Please try again.',
    },
    DROPDOWN: {
      PIN: 'Pin post',
      UNPIN: 'Unpin post',
      EDIT: 'Edit post',
      EDIT_AUDIENCE: 'Edit audience',
      MUTE: 'Turn off notifications for this post',
      SHARE_PROMO: 'Share co-op promo code',
      UNTRANSLATE: 'Turn off translation',
      EDIT_DATE: 'Edit date',
      REFRESH_ATTACHMENT: 'Refresh shared attachment',
      SAVE: 'Save post',
      UNSAVE: 'Unsave post',
      REPORT: 'Report post',
      DELETE: 'Delete post',
      UNMUTE: 'Turn on notifications',
      TRANSLATE: 'Turn on translation',
      EMBED: 'Embed post',
      COPY_LINK: 'Copy link',
      LABEL: 'Post options',
    },
    NOTIFICATIONS: {
      LIKE_TITLE: 'Post Liked',
      LIKE_BODY: (name: string, title: string) => `${name} liked your post: "${title}"`,
      COMMENT_TITLE: 'Post Commented',
      COMMENT_BODY: (name: string, title: string) => `${name} commented on your post: "${title}"`,
      REPLY_TITLE: 'Comment Replied',
      REPLY_BODY: (name: string, title: string) => `${name} replied to your comment on post: "${title}"`,
      SHARE_TITLE: 'Post Shared',
      SHARE_BODY: (name: string, title: string) => `${name} shared your post: "${title}"`,
    }
  },
  MODERATION: {
    TITLE: 'Content Moderation',
    PENDING_REPORTS: 'Report Moderation Queue',
    TARGET_TYPE: 'Target Type:',
    TARGET_ID: 'Target ID:',
    REPORT_REASON: 'Report Reason:',
    STATUS_PENDING: 'Pending',
    STATUS_RESOLVED: 'Removed',
    STATUS_REJECTED: 'Dismissed',
    ACTION_APPROVE: 'Remove Post',
    ACTION_REJECT: 'Dismiss Report',
    NO_REPORTS: 'No reports to process.',
    RESOLVE_SUCCESS: 'Report processed successfully.',
    REPORT_SUBMITTED: 'Report submitted. Thank you for your feedback!',
    TOAST_REPORT_ERROR: 'Failed to submit report!',
    RESOLVE_ERROR: 'Failed to resolve report!',
    DISMISS_ERROR: 'Failed to dismiss report!',
    REPORT_TITLE: 'Report Content Violation',
    REPORT_REASON_LABEL: 'Describe reason for reporting:',
    REPORT_MAIN_REASON_LABEL: 'Main Reason',
    REPORT_DETAILS_PLACEHOLDER: 'Enter additional details here (optional)...',
    REPORT_BANNER: 'Your report will be reviewed by the Food AI moderation team. Please select an accurate reason to help us build a safe culinary community.',
    DEFAULT_REPORT_CONTENT: 'Content violation report',
    REPORT_SUBMIT: 'Submit Report',
    REPORT_REASONS: [
      'Spam / Junk advertising',
      'Hate speech / Offensive language',
      'Inappropriate / Sensitive content',
      'Misinformation / Fraud',
      'Non-existent food or restaurant',
      'Other reason (Describe below)',
    ],
    REPORT_OTHER_PREFIX: 'Other reason',
    REPORT_DETAIL_PREFIX: ' - Details: ',
    REJECT_SUCCESS: 'Report dismissed. Content has been kept unchanged.',
    CLEAN_STATE_DESC: 'Your system is clean and safe. ✨',
    NOTIFICATIONS: {
      CONTENT_REMOVED_TITLE: 'Content removed',
      POST_REMOVED_BODY: (title: string) => `Your post "${title}" has been removed for violating community guidelines.`,
      COMMENT_REMOVED_BODY: (postTitle: string) => `Your comment on post "${postTitle}" has been removed for violating community guidelines.`,
      REPORT_RESOLVED_TITLE: 'Report processed',
      REPORT_RESOLVED_BODY: (targetType: string, id: number) => `Your report about ${targetType === 'POST' ? 'post' : 'comment'} #${id} has been processed: The violating content has been removed.`,
      REPORT_DISMISSED_BODY: (targetType: string, id: number) => `Your report about ${targetType === 'POST' ? 'post' : 'comment'} #${id} has been reviewed: No violations found.`,
    }
  },
  ANALYTICS: {
    TITLE: 'Merchant Statistics & Analytics',
    VIEWS: 'Dish Views',
    RECOMMENDATIONS: 'AI Suggestions Counter',
    AI_CONVERSION_RATE: 'AI Conversion Rate',
    AI_INSIGHTS: 'Automated Business Insights by AI Assistant',
    TIME_PERIOD: 'Timeframe: Last 30 days',
    CHART_TITLE: 'Correlation: Views vs AI Recommendations Frequency',
    CHART_TOOLTIP_VIEWS: 'Views',
    CHART_TOOLTIP_AI: 'AI Suggestions',
    INSIGHT_TIPS: [
      'Your top performing dish is suggested most by AI thanks to steady page views.',
      'Optimize descriptions and images of low-view foods to boost AI recommendation rates.',
      'Customers lean towards ordering "Promotion" dishes during lunch hours (11 AM - 1 PM).',
    ],
    EMPTY_TITLE: 'No analytics data yet',
    EMPTY_DESC: 'Add dishes to your menu to start tracking views and suggestions.',
    ERROR_OCCURRED: 'An error occurred',
    COMPARE_SELECT_TITLE: 'Select dishes to compare (Max 8 dishes)',
    COMPARE_SELECT_ARIA: 'Comparison dishes list',
    CHART_EMPTY_COMPARE: 'Please select at least one dish from the list below to compare on the chart.',
    CHART_SVG_TITLE: 'Double bar chart comparing views and AI recommendations',
    CHART_ARIA_LABEL: 'Comparison chart of views and AI recommendations for dishes',
    CHART_GROUP_ARIA: (name: string) => `Dish ${name}`,
    CHART_BAR_VIEWS_ARIA: (name: string, views: number) => `${name}: ${views} views`,
    CHART_BAR_AI_ARIA: (name: string, aiSuggestions: number) => `${name}: ${aiSuggestions} AI recommendations`,
    ERROR_FETCH_FAILED: 'Failed to load statistics from system.',
    TOAST_MAX_SELECTION: 'You should only select up to 8 dishes for the best chart visualization!',
    LOADING_ARIA: 'Loading statistics data',
  },
  BUG_REPORT: {
    TITLE: 'Bug Report Form',
    SUBTITLE: 'Encountered an issue? Send us a bug report so we can fix it!',
    CATEGORY: 'Issue Category',
    DESC: 'Detailed Description',
    DESC_PLACEHOLDER: 'Please describe the bug in detail and steps to reproduce (if any)...',
    IMAGE: 'Issue Screenshot (URL)',
    IMAGE_PLACEHOLDER: 'Paste a screenshot URL of the issue (optional)...',
    SUBMIT: 'Submit Bug Report',
    SUCCESS: 'Bug report submitted successfully! Our technical team will review it.',
    DESC_TOO_SHORT: 'Issue description must be at least 10 characters.',
    SUBMIT_ERROR: 'An error occurred while submitting the bug report',
    CATEGORIES: {
      AI: 'AI / Chat Suggestions Bug',
      UI: 'Display / Layout UI Bug',
      PERFORMANCE: 'System Performance / Slow Response',
      OTHER: 'Other Issues',
    },
  },
  TERMS_PAGE: {
    SUBTITLE: 'Please read the terms of service of Food AI carefully to ensure the best experience for the community.',
    SEC1_TITLE: '1. Terms of Service',
    SEC1_DESC: 'By accessing and using the Food AI application, you agree to comply with these terms. Our service provides automatic food recommendations based on artificial intelligence (AI) analysis.',
    SEC2_TITLE: '2. User Rights and Responsibilities',
    SEC2_DESC: 'You are responsible for maintaining the confidentiality of your login account information. You must not use the platform to post illegal, offensive, defamatory, or incorrect information about food establishments.',
    SEC3_TITLE: '3. Limitation of Liability',
    SEC3_DESC: 'AI suggestions are for reference only. We strive to provide accurate information about menus, prices, and locations, but we do not fully guarantee the actual quality of food at our partners.',
    SEC4_TITLE: '4. Modification of Terms',
    SEC4_DESC: 'Food AI reserves the right to update and modify these regulations at any time without prior notice. Continued use of the application after updates implies acceptance of those changes.',
  },
  POLICY_PAGE: {
    SUBTITLE: "Food AI is committed to protecting the privacy and security of users' personal data across all platforms.",
    SEC1_TITLE: '1. Data We Collect',
    SEC1_DESC: 'We collect basic information when you register an account (name, email) and your culinary preferences from the onboarding survey to train the personalized AI recommendation models.',
    SEC2_TITLE: '2. Information Security',
    SEC2_DESC: 'All passwords and account information are one-way encrypted using a high-level security algorithm (bcrypt) on the back-end to protect against data theft attacks.',
    SEC3_TITLE: '3. Artificial Intelligence (AI) Applications',
    SEC3_DESC: 'Your food consultation chat records with the AI assistant are saved to improve chatbot accuracy and food suggestions fitting your real context.',
    SEC4_TITLE: '4. Your Data Rights',
    SEC4_DESC: 'You have full rights to edit your personal profile or request permanent deletion of your account and all AI consultation history directly from the Settings panel.',
    SEC5_TITLE: '5. Information Sharing',
    SEC5_DESC: 'We do not sell or share your personal information with third parties for commercial purposes. Your geolocation information (City/District) is only used locally or sent anonymously to the mapping API to display distances to nearby restaurants.',
    SEC6_TITLE: '6. Compliance Commitment',
    SEC6_DESC: 'The platform is committed to strictly complying with current legal regulations on cybersecurity and personal data protection for consumers in Vietnam.',
  },
  CONTACT_PAGE: {
    SUBTITLE: 'For any inquiries, partnership proposals, or system reports, please send us a message or contact us using the information below.',
    INFO_TITLE: 'Contact Information',
    INFO_DESC: 'Our support team is ready to respond and assist you within 24 business hours.',
    OFFICE_LABEL: 'Address',
    OFFICE_VAL: 'Hanoi, Vietnam',
    CONTACT_PERSON_LABEL: 'Representative',
    CONTACT_PERSON: 'Nguyen Tien Dat',
    PHONE_LABEL: 'Phone',
    PHONE_VAL: '0559446557',
    EMAIL_LABEL: 'Contact Email',
    EMAIL_VAL: 'datnguyenforcode557@gmail.com',
    WORKING_HOURS: 'Working Hours: Monday - Friday, 8:00 AM - 5:30 PM',
    FORM_TITLE: 'Send a Direct Message',
    INPUT_NAME: 'Your full name',
    INPUT_NAME_PLACEHOLDER: 'John Doe',
    INPUT_EMAIL: 'Email Address',
    INPUT_MESSAGE: 'Message content',
    INPUT_MESSAGE_PLACEHOLDER: 'Enter your questions or feedback here...',
    SUBMIT_BTN: 'Submit Contact',
    SUBMIT_BTN_LOADING: 'Sending...',
    FORM_ERROR_FILL: 'Please fill in all fields!',
    FORM_SUCCESS_MSG: 'Thank you! Your message has been sent successfully.',
  }
};
