// Mục đích: Khai báo đối tượng hằng số LABELS_EN chứa toàn bộ văn bản hiển thị (UI text) tiếng Anh.
// Các file khác hay file này có ý nghĩa như nào: Cung cấp bản dịch tiếng Anh để labels.ts truy xuất động dựa trên cấu hình ngôn ngữ.
// Các chức năng đặc biệt: Định nghĩa bản dịch cho toàn bộ giao diện (Common, Navigation, Settings, Restaurant, AI Chat...).
// Kiến thức, Design Pattern, nguyên tắc (SOLID, OOP...) đang được áp dụng trong file: Constant pattern, Namespace grouping, Localization/i18n.
// Các biến, hàm đặc biệt trong file: LABELS_EN.
export const LABELS_EN = {
  COMMON: {
    SAVE: 'Save changes',
    CANCEL: 'Cancel',
    DELETE: 'Delete',
    EDIT: 'Edit',
    APPROVE: 'Approve',
    REJECT: 'Reject',
    LOGOUT: 'Logout',
    BACK_HOME: 'Back to home',
    LOADING: 'Loading...',
    SUCCESS: 'Success',
    ERROR: 'Error',
    NEXT: 'Next',
    BACK: 'Back',
    SEARCH: 'Search...',
    OTHER: 'Other...',
    APP_TITLE: 'FOOD AI - Daily Delicious Dishes',
    PROCESSING: 'Processing...',
    DEVELOPING: 'Feature under development',
    DEVELOPING_DESC: 'We are developing this feature. Please come back later! ✨',
    SEE_MORE: 'See more',
    UNNAMED: 'Unnamed',
    SCROLL_LEFT: 'Scroll left',
    SCROLL_RIGHT: 'Scroll right',
    TOGGLE_THEME: 'Toggle light/dark theme',
    CLOSE: 'Close',
    AI_BUSY: 'Sorry, AI is busy. Please try again later!',
    UNKNOWN: 'Unknown',
    BRAND_NAME: 'Food AI',
    BRAND_LOGO_ALT: 'Food AI Logo',
    AI_ASSISTANT_NAME: 'Food AI Assistant',
    USER: 'User',
    STORE: 'Store',
    PAGINATION: {
      PREVIOUS: 'Previous page',
      NEXT: 'Next page',
      JUMP_TO_PAGE: 'Jump to page',
    },
  },
  AUTH: {
    LOGIN: 'Login',
    REGISTER: 'Register',
    ADMIN: 'Administrator',
    RESTAURANT_ROLE: 'Restaurant Owner',
    PROFILE: 'Personal Profile',
    LOGIN_TITLE: 'Login',
    LOGIN_SUBTITLE: 'Welcome back to FoodAI',
    PASSWORD: 'Password',
    OR_LOGIN_WITH: 'Or login with',
    SOCIAL_GOOGLE: 'Google',
    SOCIAL_FACEBOOK: 'Facebook',
    FORGOT_PASSWORD: 'Forgot password?',
    NO_ACCOUNT: 'Don\'t have an account?',
    REGISTER_NOW: 'Register now',
    REGISTER_TITLE: 'Create Account',
    REGISTER_SUBTITLE: 'Start your smart culinary journey',
    WHO_ARE_YOU: 'Who are you?',
    CUSTOMER: 'Customer',
    RESTAURANT: 'Restaurant',
    CONFIRM_PASSWORD: 'Confirm Password',
    LEGAL_DOCS: 'Legal Documents / Verification Info',
    LEGAL_DOCS_PLACEHOLDER: 'Business license number or document image link...',
    AGREE_TERMS: 'I agree to the privacy terms and terms of use.',
    ALREADY_HAVE_ACCOUNT: 'Already have an account?',
    VERIFY_ACCOUNT: 'Verify Account',
    LOGIN_GO: 'Go to Login',
    REGISTER_SUCCESS_PENDING: 'Registration successful! Pending Admin approval.',
    REGISTER_SUCCESS_VERIFY: 'Registration successful! Please verify your account.',
    LOGIN_REQUIRED: 'Please login to perform this function!',
  },
  RESTAURANT: {
    DASHBOARD_TITLE: 'Welcome back!',
    MENU_MANAGEMENT: 'Menu Management',
    AI_HISTORY: 'AI Suggestion History',
    SUBTITLE: 'Your store is doing very well ✨',
    MERCHANT_HUB: 'Merchant Hub',
    STATUS: 'Status',
    ADD_FOOD: 'Add New Food',
    RECENT_ACTIVITY: 'Recent Activity',
    DELETE_BRANCH: 'Delete Branch',
    BRANCH_NUMBER: (num: number) => `📍 Branch ${num}`,
    VIEW_INSIGHT: 'View detailed insights',
    VIEW_AS_GUEST: 'View as guest',
    NO_FOOD: 'No food items yet.',
    SAVE_SUCCESS_EDIT: 'Saved! Pending Admin approval.',
    SAVE_SUCCESS_ADD: 'Posted! Pending Admin approval.',
    AI_SUGGESTION_TITLE: 'AI Suggestions for Store',
    AI_SUGGESTION_DESC: 'Dish "Pho Cuon" is trending. Would you like to add it to the menu?',
    STATUS_OPEN: 'Open',
    STATUS_CLOSED: 'Closed temporarily',
    STATUS_TOOLTIP: 'When closed temporarily, all your food items will be hidden from search results and recommendations.',
    SETTINGS_TITLE: 'Store Settings',
    OPERATING_HOURS: 'Operating Hours',
    CONTACT_PHONE: 'Contact Phone',
    SAVE: 'Save',
    STATUS_OPEN_SUCCESS: 'Store is now open for customers.',
    STATUS_CLOSE_SUCCESS: 'Store has been closed temporarily.',
    STATUS_UPDATE_ERROR: 'Unable to update store status.',
    DELETE_FOOD_CONFIRM: 'Are you sure you want to delete this food item from the menu? It will be hidden and no longer visible to guests.',
    DELETE_FOOD_CONFIRM_TITLE: 'Confirm Food Deletion',
    HOURS_UPDATE_SUCCESS: 'Operating hours updated successfully.',
    HOURS_UPDATE_ERROR: 'Unable to update operating hours.',
    CLOSED_WARNING_TITLE: 'Store is temporarily closed',
    CLOSED_BY_MERCHANT: 'Restaurant has temporarily closed.',
    CLOSED_OUTSIDE_HOURS: (hours: string) => `Outside operating hours (${hours}).`,
    NOT_SET: 'not set',
    OPERATING_HOURS_LABEL: 'Operating Hours',
    HOURS_PLACEHOLDER: 'E.g., 08:00 - 22:00',
    HOURS_FORMAT_ERROR: 'Operating hours format is invalid (Correct e.g.: 08:00 - 22:00).',
    EDIT_STORE: 'store',
    TABS: {
      OVERVIEW: 'Overview',
      CATEGORIES: 'Categories',
      MENU: 'My Menu',
      HISTORY: 'Suggestion History',
    },
    EDIT_MODAL: {
      LIVE_PREVIEW: 'Live Card Preview',
      VERIFIED: 'Verified',
      BIO_PLACEHOLDER: 'Short introduction of the restaurant...',
      NOT_OPENED: 'Not opened',
      TIP: 'Changes to Logo and Cover images will update immediately on the Explore grid and public profile.',
      SUBTITLE: 'Customize brand details and contact info of the store',
      TAB_INFO: 'Basic Info',
      TAB_IMAGES: 'Brand Images',
      TAB_CONTACT: 'Contact & Operation',
      NAME_LABEL: 'Restaurant Name',
      NAME_PLACEHOLDER: 'E.g., FOOD AI - Dong Da Branch',
      NAME_REQUIRED: 'Please enter restaurant name',
      BIO_LABEL: 'Short bio',
      BIO_INPUT_PLACEHOLDER: 'Clean food, pure nature...',
      DESC_LABEL: 'Detailed Description',
      DESC_PLACEHOLDER: 'Describe your menu and style in detail...',
      LOGO_LABEL: 'Logo URL',
      LOGO_PLACEHOLDER: 'https://example.com/logo.png',
      SYNC_AVATAR: 'Synchronize this logo as your personal avatar',
      COVER_LABEL: 'Cover Image URL',
      COVER_PLACEHOLDER: 'https://example.com/cover.png',
      SYNC_COVER: 'Synchronize this cover image as your personal cover image',
      CITY_LABEL: 'City / Province',
      DISTRICT_LABEL: 'District',
      ADDRESS_LABEL: 'Detailed Address',
      ADDRESS_PLACEHOLDER: 'E.g., 123 Duong Lang, Lang Thuong',
      HOURS_LABEL: 'Operating hours (HH:MM - HH:MM)',
      PHONE_LABEL: 'Contact Phone Number',
      PHONE_PLACEHOLDER: '0987654321',
      EMAIL_LABEL: 'Contact Email',
      EMAIL_PLACEHOLDER: 'contact@quanphobac.com',
      MAPS_LABEL: 'Google Maps Link',
      MAPS_PLACEHOLDER: 'https://maps.app.goo.gl/...',
      CANCEL: 'Cancel',
      SUBMIT: 'Save Settings',
      SAVING: 'Saving...',
      SAVE_ERROR: 'Error updating restaurant details',
      CONFIRM_TITLE: 'Confirm Settings Save',
      CONFIRM_DESC: 'Are you sure you want to save these changes for the store?',
      CLOSE_SETTINGS: 'Close store settings',
    },
    CARD_LABELS: {
      DEFAULT_BIO: 'We are pleased to serve you premium delicious dishes.',
      FOLLOWERS_SUFFIX: 'followers',
      FOODS_SUFFIX: 'food items',
      DEFAULT_LOCATION: 'Vietnam',
      DEFAULT_CATEGORY: 'Restaurant',
    },
    TABLE: {
      FOOD: 'Food Item',
      STATUS: 'Status',
      ACTION: 'Action',
      FEATURE: 'Featured',
      RECOMMEND: 'Recommended',
    },
    MODAL: {
      ADD_TITLE: 'Post New Food',
      EDIT_TITLE: 'Edit Food Item',
      SUBMIT_ADD: 'Post Food Now',
      SUBMIT_EDIT: 'Save Changes',
      BRANCH_LABEL: 'Business Branch',
      BRANCH_PLACEHOLDER: '-- Select Branch --',
      CATEGORY_LABEL: 'Food Category (Optional)',
      CATEGORY_PLACEHOLDER: '-- Uncategorized --',
      AUTO_FILL_BRANCH: '(Auto-filled by branch)',
      AUTO_FILL_LAT_LNG: '(Auto-filled)',
    },
    PUBLIC_PROFILE: {
      NOT_FOUND: 'Restaurant not found',
      NOT_FOUND_DESC: 'Invalid link or the business has stopped operating.',
      MENU_TAB: 'Food Menu',
      INFO_TAB: 'Restaurant Info',
      EMPTY_MENU: 'Menu is empty',
      EMPTY_MENU_DESC: 'The restaurant has not published any approved food items yet.',
      DETAIL_INFO: 'Detailed Information',
      NO_HOURS: 'Operating hours not configured',
      NO_PHONE: 'Phone number not configured',
      CONTACT_EMAIL: 'Contact Email',
      MAP_TITLE: 'Google Maps Location',
      MAP_OPEN: 'Open location on Google Maps',
      BIO_TITLE: 'About Us',
      BIO_EMPTY: 'The restaurant has not updated its introduction details.',
      FOLLOWERS_TITLE: 'Current Followers',
      FOLLOWERS_EMPTY: 'No followers yet.',
      FOLLOWING_TITLE: 'Following restaurants',
      FOLLOWING_EMPTY: 'Not following any restaurants.',
      LOGIN_REQUIRED: 'Please login to perform this action',
      FOLLOWERS_PRIVATE: 'Follower list is hidden by owner',
      FOLLOWING_PRIVATE: 'Following list is hidden by owner',
      LOAD_ERROR: 'Failed to load list',
      VIEWING_AS_GUEST: 'You are viewing your own store as guest.',
      PRIVACY_TITLE: '🔒 Privacy Settings',
      PRIVACY_LABEL: 'Show followers/following list',
      PRIVACY_DESC: 'Toggle visibility of followers and following lists on your page.',
      PRIVACY_SUCCESS: 'Privacy settings updated successfully!',
      PRIVACY_ERROR: 'Error updating privacy settings.',
      MENU_CATEGORIES: 'Menu Categories',
      COLLAPSE_CATEGORY: 'Collapse Category',
      EXPAND_CATEGORY: 'Expand Category',
      ALL_FOODS: 'All Dishes',
      LOADING_FOODS: 'Loading dishes...',
      LOADING_MORE: 'Loading...',
      LOAD_MORE: 'See more dishes',
      GO_TO_ADMIN: '[Go to Admin Panel]',
      MANAGE_RESTAURANT: 'Manage Restaurant',
      CATEGORY_MANAGER: {
        TITLE: 'Groups & Categories',
        LOADING: 'Loading categories...',
        HELP_TOOLTIP: 'Group is the root folder. Once created, click [+] on it to create child Categories inside.',
        ADD_GROUP: 'Add New Group',
        GUIDE_TITLE: '💡 Categorizing Guide:',
        GUIDE_GROUP: 'Category Group (E.g.: Drinks): You can assign food items directly to this Group.',
        GUIDE_CATEGORY: 'Sub-category (E.g.: Milk tea, Juice): If you want more details, click [+] on Group to create a Sub-category, then assign food items to it.',
        PRIORITY_PREFIX: 'Display Priority Order: #',
        PRIORITY_SHORT: 'Priority: #',
        ADD_ROOT_CATEGORY: 'Add Root Category',
        ADD_SUB_CATEGORY: 'Add Sub-category',
        EMPTY_GROUP_NOTE: '📌 You can assign food items directly to this group, or click [+] to create a sub-category.',
        EMPTY_GROUPS: 'No groups yet',
        EDIT_GROUP: 'Edit Group',
        GROUP_NAME: 'Group Name',
        DISPLAY_ORDER: 'Display Order',
        ORDER_DESC_GROUP: 'Used for sorting display positions on Menu. Smaller numbers have higher priority. E.g., 0 ranks first, 1 ranks second.',
        GROUP_PLACEHOLDER: 'E.g., Mains, Drinks...',
        EDIT_CATEGORY: 'Edit Category',
        ADD_CATEGORY: 'Add Category',
        CATEGORY_NAME: 'Category Name',
        CATEGORY_PLACEHOLDER: 'E.g., Rice, Juices...',
        ORDER_DESC_CATEGORY: 'Used for sorting display positions on Menu. Smaller numbers have higher priority.',
        CONFIRM_DELETE_TITLE: 'Confirm Deletion',
        CONFIRM_DELETE_MESSAGE: (type: string) => `Are you sure you want to delete this ${type}? All sub-categories inside will also be deleted!`
      }
    },
    UPLOAD_EXCEL: {
      MAIN_GROUP: '📁 Main Group',
      COLS: {
        NAME: 'Food Name',
        PRICE: 'Price',
        DESC: 'Description',
        IMAGE: 'Image',
        TAGS: 'Tags'
      },
      FILE_NAME: 'sample-food-template.xlsx',
      SHEET_NAME: 'Food List',
      DOWNLOAD_SUCCESS: 'Sample file downloaded!',
      READ_SUCCESS: (count: number) => `Successfully read ${count} food items from file!`,
      READ_ERROR: 'Error reading Excel file. Please check format.',
      INVALID_DATA: 'No valid data found. Check column headers and data.',
      BRANCH_REQUIRED: 'Please select branch to apply',
      EMPTY_DATA: 'Empty or invalid data',
      UPLOAD_SUCCESS: (count: number) => `Successfully added ${count} food items!`,
      UPLOAD_ERROR: 'Error uploading data to system.',
      TITLE: 'Upload Excel',
      GUIDE_TITLE: 'Excel Upload Guide:',
      DOWNLOAD_BTN: 'Download Sample',
      STEP_1: 'Step 1: Select branch',
      STEP_2: 'Step 2: Select category',
      STEP_3: 'Step 3: Select Excel file',
      SELECT_BRANCH: '-- Select Branch --',
      SELECT_CATEGORY: '-- Uncategorized (skip) --',
      NO_CATEGORY_WARN: '⚠ This branch has no categories. Go to "Categories" tab to create one first.',
      LOADING_CATEGORY: 'Loading categories...',
      PREVIEW_TITLE: (count: number) => `Preview Data (${count} items)`,
      SAVING: 'Processing...',
      SAVE_BTN: (count: number) => `Save ${count > 0 ? count + ' items' : ''} to System`,
      OPTIONAL: '(Optional)',
      GUIDES: {
        COLS_INFO: 'Excel file must have exactly these columns:',
        REQUIRED_INFO: (col1: string, col2: string) => `${col1} and ${col2} are required columns.`,
        TAGS_INFO: 'enter multiple values separated by commas (e.g. Snacks, Drinks).',
        NO_FILE: 'No file yet? Download sample file, fill in, and upload.',
      }
    }
  },
  ADMIN: {
    PANEL_TITLE: 'Admin Panel',
    APPROVE_MERCHANTS: 'Approve Merchants',
    MANAGE_MERCHANTS: 'Manage Merchants',
    MANAGE_CUSTOMERS: 'Manage Customers',
    MANAGE_MENU: 'Manage Menus',
    IMPORT_EXCEL: 'Import Excel',
    SYSTEM_FOOD: 'System Foods',
    MERCHANT_FOOD: 'Merchant Foods',
    BATCH_SAVE: 'Save',
    BATCH_CANCEL: 'Cancel',
    DESELECT_ALL: 'Deselect all',
    BATCH_SAVE_ALL: 'Save changes',
    BATCH_CANCEL_ALL: 'Cancel changes',
    UNSAVED_CHANGES: (count: number) => `You have ${count} unsaved changes on partner menus.`,
    EDIT_MODE_LABEL: 'Edit',
    VIEW_MODE_LABEL: 'View',
    FILTER_ALL: 'All',
    FILTER_RECOMMENDED: 'Recommended',
    FILTER_UNRECOMMENDED: 'Not Recommended',
    SOURCE_PARTNER: 'Partner',
    DONE: 'Completed',
    SAVE_SUCCESS: 'Updated successfully!',
    DELETE_SUCCESS: 'Deleted successfully!',
    FEATURE_TODAY_ON: 'Enabled Today\'s Featured',
    FEATURE_TODAY_OFF: 'Disabled Today\'s Featured',
    FEATURE_WEEKLY_ON: 'Enabled Weekly Featured',
    FEATURE_WEEKLY_OFF: 'Disabled Weekly Featured',
    RECOMMEND_ON: 'Enabled Recommendations',
    RECOMMEND_OFF: 'Disabled Recommendations',
    UPDATE_FAILED: 'Update failed',
    DELETE_WARNING: 'Are you sure you want to delete this account?',
    CONFIRM_DELETE_USER: 'Are you sure you want to delete this account?',
    MODAL: {
      EDIT_TITLE: 'Edit Food Item',
      FOOD_NAME: 'Food Name',
      PRICE: 'Price (VND)',
      TAGS: 'Tags',
      IMAGE_URL: 'Image URL',
      DESCRIPTION: 'Description',
    },
    TABLE: {
      NAME: 'Account Name',
      FOOD_NAME: 'Food Name',
      SOURCE: 'Source',
      EMAIL: 'Email',
      PRICE: 'Price',
      DATE: 'Registration Date',
      ACTION: 'Action',
      EMPTY: 'No data found.',
      FEATURE_TODAY: 'Today\'s Specials',
      FEATURE_WEEKLY: 'Weekly Specials',
      ADMIN_RECOMMEND: 'Admin Pick',
      SHOWING_FOODS: (count: number) => `Showing ${count} food items`,
      SHOWING_RESTAURANTS: (count: number) => `Showing ${count} restaurants`,
      SHOWING_REQUESTS: (count: number) => `Showing ${count} requests`,
      SHOWING_ACCOUNTS: (count: number) => `Showing ${count} accounts`,
      DRAFT: 'Draft',
    },
    CONFIRM: {
      DELETE_USER: 'Are you sure you want to delete this account?',
      DELETE_FOOD: 'Are you sure you want to delete this food item?',
      DELETE_FOOD_DESC: 'This action cannot be undone. This food item will be deleted permanently.',
      DELETE_USER_DESC: 'This action cannot be undone. This user will be deleted permanently.',
      BATCH_SAVE: 'Confirm save changes?',
      BATCH_SAVE_DESC: 'Are you sure you want to apply all draft changes to partner menus?',
      BATCH_DISCARD: 'Confirm discard changes?',
      BATCH_DISCARD_DESC: 'All current draft changes on partner menus will be discarded. This cannot be undone. Confirm discard?',
      APPROVE_FOOD: 'Confirm Food Approval',
      APPROVE_FOOD_DESC: (name: string) => `Are you sure you want to approve food item "${name}"? It will immediately show on the customer menu.`,
      REJECT_FOOD: 'Confirm Food Rejection',
      REJECT_FOOD_DESC: (name: string) => `Are you sure you want to reject food item "${name}"? It will be hidden from the public menu.`,
      SAVE_FOOD: 'Confirm Food Save',
      SAVE_FOOD_DESC: 'Are you sure you want to save these changes for the food item?',
    },
    PENDING_APPROVAL: 'PENDING',
    VIEW_MODE: {
      TABLE: 'Table',
      ROW: 'Row (1x1)',
      TITLE_TABLE: 'View table',
      TITLE_ROW: 'View rows',
      TITLE_GRID: 'View grid',
    },
    LEGAL_DOCS: (docs: string) => `Legal documents: ${docs}`,
    REGISTER_DATE: (date: string) => `Registered: ${date}`,
    JOIN_DATE: (date: string) => `Joined: ${date}`,
  },
  CUSTOMER: {
    GREETING: (name: string) => `Hello, ${name}! 👋`,
    SUBTITLE: 'Would you like some AI food recommendations for lunch today?',
    FAVORITES: 'Favorites',
    FAVORITE_UPDATE_ERROR: 'Unable to update favorites list.',
    AI_SUGGESTION: 'AI Suggestions for You',
    AI_SUGGESTION_DESC: (food: string) => `Based on your history, we suggest ${food} for today.`,
    RECENT_FOODS: 'Recently Viewed',
    RECENT_FOODS_DESC: (limit: number) => `Your ${limit} most recently viewed food items`,
    RECENT_FOOD_SUGGEST: (days: number) => `AI suggested ${days} days ago`,
    PLACEHOLDER_FOOD: 'Traditional Beef Pho',
    OLDER_HISTORY: 'Earlier History',
    OLDER_HISTORY_DESC: (limit: number) => `Dishes you viewed in your last ${limit} visits`,
    OLDER_FOODS_TITLE: 'Previously Viewed Dishes',
    PLACEHOLDER_FOOD_2: 'Hanoi Bun Cha',
    INFO: 'Personal Info',
    UPDATE_PREFERENCES: 'Update AI Context',
    SUCCESS_UPDATE: 'Updated successfully!',
    AI_HISTORY: 'Recommendation History',
    AI_CONTEXT: 'Dietary Preferences (AI Context)',
    ONBOARDING_SUCCESS: 'Awesome!',
    ONBOARDING_PREPARING: 'Wait a moment ... !',
    STEP: (current: number, total: number) => `Step ${current} / ${total}`,
    NO_HISTORY: 'No recently viewed dishes history',
    AI_LOGIN_REQUIRED: 'Please login to use AI suggestions! ✨',
    AI_CUSTOMER_ONLY: 'AI suggestions are currently for customers only. Thank you!',
    QUESTION: 'Question',
  },
  SETTINGS: {
    TITLE: 'Account Settings',
    SUBTITLE: 'Manage your profile and account security',
    TABS: {
      PROFILE: 'Profile',
      SECURITY: 'Security',
      VERIFICATION: 'Verification',
      LANGUAGE: 'Language',
      DANGER_ZONE: 'Danger Zone',
    },
    LANG_DESC: 'Select the display language for the interface and system notifications',
    LANGUAGE_CONFIRM_TITLE: 'Confirm Language Change',
    LANGUAGE_CONFIRM_DESC: 'Are you sure you want to change the display language of the system? The page will reload.',
    SECURITY_CONFIRM_TITLE: 'Confirm Password Change',
    SECURITY_CONFIRM_DESC: 'Are you sure you want to change your account password?',
    VERIFY_CONFIRM_TITLE: 'Confirm Verification Request',
    VERIFY_CONFIRM_DESC: 'The system will send a verification link to your email. Do you want to proceed?',
    PRIVACY_CONFIRM_TITLE: 'Confirm Privacy Change',
    PRIVACY_CONFIRM_DESC: 'Are you sure you want to change the visibility of your followers/following lists on your profile page?',
    PROFILE_CONFIRM_TITLE: 'Confirm Save Changes',
    PROFILE_CONFIRM_DESC: 'Are you sure you want to save these changes to your personal profile?',
    SECURITY: {
      CURRENT_PASSWORD: 'Current password',
      NEW_PASSWORD: 'New password',
      CONFIRM_PASSWORD: 'Confirm new password',
      CHANGE_PASSWORD: 'Change Password',
      CHANGE_SUCCESS: 'Password changed successfully!',
      CHANGE_PASSWORD_ERROR: 'Failed to change password. Please try again.',
      MISMATCH: 'New passwords do not match.',
    },
    VERIFICATION: {
      TITLE: 'Verify your email address',
      LABEL: 'Enter email to verify',
      SUCCESS: 'Email verified successfully!',
      SEND_EMAIL_ERROR: 'Failed to send verification email.',
      VERIFIED: 'Account verified.',
      VERIFY_NOW: 'Verify now',
    },
    PROFILE: {
      TITLE: 'Your Profile',
      FULL_NAME: 'Full name',
      NOT_UPDATED: 'Not updated',
      EDIT_COVER: 'Edit cover image',
      FOLLOWERS: 'followers',
      FOLLOWING: 'following',
      DASHBOARD: 'Dashboard',
      FOLLOW: 'Follow',
      UNFOLLOW: 'Unfollow',
      SAVE_SUCCESS: 'Profile updated successfully!',
      BIO_EMPTY: 'This user has no bio.',
      TABS: {
        POSTS: 'Posts',
        ABOUT: 'About',
        FRIENDS: 'Friends',
        PHOTOS: 'Photos',
      },
      INTRO: {
        TITLE: 'Introduction',
        WORK: (work: string) => `Works at ${work}`,
        LIVES: (city: string) => `Lives in ${city}`,
        JOINED: (year: number) => `Joined in ${year}`,
        EDIT_DETAILS: 'Edit details',
      },
      POSTS: {
        EMPTY_TITLE: 'No posts yet',
        EMPTY_DESC: 'Start sharing your culinary experiences today!',
        THINKING: (name: string) => `What is on your mind, ${name}?`,
      },
      EDIT_MODAL: {
        TITLE: 'Edit Profile',
        SUCCESS: 'Profile updated successfully!',
        NAME: 'Display name',
        PHONE: 'Phone number',
        AVATAR: 'Avatar URL',
        COVER: 'Cover Image URL',
        BIO: 'Bio',
        ADDRESS: 'Address / Lives in',
        WORK: 'Works at',
        CITY: 'City / Province',
        DISTRICT: 'District',
        DISTRICT_PLACEHOLDER: 'Select District',
        STREET: 'Detailed Address (Street, House number...)',
        STREET_PLACEHOLDER: 'E.g., 123 Duong Lang',
        MERCHANT_SYNC: 'Merchant Sync',
        SYNC_AVATAR: 'Sync avatar as restaurant logo',
        SYNC_COVER: 'Sync cover image as restaurant cover image',
        CLOSE_SETTINGS: 'Close settings',
      },
      MODALS: {
        FOLLOWERS_TITLE: 'Followers',
        FOLLOWERS_EMPTY: 'No followers yet',
        FOLLOWING_TITLE: 'Following',
        FOLLOWING_EMPTY: 'Not following anyone yet',
        PRIVATE_LIST_ERROR: 'This list is private or hidden.',
      }
    },
    DANGER_ZONE: {
      TITLE: '⚠️ Danger Zone',
      WARNING: 'WARNING: This action is permanent and irreversible. Once you confirm deletion: All your data including personal profile, posts, likes, reviews, AI context, and restaurant branch information (if any) will be permanently deleted and CANNOT BE RECOVERED.',
      BUTTON: 'Delete my account',
      MODAL_TITLE: 'Confirm Account Deletion?',
      MODAL_WARNING: 'This action will permanently delete all your data. This operation absolutely cannot be undone!',
      PASSWORD_LABEL: 'Enter your password to confirm:',
      PASSWORD_PLACEHOLDER: 'Your account password',
      CONFIRM_BUTTON: 'Confirm delete',
      CANCEL_BUTTON: 'Cancel',
      TOAST_PASSWORD_REQUIRED: 'Please enter password to confirm.',
      TOAST_SUCCESS: 'Your account has been deleted permanently.',
      TOAST_ERROR: 'Incorrect password or an error occurred.'
    }
  },
  NAV: {
    HOME: 'Home',
    EXPLORE: 'Explore',
    OFFERS: 'Offers',
    ADMIN_PANEL: 'Admin Panel',
    RESTAURANT_PANEL: 'Store Management',
    DASHBOARD: 'Personal Dashboard',
    SETTINGS: 'Settings',
    FEATURES: 'Features',
    SEARCH_PLACEHOLDER: 'Feature search is under development!',
    USER_MENU: 'User menu',
  },
  FOOTER: {
    DESCRIPTION: 'AI-powered smart food recommendation platform, helping you find your favorite taste anywhere, anytime.',
    QUICK_LINKS: 'Quick Links',
    FOLLOW_US: 'Follow us',
    RIGHTS: '© 2026 Food AI. All rights reserved.',
    TERMS: 'Terms',
    POLICY: 'Privacy Policy',
    CONTACT: 'Contact',
  },
  HERO: {
    TITLE_START: 'What do you want to eat',
    TITLE_HIGHLIGHT: 'today?',
    DESCRIPTION: 'Tell AI about your mood, budget or preferences. We will recommend the perfect dishes near you.',
    BG_ALT: 'Homepage background',
    OPEN_AI_TOOLTIP: 'Toggle AI Assistant',
    SEARCH_PLACEHOLDER: 'How are you feeling today?',
    PLACEHOLDER_AUTH: 'Tell AI what you want to eat...',
    PLACEHOLDER_GUEST: 'Log in to chat with AI recommendations...',
    SEARCH_BUTTON: 'Search',
    AI_THINKING: 'AI is thinking...',
    SUGGESTED_TITLE: 'Recommended dishes for you:',
    FEATURES: {
      MOOD: 'Mood Recommendations',
      BUDGET: 'Budget Friendly',
      LOCATION: 'Dishes Near You',
    }
  },
  HOME: {
    NEARBY_TITLE: "Good Food Nearby",
    NEARBY_SUBTITLE: "Explore delicious food right at your location",
    TODAY_TITLE: "Today\'s Specials",
    TODAY_SUBTITLE: "Great selected choices for today",
    WEEKLY_TITLE: "Featured Weekly Hits",
    WEEKLY_SUBTITLE: "The most liked dishes of the week",
    RECOMMENDED_TITLE: "Recommended for You",
    RECOMMENDED_SUBTITLE: "Delicious dishes selected and recommended by Admin",
  },
  FORM: {
    FOOD_NAME: 'Food Name',
    PRICE: 'Price (VND)',
    DESCRIPTION: 'Description',
    IMAGE_URL: 'Image (URL)',
    TAGS: 'Tags',
    EMAIL: 'Email',
    ADDRESS: 'Address',
    PHONE: 'Phone number',
    MAP_URL: 'Google Maps Link',
    LAT: 'Latitude',
    LNG: 'Longitude',
    NOT_SET: 'Not set',
    NO_PREFERENCES: 'You have not updated your preferences yet.',
    OPINION_PLACEHOLDER: 'Enter your message here...',
    EMAIL_REQUIRED: 'Email is required',
    EMAIL_INVALID: 'Email is invalid',
    PASSWORD_REQUIRED: 'Password is required',
    PASSWORD_INVALID: 'Password must be at least 8 characters, with letters and numbers',
    CONFIRM_PASSWORD_MISMATCH: 'Confirm password does not match',
    NAME_REQUIRED: 'Name must be at least 2 characters',
    LEGAL_DOCS_REQUIRED: 'Please provide clear legal verification document details',
    PLACEHOLDERS: {
      NAME: 'John Doe',
      EMAIL: 'user123@gmail.com',
      PASSWORD: '••••••••',
      ADDRESS: 'Hanoi, Vietnam...',
      WORK: 'ABC Company...',
    }
  },
  EXPLORE: {
    TITLE: 'Explore by Category',
    TITLE_TAG: (tag: string) => tag ? `Explore "${tag}"` : 'Explore Restaurants',
    FOUND_COUNT: (count: number) => `Found ${count} matching restaurants`,
    SEARCH_IN_TAG: (tag: string) => tag ? `Search restaurants in ${tag}...` : 'Search restaurants...',
    EMPTY_TITLE: 'Sorry, no restaurants found!',
    EMPTY_DESC: 'Please try searching with another keyword.',
    LOADING: 'Loading explore page...',
    SEARCHING: 'Searching restaurants for you...',
    TAG_PLACEHOLDER: 'Enter tags separated by commas!',
    SUGGESTED_TAGS: 'Suggested:',
    ALL_DISTRICTS: 'All Districts',
  },
  FOOD: {
    DETAIL_TITLE: 'Food Description',
    RESTAURANT_TITLE: 'Restaurant Address',
    VIEW_MAP: 'View location on Map',
    NO_ADDRESS: 'No address updated',
    STORE_PAGE: 'Restaurant Page',
    REVIEWS: 'View Reviews',
    ADD_FAVORITE: 'Add to Favorites',
    VIEW_DETAIL: 'View details',
    NO_DESCRIPTION: 'No description',
    NO_IMAGE: 'No image',
    UNCATEGORIZED: 'Uncategorized',
    SYSTEM: 'System',
  },
  UI_MESSAGES: {
    CATEGORY: {
      LOAD_ERROR: 'Error loading categories',
      GROUP_NAME_REQUIRED: 'Group name is required',
      GROUP_UPDATE_SUCCESS: 'Group updated successfully',
      GROUP_ADD_SUCCESS: 'Group added successfully',
      GROUP_DELETE_SUCCESS: 'Group deleted successfully',
      CATEGORY_NAME_REQUIRED: 'Category name is required',
      CATEGORY_UPDATE_SUCCESS: 'Category updated successfully',
      CATEGORY_ADD_SUCCESS: 'Category added successfully',
      CATEGORY_DELETE_SUCCESS: 'Category deleted successfully',
      HAS_FOODS_ERROR: 'An error occurred (the category might contain food items)',
      MAX_GROUPS_LIMIT_ERROR: (max: number) => `You are allowed to create at most ${max} Groups to avoid overloading the menu.`,
      GROUP_ORDER_DUPLICATE_ERROR: (order: number) => `Display order #${order} is already in use by another group. Choose another!`,
      CATEGORY_ORDER_DUPLICATE_ERROR: (order: number) => `Display order #${order} already exists in this group. Choose another!`,
    },
    RESTAURANT: {
      SELECT_REQUIRED: 'Please select a business branch',
    },
    ADMIN: {
      UPDATE_FAILED: 'Update failed',
      UPDATE_SUCCESS: 'Updated successfully',
      LOAD_ERROR: 'Error fetching admin data:',
    },
  },
  IMPORT_EXCEL: {
    MESSAGES: {
      INVALID_FILE_TYPE: 'Please select an Excel file (.xlsx) or CSV (.csv)',
      IMPORT_SUCCESS: (created: number, appended: number) => `Import successful! Created ${created} and merged ${appended} restaurants.`,
      IMPORT_ERROR_DEFAULT: 'Error importing Excel file',
      VALID_TYPES: [
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'application/vnd.ms-excel',
        'text/csv'
      ],
      TEMPLATE_HEADERS: 'Email,Password,Owner Name,Restaurant Name,Address,Latitude,Longitude,Restaurant Map URL,Food Name,Food Price,Food Desc,Food Image URL,Food Tags\n',
      TEMPLATE_SAMPLE: 'merchant@gmail.com,password123,Nguyen Van A,Pizza Ha Noi,Ha Noi,21.0285,105.8542,https://maps.app.goo.gl/example,Pizza Hai San,150000,Pizza ngon thuong hang,https://example.com/pizza.jpg,"ngon,hai san"\n',
      TEMPLATE_FILENAME: 'merchant_template.csv',
    },
    UI: {
      TITLE: 'Bulk Import Data',
      TEMPLATE_TITLE: 'Download sample CSV/Excel Template',
      TEMPLATE_DESC: 'Use sample template for correct data parsing.',
      BTN_DOWNLOAD: 'Download Sample',
      DROPZONE_TITLE_FILE: 'Click or drag file here',
      DROPZONE_SUBTITLE_FILE: 'Supports .xlsx, .csv formats',
      BTN_REMOVE_FILE: 'Remove file',
      BTN_CANCEL: 'Cancel',
      BTN_IMPORT: 'Import Now',
      BTN_LOADING: 'Processing...'
    }
  },
  ONBOARDING: {
    BRANCH_STEP_TITLE: 'Configure location & business branches',
    BRANCH_STEP_DESC: 'Declare branch details so that AI can optimize visibility for nearby diners.',
    ADD_BRANCH_BTN: 'Add Another Branch (+)',
    BACK_BTN: 'Back',
    COMPLETE_BTN: 'Complete & Initialize',
    REQUIRED_BRANCH_FIELDS: (index: number) => `Please fill Name and Address for Branch #${index}.`,
    INVALID_COORDINATES: (index: number) => `GPS Coordinates of Branch #${index} must be valid numbers.`,
    INVALID_LATITUDE: (index: number) => `Latitude of Branch #${index} must be between -90 and 90.`,
    INVALID_LONGITUDE: (index: number) => `Longitude of Branch #${index} must be between -180 and 180.`,
    INVALID_HOURS_FORMAT: (index: number) => `Operating hours format of Branch #${index} is invalid (E.g., 08:00 - 22:00).`,
    MIN_BRANCH_REQUIRED: 'You must declare at least 1 main branch.',
    ADD_BRANCH_SUCCESS: 'Added a blank branch. Please fill details below.',
    REMOVE_BRANCH_SUCCESS: 'Removed branch from list.',
    STEP_INDICATOR: (current: number, total: number) => `Step ${current} / ${total}`,
    FORM: {
      NAME_LABEL: 'Branch Name',
      NAME_PLACEHOLDER: 'E.g., FOOD AI - Hanoi Branch',
      ADDRESS_LABEL: 'Address',
      ADDRESS_PLACEHOLDER: 'E.g., 123 Nguyen Trai, Thanh Xuan, Hanoi',
      LAT_LABEL: 'Latitude',
      LAT_PLACEHOLDER: 'E.g., 20.9760',
      LNG_LABEL: 'Longitude',
      LNG_PLACEHOLDER: 'E.g., 105.7629',
      MAP_URL_LABEL: 'Google Maps Link (Optional)',
      MAP_URL_PLACEHOLDER: 'E.g., https://maps.google.com/...',
      HOURS_LABEL: 'Operating hours (Optional)',
      HOURS_PLACEHOLDER: 'E.g., 09:00 - 21:00',
      BIO_LABEL: 'Slogan / Bio',
      BIO_PLACEHOLDER: 'E.g., Clean food, healthy eating...',
    },
    QUESTIONS: {
      CUSTOMER: {
        GOAL: {
          Q: 'What is your dietary goal?',
          DESC: 'So AI can recommend dishes that fit your health goals.',
          OPT: { WEIGHT_LOSS: 'Weight loss', MUSCLE_GAIN: 'Muscle gain', EAT_CLEAN: 'Eat Clean', ENJOY: 'Enjoyment' }
        },
        CUISINE: {
          Q: 'Which cuisine style do you prefer?',
          DESC: 'We will prioritize showing restaurants with these styles.',
          OPT: { VIETNAMESE: 'Vietnamese', KOREAN: 'Korean', JAPANESE: 'Japanese', WESTERN: 'Western' }
        },
        BUDGET: {
          Q: 'What is your budget per meal?',
          DESC: 'Suggest dishes within your budget range.',
          OPT: { UNDER_100K: 'Under 100k', '100K_200K': '100k - 200k', '200K_400K': '200k - 400k', OVER_400K: 'Above 400k' }
        },
        ALLERGIES: {
          Q: 'Do you have any food allergies?',
          DESC: 'Your safety is first. Let AI know!',
          OPT: { SEAFOOD: 'Seafood', PEANUTS: 'Peanuts', DAIRY: 'Dairy/Cheese', NONE: 'None' }
        }
      },
      RESTAURANT: {
        STYLE: {
          Q: 'What is your restaurant style?',
          DESC: 'Help diners imagine the dining space.',
          OPT: { LUXURY: 'Luxury', CASUAL: 'Casual', STREET: 'Street Food', TAKEAWAY: 'Takeaway' }
        },
        FLAVOR: {
          Q: 'What is the main flavor of your dishes?',
          DESC: 'Diners usually search by preferred flavors.',
          OPT: { SPICY: 'Spicy', SWEET: 'Sweet', SAVORY: 'Savory', LIGHT: 'Light/Fresh' }
        },
        TARGET: {
          Q: 'Who is your main target audience?',
          DESC: 'AI will prioritize showing your store to this group.',
          OPT: { STUDENTS: 'Students', OFFICE: 'Office workers', FAMILY: 'Family', TOURISTS: 'Tourists' }
        }
      }
    }
  },
  CATEGORIES: {
    NAMES: {
      WATER: 'Soup/Noodles',
      RICE: 'Rice / Sticky rice',
      SNACK: 'Snacks',
      DESSERT: 'Desserts',
      CASUAL: 'Casual',
      LUXURY: 'Premium'
    },
    TAGS: {
      TRADITIONAL: 'traditional',
      FASTFOOD: 'fast food',
      FRIED: 'fried',
      ALONE: 'solo',
      GROUP: 'group',
      OFFICE: 'office',
      SPICY: 'spicy',
      HEALTHY: 'healthy'
    }
  },
  AI_CHAT: {
    SIDEBAR: {
      NEW_CHAT: 'New Chat',
      RECENT: 'Recent Chats',
      NO_CHAT: 'No chats yet',
      CLOSE_SIDEBAR: 'Close sidebar',
      DELETE_CHAT: 'Delete chat',
      CUSTOMER: 'Customer',
      FREE_PLAN: 'Free Plan',
      REFRESH_LIST: 'Refresh list',
    },
    HEADER: {
      OPEN_SIDEBAR: 'Open sidebar',
      SIMULATE_CONTEXT: 'Weather in',
      COLLAPSE_CHAT: 'Collapse chat',
      ACTIVE: 'Active',
    },
    CONFIG: {
      WEATHER_TITLE: 'Real-time Weather',
      TEMPERATURE: 'Temperature',
      STATUS: 'Status',
      RAINY: 'Rainy 🌧️',
      DRY: 'Clear ☀️',
      LOCATION_TITLE: 'GPS Coordinates & Location',
      GPS_COORDS: 'GPS Coordinates',
      UPDATE_GPS: 'Sync current GPS',
      TIPS_TITLE: '💡 Automatic Detection Mechanism:',
      TIP_1: '1. The system automatically reads GPS coordinates from your browser to sync weather details via Open-Meteo.',
      TIP_2: '2. The AI assistant automatically analyzes real-time weather (temp, rain, wind) to recommend the best dishes.',
      WEATHER_TEMP_LIMITS: {
        MIN: 15,
        MAX: 42,
      },
      GPS_DEFAULTS: {
        LAT: 21.0285,
        LNG: 105.8542,
      },
      CITY_DEFAULTS: {
        NAME: 'Hanoi',
      },
      SYNCING_WEATHER: 'Syncing weather...',
      FEELS_LIKE: (temp: number) => `Feels like ${temp}°C`,
      HUMIDITY: 'Humidity',
      WIND_SPEED: 'Wind speed',
      NO_WEATHER_DATA: 'No weather data. Sync GPS to activate.',
      LATITUDE: 'Latitude (Lat)',
      LONGITUDE: 'Longitude (Lng)',
      UPDATE_BTN: 'Update',
    },
    FEED: {
      WELCOME: 'Hello! How can I help you today?',
      WELCOME_SUB: 'Ask me anything (E.g., "What is delicious to eat today", "Search for bun cha near me",...)',
      SUGGESTION: 'Suggestions for you:',
      SEND_MESSAGE: 'Send message',
      FEEDBACK_LIKE: '👍 Helpful',
      FEEDBACK_DISLIKE: '👎 Irrelevant',
    },
    INPUT: {
      PLACEHOLDER: 'Ask culinary AI assistant...',
      SEND: 'Send',
      SEARCH: 'Chat Now!'
    },
    PREFERENCES: {
      TITLE: 'AI Recommendations Settings',
      TAB_LIKED: 'Liked Dishes',
      TAB_DISLIKED: 'Hidden Suggestions',
      LOADING: 'Loading...',
      EMPTY_LIST: 'Empty list',
      EMPTY_LIKED_DESC: 'Click thumbs up (LIKE) on AI recommended dishes to save here.',
      EMPTY_DISLIKED_DESC: 'Click thumbs down (DISLIKE) on AI recommendations to hide and save here.',
      VOICE_INPUT_LABEL: 'Enable voice input',
      REMOVE_LIKE_SUCCESS: 'Removed dish from likes!',
      REMOVE_DISLIKE_SUCCESS: 'Removed dish from hidden recommendations!',
      LOAD_ERROR: 'Could not load preferences.',
      REMOVE_ERROR: 'Could not remove feedback. Please try again.',
      TOOLTIP_REMOVE: 'Remove feedback',
      TAB_GENERAL: 'General',
      TAB_PERSONALIZATION: 'Personalization',
      TAB_DATA_CONTROL: 'Data Control',
      TAB_ACCOUNT: 'Account',
      THEME_LABEL: 'Theme',
      THEME_MIXED: 'Mixed',
      THEME_LIGHT: 'Light',
      THEME_DARK: 'Dark',
      LANG_LABEL: 'Language',
      LANG_AUTO: 'Auto Detect',
      LANG_VI: 'Tiếng Việt',
      LANG_EN: 'English',
      DELETE_FEEDBACKS_TITLE: 'Delete All AI Feedback',
      DELETE_FEEDBACKS_DESC: 'This will delete all Liked (LIKE) and Hidden (DISLIKE) feedback history, resetting the personalization AI model.',
      DELETE_FEEDBACKS_BTN: 'Clear All Feedback',
      DELETE_FEEDBACKS_CONFIRM: 'Are you sure you want to delete all Like/Dislike history? This will also remove dishes from your favorites list!',
      DELETE_FEEDBACKS_SUCCESS: 'Feedback cleared successfully!',
      DELETE_FEEDBACKS_ERROR: 'Error clearing feedback. Please try again.',
      ACCOUNT_INFO_TITLE: 'Customer Account Info',
      ACCOUNT_NAME: 'Full Name',
      ACCOUNT_EMAIL: 'Email Address',
      ACCOUNT_ROLE: 'Account Role',
      ACCOUNT_PLAN: 'Service Plan',
    },
    CONFIRM: {
      DELETE_CHAT: 'Are you sure you want to delete this chat conversation?',
      EMPTY_CHAT_WARNING: 'You already have an empty new chat ready.',
      ERROR_FALLBACK: 'Sorry, I encountered a system issue.',
    },
    TOAST: {
      GPS_SUCCESS: 'Device GPS coordinates updated successfully.',
      GPS_ERROR: 'Could not get GPS coordinates from browser.',
      GPS_NOT_SUPPORTED: 'Browser does not support GPS.',
      LOAD_HISTORY_ERROR: 'Error loading conversation history:',
      SEND_FIRST_ERROR: 'Error sending first message:',
      GPS_WARN: 'Could not read device GPS, using fallback defaults:',
      FEEDBACK_LIKE_SUCCESS: 'Marked helpful! AI will suggest similar dishes.',
      FEEDBACK_DISLIKE_SUCCESS: 'Feedback noted! AI will restrict this dish.',
      FEEDBACK_ERROR: 'Error sending feedback.',
    }
  }
};
